<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Termination, insolvency and bankruptcy – Functioning Legal Knowledge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../flk1/dr-00-overview.html" rel="next">
<link href="../flk1/blp-05-taxation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0a4414a393388c898190164198f83909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../flk1/blp-00-overview.html">Business Law and Practice</a></li><li class="breadcrumb-item"><a href="../flk1/blp-06-termination.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Functioning Legal Knowledge</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to use this text</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Business Law and Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-00-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Business Law and Practice: what is examined</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-01-vehicles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Choosing and forming the vehicle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-02-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Running the business</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-03-stakeholders.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Stakeholders: rights, powers and protection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-04-finance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Financing the business</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-05-taxation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-06-termination.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Dispute Resolution</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-00-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Dispute Resolution: what is examined</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-01-merits-and-forum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing the dispute and choosing the forum</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-02-preaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Before proceedings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-03-commencing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Issuing, serving, pleading and responding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-04-case-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Running the claim</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-05-evidence-disclosure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Proving the case</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-06-trial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Trial, appeals and enforcement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-07-costs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Who pays, and how much</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-07-authorities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Authorities and numbers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-08-authorities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Dispute Resolution: authorities, rules and numbers</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-first-question-is-always-solvency" id="toc-the-first-question-is-always-solvency" class="nav-link active" data-scroll-target="#the-first-question-is-always-solvency"><span class="header-section-number">7.1</span> The first question is always solvency</a></li>
  <li><a href="#terminating-a-solvent-business" id="toc-terminating-a-solvent-business" class="nav-link" data-scroll-target="#terminating-a-solvent-business"><span class="header-section-number">7.2</span> Terminating a solvent business</a>
  <ul class="collapse">
  <li><a href="#members-voluntary-liquidation" id="toc-members-voluntary-liquidation" class="nav-link" data-scroll-target="#members-voluntary-liquidation"><span class="header-section-number">7.2.1</span> Members’ voluntary liquidation</a></li>
  <li><a href="#striking-off" id="toc-striking-off" class="nav-link" data-scroll-target="#striking-off"><span class="header-section-number">7.2.2</span> Striking off</a></li>
  <li><a href="#dissolving-a-partnership" id="toc-dissolving-a-partnership" class="nav-link" data-scroll-target="#dissolving-a-partnership"><span class="header-section-number">7.2.3</span> Dissolving a partnership</a></li>
  </ul></li>
  <li><a href="#is-the-company-insolvent-the-statutory-tests" id="toc-is-the-company-insolvent-the-statutory-tests" class="nav-link" data-scroll-target="#is-the-company-insolvent-the-statutory-tests"><span class="header-section-number">7.3</span> Is the company insolvent? The statutory tests</a></li>
  <li><a href="#the-corporate-procedures" id="toc-the-corporate-procedures" class="nav-link" data-scroll-target="#the-corporate-procedures"><span class="header-section-number">7.4</span> The corporate procedures</a>
  <ul class="collapse">
  <li><a href="#the-part-a1-moratorium" id="toc-the-part-a1-moratorium" class="nav-link" data-scroll-target="#the-part-a1-moratorium"><span class="header-section-number">7.4.1</span> The Part A1 moratorium</a></li>
  <li><a href="#administration" id="toc-administration" class="nav-link" data-scroll-target="#administration"><span class="header-section-number">7.4.2</span> Administration</a></li>
  <li><a href="#receivership" id="toc-receivership" class="nav-link" data-scroll-target="#receivership"><span class="header-section-number">7.4.3</span> Receivership</a></li>
  <li><a href="#company-voluntary-arrangement" id="toc-company-voluntary-arrangement" class="nav-link" data-scroll-target="#company-voluntary-arrangement"><span class="header-section-number">7.4.4</span> Company voluntary arrangement</a></li>
  <li><a href="#restructuring-plan" id="toc-restructuring-plan" class="nav-link" data-scroll-target="#restructuring-plan"><span class="header-section-number">7.4.5</span> Restructuring plan</a></li>
  <li><a href="#liquidation" id="toc-liquidation" class="nav-link" data-scroll-target="#liquidation"><span class="header-section-number">7.4.6</span> Liquidation</a></li>
  <li><a href="#check-yourself-procedures" id="toc-check-yourself-procedures" class="nav-link" data-scroll-target="#check-yourself-procedures"><span class="header-section-number">7.4.7</span> Check yourself: procedures</a></li>
  </ul></li>
  <li><a href="#clawing-assets-back-for-the-creditors" id="toc-clawing-assets-back-for-the-creditors" class="nav-link" data-scroll-target="#clawing-assets-back-for-the-creditors"><span class="header-section-number">7.5</span> Clawing assets back for the creditors</a>
  <ul class="collapse">
  <li><a href="#the-table" id="toc-the-table" class="nav-link" data-scroll-target="#the-table"><span class="header-section-number">7.5.1</span> The table</a></li>
  <li><a href="#transactions-at-an-undervalue-s.238" id="toc-transactions-at-an-undervalue-s.238" class="nav-link" data-scroll-target="#transactions-at-an-undervalue-s.238"><span class="header-section-number">7.5.2</span> Transactions at an undervalue (s.238)</a></li>
  <li><a href="#preferences-s.239" id="toc-preferences-s.239" class="nav-link" data-scroll-target="#preferences-s.239"><span class="header-section-number">7.5.3</span> Preferences (s.239)</a></li>
  <li><a href="#extortionate-credit-transactions-s.244" id="toc-extortionate-credit-transactions-s.244" class="nav-link" data-scroll-target="#extortionate-credit-transactions-s.244"><span class="header-section-number">7.5.4</span> Extortionate credit transactions (s.244)</a></li>
  <li><a href="#avoidance-of-floating-charges-s.245" id="toc-avoidance-of-floating-charges-s.245" class="nav-link" data-scroll-target="#avoidance-of-floating-charges-s.245"><span class="header-section-number">7.5.5</span> Avoidance of floating charges (s.245)</a></li>
  <li><a href="#transactions-defrauding-creditors-s.423" id="toc-transactions-defrauding-creditors-s.423" class="nav-link" data-scroll-target="#transactions-defrauding-creditors-s.423"><span class="header-section-number">7.5.6</span> Transactions defrauding creditors (s.423)</a></li>
  <li><a href="#personal-liability-of-directors" id="toc-personal-liability-of-directors" class="nav-link" data-scroll-target="#personal-liability-of-directors"><span class="header-section-number">7.5.7</span> Personal liability of directors</a></li>
  </ul></li>
  <li><a href="#the-order-of-priority" id="toc-the-order-of-priority" class="nav-link" data-scroll-target="#the-order-of-priority"><span class="header-section-number">7.6</span> The order of priority</a></li>
  <li><a href="#personal-bankruptcy" id="toc-personal-bankruptcy" class="nav-link" data-scroll-target="#personal-bankruptcy"><span class="header-section-number">7.7</span> Personal bankruptcy</a>
  <ul class="collapse">
  <li><a href="#getting-there" id="toc-getting-there" class="nav-link" data-scroll-target="#getting-there"><span class="header-section-number">7.7.1</span> Getting there</a></li>
  <li><a href="#the-consequences" id="toc-the-consequences" class="nav-link" data-scroll-target="#the-consequences"><span class="header-section-number">7.7.2</span> The consequences</a></li>
  <li><a href="#getting-out" id="toc-getting-out" class="nav-link" data-scroll-target="#getting-out"><span class="header-section-number">7.7.3</span> Getting out</a></li>
  <li><a href="#the-alternatives" id="toc-the-alternatives" class="nav-link" data-scroll-target="#the-alternatives"><span class="header-section-number">7.7.4</span> The alternatives</a></li>
  <li><a href="#check-yourself-insolvency-and-bankruptcy" id="toc-check-yourself-insolvency-and-bankruptcy" class="nav-link" data-scroll-target="#check-yourself-insolvency-and-bankruptcy"><span class="header-section-number">7.7.5</span> Check yourself: insolvency and bankruptcy</a></li>
  </ul></li>
  <li><a href="#the-solicitors-position" id="toc-the-solicitors-position" class="nav-link" data-scroll-target="#the-solicitors-position"><span class="header-section-number">7.8</span> The solicitor’s position</a></li>
  <li><a href="#chapter-review" id="toc-chapter-review" class="nav-link" data-scroll-target="#chapter-review"><span class="header-section-number">7.9</span> Chapter review</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../flk1/blp-00-overview.html">Business Law and Practice</a></li><li class="breadcrumb-item"><a href="../flk1/blp-06-termination.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-blp-termination" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><em>Assessment objective 6: the termination of a solvent business, corporate insolvency and personal bankruptcy.</em></p>
</blockquote>
<section id="the-first-question-is-always-solvency" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="the-first-question-is-always-solvency"><span class="header-section-number">7.1</span> The first question is always solvency</h2>
<p>Every question in this chapter turns on one preliminary fact, and the procedures available differ completely on either side of it.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Solvent</th>
<th>Insolvent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Company</td>
<td>Members’ voluntary liquidation; striking off</td>
<td>Administration; CVA; restructuring plan; creditors’ voluntary liquidation; compulsory liquidation; receivership</td>
</tr>
<tr class="even">
<td>Who controls it</td>
<td>The <strong>members</strong></td>
<td>The <strong>creditors</strong>, through an office-holder</td>
</tr>
<tr class="odd">
<td>Who is paid</td>
<td>Creditors in full, then members</td>
<td>Creditors in the statutory order; members rarely</td>
</tr>
<tr class="even">
<td>Directors’ duty</td>
<td>s.172, benefit of the members</td>
<td>s.172 as modified: <strong>creditors’ interests</strong> (<em>Sequana</em>)</td>
</tr>
<tr class="odd">
<td>Clawback</td>
<td>Not engaged</td>
<td>ss.238, 239, 244, 245, 423 IA 1986</td>
</tr>
</tbody>
</table>
</section>
<section id="terminating-a-solvent-business" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="terminating-a-solvent-business"><span class="header-section-number">7.2</span> Terminating a solvent business</h2>
<section id="members-voluntary-liquidation" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="members-voluntary-liquidation"><span class="header-section-number">7.2.1</span> Members’ voluntary liquidation</h3>
<p>An MVL is the orderly winding up of a <strong>solvent</strong> company. The mechanism:</p>
<ol type="1">
<li>The directors — or a majority of them, at a directors’ meeting — make a <strong>statutory declaration of solvency</strong> under <strong>s.89 IA 1986</strong>: that they have made a <strong>full inquiry</strong> into the company’s affairs and have formed the opinion that the company <strong>will be able to pay its debts in full, together with interest at the official rate, within a period not exceeding 12 months</strong> from the commencement of the winding up. A statement of the company’s assets and liabilities is annexed.</li>
<li>The declaration must be made <strong>within the five weeks immediately preceding</strong> the resolution to wind up, or on the date of it, and must be delivered to the Registrar within 15 days after the resolution.</li>
<li>The members pass a <strong>special resolution</strong> to wind up voluntarily (s.84(1)(b)), and appoint a <strong>liquidator</strong> by ordinary resolution.</li>
<li>The liquidator realises the assets, pays the creditors in full with interest, distributes the surplus to the members, and the company is dissolved three months after the final account is filed.</li>
</ol>
<p>Two sanctions attach to the declaration. Making it <strong>without reasonable grounds</strong> is a criminal offence (s.89(4)), and if the debts are <strong>not</strong> paid within the stated period it is <strong>presumed</strong> that the director had no reasonable grounds (s.89(5)). If the liquidator later forms the opinion that the company will <strong>not</strong> be able to pay its debts in full within the stated period, the liquidation <strong>converts</strong> to a creditors’ voluntary liquidation.</p>
</section>
<section id="striking-off" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="striking-off"><span class="header-section-number">7.2.2</span> Striking off</h3>
<p>For a company with no assets, no liabilities and nothing to distribute, striking off is far cheaper than an MVL. <strong>Section 1003 CA 2006</strong>: the company applies to the Registrar to be struck off. The application must be made by a majority of the directors.</p>
<p><strong>The application cannot be made</strong> if, at any time in the <strong>previous three months</strong>, the company has:</p>
<ul>
<li><strong>traded</strong> or otherwise carried on business;</li>
<li>changed its <strong>name</strong>;</li>
<li><strong>disposed of property or rights</strong> for value that, immediately before ceasing to trade, it held for disposal or gain in the normal course of trading; or</li>
<li>engaged in any other activity, except one necessary or expedient for making the application, concluding the company’s affairs, or complying with a statutory requirement.</li>
</ul>
<p>Nor can it be made while the company is subject to insolvency proceedings or a s.895 compromise (s.1005).</p>
<p>The directors must send a copy of the application to every <strong>member, creditor, employee</strong>, director who did not sign it, and pension trustee <strong>within seven days</strong> (s.1006). The Registrar advertises in the <em>Gazette</em> and, if no objection is received, strikes the company off after not less than two months.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>On dissolution, <strong>all the company’s remaining property vests in the Crown as bona vacantia</strong> (s.1012). A client who strikes off a company with a bank balance or an undistributed asset loses it. The right advice is to distribute everything first — or to use an MVL, which also has a <strong>tax</strong> advantage, because distributions in a winding up are capital receipts potentially attracting business asset disposal relief rather than income distributions.</p>
<p>Restoration is possible: <strong>administrative restoration</strong> by application to the Registrar within six years where the company was struck off under s.1000–1001 while carrying on business (s.1024), or by <strong>court order</strong> under s.1029, generally within six years.</p>
</div>
</div>
</section>
<section id="dissolving-a-partnership" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="dissolving-a-partnership"><span class="header-section-number">7.2.3</span> Dissolving a partnership</h3>
<p>The PA 1890 grounds (see <a href="blp-01-vehicles.html" class="quarto-xref"><span>Chapter 2</span></a> for the detail):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>Ground</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>s.32</td>
<td>Expiry of a fixed term; completion of the single adventure; <strong>notice</strong> by any partner in a partnership at will</td>
</tr>
<tr class="even">
<td>s.33</td>
<td><strong>Death or bankruptcy</strong> of any partner (subject to contrary agreement); at the option of the other partners, where a partner’s share is charged for their separate debt</td>
</tr>
<tr class="odd">
<td>s.34</td>
<td><strong>Illegality</strong> — mandatory, and cannot be excluded by agreement</td>
</tr>
<tr class="even">
<td>s.35</td>
<td><strong>Court order</strong>: permanent incapacity; conduct prejudicial to the business; wilful or persistent breach of the agreement; carrying on the business only at a loss; <strong>just and equitable</strong></td>
</tr>
</tbody>
</table>
<p>On dissolution, s.38 preserves each partner’s authority so far as necessary to wind up and complete unfinished transactions, and <strong>s.44</strong> governs the distribution of assets — the order and the rule that a loss of capital is a loss like any other, borne in the profit-sharing ratio (<a href="blp-03-stakeholders.html" class="quarto-xref"><span>Chapter 4</span></a>).</p>
</section>
</section>
<section id="is-the-company-insolvent-the-statutory-tests" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="is-the-company-insolvent-the-statutory-tests"><span class="header-section-number">7.3</span> Is the company insolvent? The statutory tests</h2>
<p><strong>Section 123 IA 1986</strong> provides the tests, and they are alternatives — satisfying any one is enough.</p>
<ul>
<li><strong>s.123(1)(a) — the statutory demand.</strong> A creditor owed a sum <strong>exceeding £750</strong>, then due, serves a written demand in the prescribed form at the company’s registered office, and the company for <strong>three weeks</strong> neglects to pay, secure or compound for it.</li>
<li><strong>s.123(1)(b)</strong> — execution or other process on a judgment is returned unsatisfied.</li>
<li><strong>s.123(1)(e) — the cash flow test.</strong> The company is <strong>unable to pay its debts as they fall due</strong>.</li>
<li><strong>s.123(2) — the balance sheet test.</strong> The value of the company’s assets is <strong>less than the amount of its liabilities, taking into account its contingent and prospective liabilities</strong>.</li>
</ul>
<p><em>BNY Corporate Trustee Services Ltd v Eurosail-UK 2007-3BL plc</em> [2013] UKSC 28 held that the balance sheet test is <strong>not a mechanical exercise</strong>. The court asks whether the company has reached the “point of no return” — whether, on the balance of probabilities, it will be unable to meet its liabilities. A temporary excess of liabilities over assets in a company with a long-dated liability profile does not make it insolvent.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Insolvency is not a synonym for “in financial difficulty” or “in a loss-making year”. It is the satisfaction of one of the s.123 tests. Note also that the statutory demand route is a <strong>deemed</strong> inability to pay, so a company that could pay but simply has not may be wound up on it — while a company that disputes the debt <strong>on substantial grounds</strong> cannot, because the petition would be an abuse of process.</p>
</div>
</div>
</section>
<section id="the-corporate-procedures" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="the-corporate-procedures"><span class="header-section-number">7.4</span> The corporate procedures</h2>
<p>The discriminator between them is <strong>what each is for</strong>, not their mechanics. Learn the purposes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Procedure</th>
<th>What it is for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Part A1 moratorium</strong></td>
<td>Breathing space: a payment holiday while a rescue is put together</td>
</tr>
<tr class="even">
<td><strong>Administration</strong></td>
<td>Rescue, or a better outcome for creditors than winding up; comes with a strong moratorium</td>
</tr>
<tr class="odd">
<td><strong>Company voluntary arrangement</strong></td>
<td>A <strong>compromise with the unsecured creditors</strong> so that the company can continue trading</td>
</tr>
<tr class="even">
<td><strong>Restructuring plan</strong></td>
<td>A court-sanctioned compromise that can bind <strong>dissenting classes</strong>, including secured creditors</td>
</tr>
<tr class="odd">
<td><strong>Creditors’ voluntary liquidation</strong></td>
<td>Ending an insolvent company, on the members’ initiative</td>
</tr>
<tr class="even">
<td><strong>Compulsory liquidation</strong></td>
<td>Ending a company, usually on a <strong>creditor’s</strong> petition</td>
</tr>
<tr class="odd">
<td><strong>Fixed charge receivership</strong></td>
<td>Realising a <strong>specific charged asset</strong> for the benefit of the appointing chargee</td>
</tr>
</tbody>
</table>
<section id="the-part-a1-moratorium" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="the-part-a1-moratorium"><span class="header-section-number">7.4.1</span> The Part A1 moratorium</h3>
<p>Introduced by the Corporate Insolvency and Governance Act 2020. A free-standing moratorium, obtained by the directors filing the relevant documents at court, which does <strong>not</strong> displace the directors: they remain in office and the company remains under their control, supervised by a <strong>monitor</strong> (a licensed insolvency practitioner) who must state that, in their view, <strong>it is likely that a moratorium would result in the rescue of the company as a going concern</strong>.</p>
<p>It lasts an <strong>initial 20 business days</strong>, extendable by the directors for a further 20 without creditor consent, and beyond that with creditor consent or by the court. During it the company has a <strong>payment holiday</strong> for <strong>pre-moratorium debts</strong> — but must continue to pay moratorium debts and certain excluded pre-moratorium debts, including <strong>rent for the moratorium period, wages and salary, goods and services supplied during the moratorium, and debts under financial contracts</strong>. Creditors cannot enforce security or commence proceedings without the court’s permission.</p>
</section>
<section id="administration" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="administration"><span class="header-section-number">7.4.2</span> Administration</h3>
<p>Administration is the principal <strong>rescue</strong> procedure, and its structure is examined closely.</p>
<p><strong>The purpose</strong> (paragraph 3, Schedule B1), which is a <strong>hierarchy</strong>, not a menu:</p>
<ol type="a">
<li><strong>rescuing the company as a going concern</strong>; or</li>
<li>achieving a <strong>better result for the company’s creditors as a whole</strong> than would be likely if the company were wound up without first being in administration; or</li>
<li><strong>realising property in order to make a distribution to one or more secured or preferential creditors</strong>.</li>
</ol>
<p>The administrator must perform their functions with the objective of (a) unless they think either that it is <strong>not reasonably practicable</strong>, or that (b) would achieve a better result for the creditors as a whole. They may pursue (c) only if they think it is not reasonably practicable to achieve (a) or (b), <strong>and</strong> they do not unnecessarily harm the interests of the creditors as a whole.</p>
<p><strong>Appointment</strong> — three routes, and the differences matter:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Route</th>
<th>Who</th>
<th>Requirements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Court order</strong> (para 12)</td>
<td>The company, the directors, or one or more <strong>creditors</strong></td>
<td>The company <strong>is or is likely to become unable to pay its debts</strong>, and the order is <strong>reasonably likely to achieve the purpose</strong></td>
</tr>
<tr class="even">
<td><strong>Out of court</strong> (para 14)</td>
<td>A <strong>qualifying floating charge holder</strong></td>
<td>A qualifying floating charge over the whole or substantially the whole of the company’s property, which is <strong>enforceable</strong>; two business days’ notice to any prior QFCH</td>
</tr>
<tr class="odd">
<td><strong>Out of court</strong> (para 22)</td>
<td>The <strong>company or its directors</strong></td>
<td><strong>Five business days’</strong> notice to any QFCH; not available if a winding-up petition is pending or an administrative receiver is in office, or if the company has been in administration on its own or its directors’ appointment in the previous 12 months</td>
</tr>
</tbody>
</table>
<p><strong>The moratorium</strong> (paragraphs 42–44) is the practical value of administration. Once an administrator is appointed — and, on an interim basis, from the filing of a notice of intention — no resolution or order may be made for winding up, no step may be taken to <strong>enforce security</strong> or to <strong>repossess goods</strong> under a hire-purchase agreement, no <strong>forfeiture</strong> by peaceable re-entry, and no <strong>legal process</strong> may be commenced or continued, without the administrator’s consent or the permission of the court.</p>
<p><strong>Status and duties.</strong> The administrator is an <strong>officer of the court</strong>, acts as <strong>agent of the company</strong>, and must perform their functions <strong>in the interests of the company’s creditors as a whole</strong>. They may remove and appoint directors, and the directors may not exercise a management power without consent.</p>
<p><strong>Duration</strong>: <strong>one year</strong> from appointment, extendable by consent of the creditors for up to one further year (once), or by the court for a specified period.</p>
<p><strong>Distributions</strong>: the administrator may distribute to <strong>secured and preferential</strong> creditors, but needs the <strong>permission of the court</strong> to distribute to unsecured creditors (other than the prescribed part).</p>
<p><strong>Exit</strong>: automatic termination after a year; conversion to a <strong>creditors’ voluntary liquidation</strong> (para 83) where there will be a distribution to unsecured creditors; <strong>dissolution</strong> (para 84) where there will not; or a court order.</p>
<p><strong>Pre-pack administrations</strong> — a sale of the business negotiated before appointment and executed immediately afterwards — preserve value but are open to the objection that creditors have no say. Where the buyer is <strong>connected</strong> to the company, the administrator must either obtain the approval of the creditors or an <strong>independent written opinion from a qualified evaluator</strong> before completing the disposal in the first eight weeks.</p>
</section>
<section id="receivership" class="level3" data-number="7.4.3">
<h3 data-number="7.4.3" class="anchored" data-anchor-id="receivership"><span class="header-section-number">7.4.3</span> Receivership</h3>
<p><strong>Administrative receivership is largely abolished.</strong> Section 72A of the Insolvency Act 1986, inserted by the Enterprise Act 2002, prevents the holder of a <strong>qualifying floating charge created on or after 15 September 2003</strong> from appointing an administrative receiver, subject to narrow exceptions (capital market arrangements, public-private partnerships, utility, project finance, financial market, registered social landlord and protected railway companies). Its replacement is the QFCH’s power to appoint an <strong>administrator</strong> out of court.</p>
<p><strong>Fixed charge receivership survives</strong>, and the specification names it. A <strong>fixed asset receiver</strong> (often an LPA receiver, appointed under the charge or under s.101 Law of Property Act 1925) takes control of the <strong>specific charged asset</strong>, realises it, and accounts to the appointing chargee. The receiver’s primary duty is to the <strong>appointor</strong>, not to the general body of creditors — which is precisely the difference from an administrator.</p>
</section>
<section id="company-voluntary-arrangement" class="level3" data-number="7.4.4">
<h3 data-number="7.4.4" class="anchored" data-anchor-id="company-voluntary-arrangement"><span class="header-section-number">7.4.4</span> Company voluntary arrangement</h3>
<p>A CVA is a <strong>composition in satisfaction of debts or a scheme of arrangement</strong> with the company’s creditors, under Part I IA 1986. It is a <strong>contractual compromise</strong>, supervised by an insolvency practitioner, that leaves the directors in control of the business.</p>
<ul>
<li>The <strong>directors</strong> (or an administrator or liquidator) prepare the proposal with a <strong>nominee</strong>, who reports on whether it has a reasonable prospect of being approved and implemented.</li>
<li>The proposal goes to the <strong>creditors</strong> by a decision procedure, and to the <strong>members</strong> at a meeting.</li>
<li><strong>Approval by creditors requires 75% or more in value</strong> of those responding or voting. It is <strong>invalid</strong> if <strong>more than half of the total value of creditors who are not connected</strong> with the company vote against it.</li>
<li>The <strong>members</strong> decide by simple majority; if the two decisions differ, the <strong>creditors’ decision prevails</strong>, subject to a member’s right to apply to court within 28 days.</li>
<li>Once approved, it binds <strong>every unsecured creditor entitled to vote who had notice</strong>, including those who voted against and those who did not vote at all.</li>
<li>It <strong>cannot affect the rights of a secured creditor to enforce their security, or the priority of a preferential debt</strong>, without that creditor’s consent.</li>
<li>A creditor or member may challenge it within 28 days on the ground of <strong>unfair prejudice</strong> or a <strong>material irregularity</strong> (s.6).</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>A CVA has <strong>no moratorium of its own</strong>. If the company needs protection from enforcement while the proposal is prepared, it must obtain a <strong>Part A1 moratorium</strong> or go into administration and propose the CVA from there. And a CVA cannot bind a secured creditor without consent — which is the gap that the Part 26A restructuring plan was created to fill.</p>
</div>
</div>
</section>
<section id="restructuring-plan" class="level3" data-number="7.4.5">
<h3 data-number="7.4.5" class="anchored" data-anchor-id="restructuring-plan"><span class="header-section-number">7.4.5</span> Restructuring plan</h3>
<p>Part 26A of the Companies Act 2006, introduced by CIGA 2020. Available where the company has encountered or is likely to encounter <strong>financial difficulties</strong> affecting its ability to carry on business as a going concern, and the plan’s purpose is to eliminate, reduce, prevent or mitigate the effect of those difficulties.</p>
<p>Creditors and members are divided into <strong>classes</strong>. A class approves by <strong>75% in value</strong> of those voting (there is <strong>no</strong> majority-in-number requirement, unlike a Part 26 scheme). The court then sanctions the plan — and the distinctive feature is the <strong>cross-class cram down</strong>: the court may sanction the plan notwithstanding that a class has voted against it, if satisfied that:</p>
<ul>
<li>members of the dissenting class would be <strong>no worse off</strong> than they would be in the <strong>relevant alternative</strong> (what would happen if the plan were not sanctioned); and</li>
<li>the plan has been approved by at least one class who would receive a payment, or have a genuine economic interest, in that relevant alternative.</li>
</ul>
<p>The Court of Appeal in <em>Re AGPS BondCo plc</em> [2024] EWCA Civ 24 (the <em>Adler</em> appeal) emphasised that the cram-down power is a discretion, that the “no worse off” test is a threshold rather than the whole inquiry, and that the court will scrutinise whether the plan fairly allocates the benefits of the restructuring between classes.</p>
<p>Compare the <strong>Part 26 scheme of arrangement</strong>, which requires a <strong>majority in number representing 75% in value</strong> of each class and has <strong>no</strong> cram-down.</p>
</section>
<section id="liquidation" class="level3" data-number="7.4.6">
<h3 data-number="7.4.6" class="anchored" data-anchor-id="liquidation"><span class="header-section-number">7.4.6</span> Liquidation</h3>
<p><strong>Creditors’ voluntary liquidation.</strong> Used where the company is insolvent and the members initiate the process:</p>
<ol type="1">
<li>The directors resolve to convene a general meeting; the members pass a <strong>special resolution</strong> to wind up voluntarily (s.84(1)(b)) and nominate a liquidator.</li>
<li>Within 14 days, the creditors decide on a liquidator by a <strong>decision procedure</strong> — deemed consent or a virtual meeting. <strong>The creditors’ nominee prevails</strong> over the members’.</li>
<li>The directors prepare a <strong>statement of affairs</strong>.</li>
<li>A <strong>liquidation committee</strong> may be appointed.</li>
</ol>
<p><strong>Compulsory liquidation.</strong> A <strong>petition</strong> to the court under s.124, presented by the company, the directors, a <strong>creditor</strong>, a <strong>contributory</strong> (a member, who must generally have held the shares for at least six of the last eighteen months), the Secretary of State, or the official receiver. The grounds are in s.122(1), and two matter:</p>
<ul>
<li><strong>s.122(1)(f)</strong> — the company is <strong>unable to pay its debts</strong> within s.123;</li>
<li><strong>s.122(1)(g)</strong> — it is <strong>just and equitable</strong> to wind the company up (<a href="blp-03-stakeholders.html" class="quarto-xref"><span>Chapter 4</span></a>).</li>
</ul>
<p>Three consequences of the order are examinable:</p>
<ul>
<li>The <strong>winding up is deemed to commence at the presentation of the petition</strong> (s.129), not at the order.</li>
<li><strong>Section 127</strong>: any <strong>disposition of the company’s property</strong> made after the presentation of the petition is <strong>void</strong> unless the court orders otherwise. This is why a company facing a petition applies for a <strong>validation order</strong> to keep trading and to keep its bank account operating.</li>
<li><strong>Section 130(2)</strong>: no action or proceeding may be commenced or continued against the company without the permission of the court.</li>
</ul>
<p>The <strong>official receiver</strong> becomes liquidator on the making of the order, unless and until another is appointed.</p>
<p><strong>A liquidator’s functions</strong> in any liquidation: to take control of and realise the assets, to investigate the company’s affairs and the directors’ conduct, to <strong>report to the Secretary of State</strong> on whether the directors are unfit, to pursue clawback and misfeasance claims, and to distribute in the statutory order.</p>
</section>
<section id="check-yourself-procedures" class="level3" data-number="7.4.7">
<h3 data-number="7.4.7" class="anchored" data-anchor-id="check-yourself-procedures"><span class="header-section-number">7.4.7</span> Check yourself: procedures</h3>
<p><strong>Q1.</strong> A company is trading at a loss and cannot pay its trade creditors as they fall due, but the directors believe that with a few months’ protection they could sell the business as a going concern for substantially more than a break-up would realise. A creditor has threatened to present a winding-up petition.</p>
<p>Which procedure is most appropriate?</p>
<p>A. A members’ voluntary liquidation, because the directors believe the business has value.</p>
<p>B. A company voluntary arrangement, which will impose an immediate moratorium preventing the creditor from petitioning.</p>
<p>C. Administration, whose statutory purpose includes achieving a better result for creditors as a whole than winding up, and which imposes a moratorium preventing the presentation of a winding-up petition and the enforcement of security without consent or permission.</p>
<p>D. A creditors’ voluntary liquidation, which will preserve the business.</p>
<p>E. An application to strike the company off under s.1003 CA 2006.</p>
<p><strong>Q2.</strong> A company proposes a CVA under which unsecured creditors will be paid 40 pence in the pound over three years. At the creditors’ decision procedure, creditors representing 78% in value of those voting support it. Of the creditors who are not connected with the company, 55% in value vote against it. A secured creditor with a fixed charge over the company’s premises did not vote and does not consent.</p>
<p>Which of the following is correct?</p>
<p>A. The CVA is approved, because 78% in value exceeds the 75% threshold, and it binds the secured creditor.</p>
<p>B. The CVA is not approved, because more than half of the total value of unconnected creditors voted against it.</p>
<p>C. The CVA is approved and binds all unsecured creditors, but not the secured creditor.</p>
<p>D. The CVA is approved, but only in respect of creditors who voted in favour.</p>
<p>E. The CVA requires the approval of 75% in number as well as in value.</p>
<p><strong>Q3.</strong> A winding-up petition is presented against a company on 4 May. On 20 May, before any order is made, the company pays a supplier £30,000 for goods delivered that week and continues to draw on its bank account. A winding-up order is made on 30 June.</p>
<p>Which of the following is correct?</p>
<p>A. The payments are valid, because the winding up commenced on 30 June.</p>
<p>B. The payments are void under s.127 IA 1986 unless the court orders otherwise, because the winding up is deemed to have commenced on 4 May, when the petition was presented; the company should have applied for a validation order.</p>
<p>C. The payments are voidable as preferences under s.239.</p>
<p>D. The payments are valid, because they were made in the ordinary course of business.</p>
<p>E. The payments are void, and the court has no power to validate them.</p>
<p><strong>Q4.</strong> A bank holds a qualifying floating charge over the whole of a company’s undertaking, created in 2021. The charge has become enforceable.</p>
<p>Which of the following may the bank do?</p>
<p>A. Appoint an administrative receiver, because it holds a floating charge over the whole of the undertaking.</p>
<p>B. Appoint an administrator out of court, having given two business days’ notice to any prior qualifying floating charge holder.</p>
<p>C. Present a winding-up petition without proving that the company is unable to pay its debts.</p>
<p>D. Appoint a fixed charge receiver over the whole of the company’s undertaking.</p>
<p>E. Nothing without a court order, because out-of-court appointments were abolished by the Enterprise Act 2002.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — C.</strong> Administration is the rescue procedure, its statutory purposes include achieving a better result for the creditors as a whole than winding up (paragraph 3(1)(b), Schedule B1), and the moratorium in paragraphs 42–44 prevents a winding-up order or resolution, the enforcement of security and the commencement of legal process without consent or the court’s permission. It is designed for exactly these facts.</p>
<ul>
<li><strong>A</strong> requires solvency and a declaration under s.89 that the company can pay its debts in full within 12 months, which the directors cannot make.</li>
<li><strong>B</strong> is the strongest distractor: a CVA is a good tool for compromising unsecured debt, but it has <strong>no moratorium of its own</strong>. The company would need a Part A1 moratorium or an administration.</li>
<li><strong>D</strong> and <strong>E</strong> both bring the company to an end without any attempt to preserve the business, and striking off is unavailable to a company that has traded in the last three months or is subject to insolvency proceedings.</li>
</ul>
<p><strong>Q2 — B.</strong> Approval of a CVA requires 75% or more in value of the creditors voting, <strong>and</strong> it is invalid if <strong>more than half of the total value of creditors who are not connected with the company</strong> vote against it. The 78% is satisfied but the second condition is not: 55% of unconnected creditors by value voted against.</p>
<ul>
<li><strong>A</strong> fails both on the second condition and on the proposition that a CVA binds a secured creditor, which it cannot without consent.</li>
<li><strong>C</strong> gets the secured creditor point right but overlooks the unconnected creditor test.</li>
<li><strong>D</strong> misdescribes the effect of a CVA, which binds all unsecured creditors entitled to vote who had notice.</li>
<li><strong>E</strong> imports the majority-in-number requirement from a Part 26 scheme of arrangement.</li>
</ul>
<p><strong>Q3 — B.</strong> Section 129: in a compulsory winding up the winding up is deemed to commence at the time of the <strong>presentation of the petition</strong>. Section 127: any disposition of the company’s property after that time is <strong>void</strong> unless the court otherwise orders. Payments out of the company’s bank account are dispositions. The remedy is a <strong>validation order</strong>, applied for as soon as the petition is presented.</p>
<ul>
<li><strong>A</strong> takes the date of the order.</li>
<li><strong>C</strong> applies the preference regime, which requires a desire to prefer a creditor and has its own time limits; s.127 operates automatically and needs no such element.</li>
<li><strong>D</strong> invents an ordinary course exception, though the ordinary course of business is a factor the court weighs in deciding whether to validate.</li>
<li><strong>E</strong> denies the court’s express power to order otherwise.</li>
</ul>
<p><strong>Q4 — B.</strong> Paragraph 14 of Schedule B1: the holder of a qualifying floating charge over the whole or substantially the whole of the company’s property may appoint an administrator out of court once the charge is enforceable, giving two business days’ notice to the holder of any prior qualifying floating charge.</p>
<ul>
<li><strong>A</strong> is barred by s.72A IA 1986 for floating charges created on or after 15 September 2003, subject to exceptions that do not apply to an ordinary trading company.</li>
<li><strong>C</strong> requires a ground under s.122(1), which must be established.</li>
<li><strong>D</strong> confuses a fixed charge receivership, which attaches to specific charged assets, with a general appointment over the undertaking.</li>
<li><strong>E</strong> is the opposite of the position: out-of-court appointment of an <strong>administrator</strong> is precisely what the Enterprise Act introduced.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="clawing-assets-back-for-the-creditors" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="clawing-assets-back-for-the-creditors"><span class="header-section-number">7.5</span> Clawing assets back for the creditors</h2>
<p>Five provisions, and the discrimination between them is the examinable skill. Two definitions first:</p>
<ul>
<li><strong>“Onset of insolvency”</strong> — in administration, the date on which the application or the notice of intention to appoint was filed, or the appointment took effect; in liquidation, the date of the commencement of the winding up.</li>
<li><strong>“Connected person”</strong> — a director or shadow director, an <strong>associate</strong> of one, or an associate of the company. This includes relatives, spouses and civil partners, business partners, and companies under common control. The insolvency definition of “associate” is <strong>wider</strong> than the CA 2006 definition of a connected person, and includes <strong>siblings</strong>.</li>
</ul>
<section id="the-table" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="the-table"><span class="header-section-number">7.5.1</span> The table</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Transaction at an undervalue (s.238)</th>
<th>Preference (s.239)</th>
<th>Extortionate credit (s.244)</th>
<th>Avoidance of floating charge (s.245)</th>
<th>Defrauding creditors (s.423)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Look-back</strong></td>
<td>2 years</td>
<td><strong>6 months</strong>, or <strong>2 years if connected</strong></td>
<td>3 years</td>
<td><strong>12 months</strong>, or <strong>2 years if connected</strong></td>
<td><strong>None</strong></td>
</tr>
<tr class="even">
<td><strong>Insolvency required?</strong></td>
<td>Yes, at the time or as a result (<strong>presumed</strong> if connected)</td>
<td>Yes, at the time or as a result</td>
<td>No</td>
<td>Yes for <strong>unconnected</strong> only; not required if connected</td>
<td><strong>No</strong></td>
</tr>
<tr class="odd">
<td><strong>Mental element</strong></td>
<td>None</td>
<td><strong>Desire</strong> to prefer (<strong>presumed</strong> if connected)</td>
<td>Terms grossly exorbitant</td>
<td>None</td>
<td><strong>Purpose</strong> of putting assets beyond reach or prejudicing a claim</td>
</tr>
<tr class="even">
<td><strong>Who applies</strong></td>
<td>Office-holder</td>
<td>Office-holder</td>
<td>Office-holder</td>
<td>Automatic invalidity</td>
<td>Office-holder <strong>or a victim</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="transactions-at-an-undervalue-s.238" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="transactions-at-an-undervalue-s.238"><span class="header-section-number">7.5.2</span> Transactions at an undervalue (s.238)</h3>
<p>The company made a <strong>gift</strong>, or entered into a transaction for a consideration <strong>significantly less</strong> in value than the consideration provided by the company. Compare the value <strong>in money or money’s worth</strong> on each side, from the company’s perspective.</p>
<p><strong>Defence</strong> (s.238(5)): no order will be made if the company entered into the transaction <strong>in good faith and for the purpose of carrying on its business</strong>, and at the time there were <strong>reasonable grounds for believing</strong> that it would <strong>benefit the company</strong>.</p>
</section>
<section id="preferences-s.239" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="preferences-s.239"><span class="header-section-number">7.5.3</span> Preferences (s.239)</h3>
<p>The company did something which <strong>puts a creditor, a surety or a guarantor of the company’s debts into a position which, on the company’s insolvent liquidation, would be better than it would otherwise have been in</strong> — and in deciding to do it the company was <strong>influenced by a desire</strong> to produce that effect.</p>
<p><em>Re MC Bacon Ltd</em> [1990] BCLC 324 is the case, and it is examined for two propositions:</p>
<ul>
<li><strong>Desire, not intention.</strong> The company must positively <strong>want</strong> to improve the creditor’s position; it is not enough that it knew that would be the consequence.</li>
<li>Granting security to a bank in order to secure the bank’s <strong>continued support</strong>, under commercial pressure, is <strong>not</strong> a preference: the company desired to keep trading, not to prefer the bank.</li>
</ul>
<p>The desire is <strong>presumed</strong> where the beneficiary is a <strong>connected</strong> person — other than a person connected by reason only of being an <strong>employee</strong> — and the burden shifts to them to rebut it.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>The two most productive fact patterns:</p>
<p><strong>A director repays their own loan account</strong> shortly before liquidation. The director is a creditor, they are connected, so the look-back is two years and the desire to prefer is presumed. This is the classic preference.</p>
<p><strong>A company grants a floating charge to its bank</strong> to secure an <strong>existing</strong> overdraft. That is not a transaction at an undervalue (the company gave security, not value), and it may fail the <em>MC Bacon</em> desire test — but s.245 catches it precisely: a floating charge given for <strong>past</strong> value is invalid, because the provision protects only value given <strong>at the same time as or after</strong> the creation of the charge.</p>
</div>
</div>
</section>
<section id="extortionate-credit-transactions-s.244" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="extortionate-credit-transactions-s.244"><span class="header-section-number">7.5.4</span> Extortionate credit transactions (s.244)</h3>
<p>A transaction providing credit to the company, entered into in the <strong>three years</strong> before the company entered administration or went into liquidation, whose terms require <strong>grossly exorbitant</strong> payments or otherwise grossly contravene ordinary principles of fair dealing. The transaction is <strong>presumed</strong> extortionate unless the contrary is proved.</p>
</section>
<section id="avoidance-of-floating-charges-s.245" class="level3" data-number="7.5.5">
<h3 data-number="7.5.5" class="anchored" data-anchor-id="avoidance-of-floating-charges-s.245"><span class="header-section-number">7.5.5</span> Avoidance of floating charges (s.245)</h3>
<p>A floating charge created within the <strong>relevant time</strong> is <strong>invalid</strong>, <strong>except to the extent of</strong> the aggregate of:</p>
<ul>
<li>the value of <strong>money paid</strong>, or <strong>goods or services supplied</strong>, to the company;</li>
<li>the value of any <strong>debt of the company discharged or reduced</strong>;</li>
</ul>
<p>in each case <strong>at the same time as, or after, the creation of the charge</strong>; <strong>plus interest</strong> on those amounts.</p>
<p>The relevant time is <strong>12 months</strong> before the onset of insolvency, or <strong>two years</strong> if the charge was created in favour of a <strong>connected person</strong>. For an <strong>unconnected</strong> person, the company must in addition have been <strong>unable to pay its debts</strong> at the time of the charge or have become so in consequence of it; for a <strong>connected</strong> person, that condition does not apply.</p>
<p>Note what s.245 does <strong>not</strong> do: it does not avoid the <strong>debt</strong>, only the <strong>security</strong>. The lender becomes an unsecured creditor for the amount not covered.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Worked example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Worked example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A company grants a floating charge to its bank on 1 March to secure its overdraft, which then stands at £400,000. Over the following months the bank advances a further £150,000. The company enters administration on 1 December of the same year. The bank is not connected with the company, and the company was unable to pay its debts on 1 March.</p>
<p>The charge was created within 12 months of the onset of insolvency, and the insolvency condition is satisfied. It is therefore invalid <strong>except to the extent of</strong> value given at the same time as or after its creation — the £150,000 advanced afterwards, plus interest. The security for the pre-existing £400,000 is <strong>invalid</strong>, and the bank ranks as an <strong>unsecured creditor</strong> for that sum.</p>
<p>Change one fact: the charge was granted to a <strong>director</strong> rather than the bank. The look-back becomes <strong>two years</strong>, and the requirement to show that the company was unable to pay its debts falls away entirely.</p>
</div>
</div>
</section>
<section id="transactions-defrauding-creditors-s.423" class="level3" data-number="7.5.6">
<h3 data-number="7.5.6" class="anchored" data-anchor-id="transactions-defrauding-creditors-s.423"><span class="header-section-number">7.5.6</span> Transactions defrauding creditors (s.423)</h3>
<p>The most flexible provision, and the one with no time limit. It requires:</p>
<ul>
<li>a <strong>transaction at an undervalue</strong> (defined as in s.238); and</li>
<li>that it was entered into <strong>for the purpose</strong> of putting assets beyond the reach of a person who is making, or may at some time make, a claim against the debtor, <strong>or</strong> of otherwise prejudicing that person’s interests.</li>
</ul>
<p>There is <strong>no insolvency requirement</strong>, <strong>no look-back period</strong>, and it applies to <strong>individuals as well as companies</strong>. The application may be made by an office-holder or by a <strong>victim</strong> of the transaction (with the court’s permission where the debtor is in liquidation or administration). The purpose need not be the sole or dominant purpose, but it must be a real, substantial purpose.</p>
<p><em>BTI 2014 LLC v Sequana SA</em> [2022] UKSC 25 confirmed that a <strong>dividend</strong>, though lawfully paid, can be a transaction at an undervalue within s.423.</p>
</section>
<section id="personal-liability-of-directors" class="level3" data-number="7.5.7">
<h3 data-number="7.5.7" class="anchored" data-anchor-id="personal-liability-of-directors"><span class="header-section-number">7.5.7</span> Personal liability of directors</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Provision</th>
<th>Who</th>
<th>What must be shown</th>
<th>Consequence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>s.212</strong> misfeasance</td>
<td>Officers, liquidators, administrators</td>
<td>Misapplication or retention of money or property, or breach of fiduciary or other duty</td>
<td>Summary order to repay, restore or contribute</td>
</tr>
<tr class="even">
<td><strong>s.213</strong> fraudulent trading</td>
<td><strong>Any person</strong> knowingly a party</td>
<td>Business carried on with <strong>intent to defraud</strong> creditors or for any fraudulent purpose — actual <strong>dishonesty</strong> is required</td>
<td>Contribution as the court thinks proper</td>
</tr>
<tr class="odd">
<td><strong>s.214</strong> wrongful trading</td>
<td><strong>Directors and shadow directors</strong></td>
<td>The company has gone into <strong>insolvent liquidation</strong> (or insolvent administration, s.246ZB), and at some point before the commencement the director <strong>knew or ought to have concluded that there was no reasonable prospect</strong> that the company would avoid it</td>
<td>Contribution, measured by the <strong>increase in the net deficiency</strong> caused</td>
</tr>
<tr class="even">
<td><strong>ss.216–217</strong> prohibited names</td>
<td>Directors and shadow directors in the 12 months before insolvent liquidation</td>
<td>Being a director of, or concerned in the management of, a company with the <strong>same or a similar name</strong> within <strong>five years</strong></td>
<td><strong>Criminal offence</strong> and <strong>personal liability</strong> for the debts of the new company</td>
</tr>
</tbody>
</table>
<p><strong>Wrongful trading</strong> is the one that repays attention:</p>
<ul>
<li>The standard in <strong>s.214(4)</strong> is the same <strong>dual objective/subjective</strong> standard as s.174 CA 2006: the general knowledge, skill and experience reasonably expected of a person carrying out those functions, <strong>and</strong> the general knowledge, skill and experience the director actually has.</li>
<li>The <strong>defence</strong> in <strong>s.214(3)</strong> is exacting: the director must show they took <strong>every step</strong> with a view to <strong>minimising the potential loss to the company’s creditors</strong>. Resigning is generally the wrong step; continuing to trade in the hope of a turnaround is the wrong step. Insisting on proper information, taking insolvency advice, and pressing for the company to cease trading are the right ones.</li>
<li><em>Re Produce Marketing Consortium Ltd (No 2)</em> (1989) 5 BCC 569 — the first successful claim, and the source of the measure of contribution: the increase in the company’s net deficiency between the date the directors ought to have concluded there was no reasonable prospect and the date of liquidation.</li>
<li><em>Re Continental Assurance Co of London plc</em> [2007] 2 BCLC 287 — the liquidator must show that the continued trading actually <strong>caused loss</strong>; a claim fails if the deficiency would have been the same anyway.</li>
<li><em>Re Patrick and Lyon Ltd</em> [1933] Ch 786 sets the contrast for <strong>fraudulent</strong> trading: “actual dishonesty involving … real moral blame”. Its criminal counterpart is <strong>s.993 CA 2006</strong>, which applies whether or not the company is being wound up.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fraudulent trading requires <strong>dishonesty</strong>; wrongful trading does not. Because dishonesty is hard to prove, s.214 is the practical claim, and a question describing directors who were merely over-optimistic is a wrongful trading question. Conversely, a question describing directors who took deposits for goods they knew could never be delivered is describing <strong>fraudulent</strong> trading — and note that s.213 catches <strong>any person</strong> knowingly party to it, including a solicitor or accountant.</p>
</div>
</div>
</section>
</section>
<section id="the-order-of-priority" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="the-order-of-priority"><span class="header-section-number">7.6</span> The order of priority</h2>
<p>This ranking is examined directly and repays memorising. In a <strong>liquidation</strong>, the assets are applied:</p>
<ol type="1">
<li><strong>Fixed charge holders</strong>, out of the proceeds of the assets subject to their charge. (Strictly, those assets are outside the estate; any surplus falls into it, and any shortfall makes the chargee an unsecured creditor for the balance.)</li>
<li><strong>Expenses of the winding up</strong>, including the liquidator’s remuneration.</li>
<li><strong>Preferential debts</strong>, and within them:
<ul>
<li><strong>Ordinary preferential debts</strong> — employees’ <strong>unpaid wages</strong> for the <strong>four months</strong> before the relevant date, capped at <strong>£800</strong> per employee; <strong>accrued holiday pay</strong> (uncapped); certain occupational pension scheme contributions; and money advanced to pay those wages.</li>
<li><strong>Secondary preferential debts</strong> — <strong>HMRC</strong> in respect of <strong>VAT, PAYE, employee NICs, construction industry scheme deductions and student loan deductions</strong>, for debts arising from 1 December 2020.</li>
</ul></li>
<li><strong>The prescribed part</strong> — a fund carved out of the <strong>floating charge</strong> realisations for the unsecured creditors: <strong>50% of the first £10,000</strong>, plus <strong>20% of the remainder</strong>, subject to a cap of <strong>£800,000</strong> where the floating charge was created on or after 6 April 2020 (£600,000 for earlier charges). It need not be set aside if the net property is less than £10,000 and the office-holder thinks the cost of distributing it would be disproportionate.</li>
<li><strong>Floating charge holders.</strong></li>
<li><strong>Unsecured (non-preferential) creditors</strong>, <em>pari passu</em>.</li>
<li><strong>Interest</strong> on the unsecured debts since the commencement of the winding up.</li>
<li><strong>Shareholders</strong>, in accordance with the rights attaching to their shares — preference capital first if the articles so provide, then the ordinary shareholders.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Three points generate most of the wrong answers.</p>
<p><strong>HMRC is only partly preferential.</strong> VAT, PAYE and employee NICs are secondary preferential debts, because the company collected that money from others. <strong>Corporation tax and employer’s NICs are not</strong> — they rank as ordinary unsecured debts.</p>
<p><strong>Crystallisation does not promote a floating charge.</strong> A floating charge that has crystallised is still a floating charge for the purposes of this ranking. It remains behind the expenses, the preferential creditors and the prescribed part.</p>
<p><strong>The prescribed part comes out of the floating charge holder’s money</strong>, not out of the fixed charge realisations, and it is for the unsecured creditors only. A floating charge holder who is left with a shortfall cannot claim a share of the prescribed part for that shortfall.</p>
</div>
</div>
</section>
<section id="personal-bankruptcy" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="personal-bankruptcy"><span class="header-section-number">7.7</span> Personal bankruptcy</h2>
<section id="getting-there" class="level3" data-number="7.7.1">
<h3 data-number="7.7.1" class="anchored" data-anchor-id="getting-there"><span class="header-section-number">7.7.1</span> Getting there</h3>
<p><strong>A creditor’s petition</strong> requires a debt (or aggregate debts) of at least <strong>£5,000</strong>, which is <strong>unsecured</strong>, for a <strong>liquidated</strong> sum, payable immediately or at a future date, and which the debtor appears <strong>unable to pay</strong> or to have no reasonable prospect of paying. Inability is usually established by serving a <strong>statutory demand</strong> which the debtor fails to comply with, or to apply to set aside, within <strong>three weeks</strong>.</p>
<p><strong>A debtor</strong> no longer petitions. Since 2016 they make an <strong>online application to an adjudicator</strong>, who makes the bankruptcy order if the criteria are met.</p>
<p>The <strong>supervisor</strong> of, or a person bound by, an <strong>IVA</strong> may also petition.</p>
</section>
<section id="the-consequences" class="level3" data-number="7.7.2">
<h3 data-number="7.7.2" class="anchored" data-anchor-id="the-consequences"><span class="header-section-number">7.7.2</span> The consequences</h3>
<p>On the making of the order, the <strong>official receiver</strong> becomes trustee unless and until an insolvency practitioner is appointed. The bankrupt’s <strong>estate vests automatically</strong> in the trustee — no conveyance is needed.</p>
<p><strong>The estate</strong> is all property belonging to or vested in the bankrupt at the commencement of the bankruptcy. <strong>Excluded</strong>:</p>
<ul>
<li><strong>tools, books, vehicles and other items of equipment</strong> necessary to the bankrupt for use personally in their employment, business or vocation;</li>
<li><strong>clothing, bedding, furniture, household equipment and provisions</strong> necessary for satisfying the basic domestic needs of the bankrupt and their family;</li>
<li>property held by the bankrupt <strong>on trust</strong> for another;</li>
<li>most <strong>pension</strong> rights, and certain tenancies.</li>
</ul>
<p><strong>Income</strong> is not part of the estate, but the trustee may obtain an <strong>income payments order</strong> — or agree an income payments agreement — requiring the bankrupt to pay over surplus income for up to <strong>three years</strong>, leaving enough to meet the reasonable domestic needs of the bankrupt and their family.</p>
<p><strong>After-acquired property</strong> may be claimed by the trustee by notice, generally within 42 days of becoming aware of it.</p>
<p><strong>The family home</strong> attracts two special rules:</p>
<ul>
<li><strong>Section 283A</strong>: the bankrupt’s interest in a dwelling house which is the sole or principal residence of the bankrupt, their spouse or civil partner, or a former spouse or civil partner, <strong>revests in the bankrupt</strong> if the trustee takes no relevant step within <strong>three years</strong> — the “use it or lose it” rule.</li>
<li><strong>Section 335A</strong>: on an application for an order for sale, the court weighs the creditors’ interests against the needs of the family; but <strong>after one year</strong> from vesting, it must assume, <strong>unless the circumstances are exceptional</strong>, that the interests of the creditors <strong>outweigh all other considerations</strong>. Exceptional circumstances are construed narrowly, and the ordinary hardship of losing a home is not enough.</li>
</ul>
<p><strong>Restrictions during bankruptcy</strong>: the bankrupt may not obtain credit of <strong>£500</strong> or more without disclosing their status, may not act as a <strong>company director</strong> or be concerned in the management of a company without the court’s leave, and may not trade under a different name without disclosure.</p>
</section>
<section id="getting-out" class="level3" data-number="7.7.3">
<h3 data-number="7.7.3" class="anchored" data-anchor-id="getting-out"><span class="header-section-number">7.7.3</span> Getting out</h3>
<p><strong>Discharge is automatic after one year</strong> (s.279), and may be earlier on the official receiver’s certificate. Discharge releases the bankrupt from most <strong>bankruptcy debts</strong>, but <strong>not</strong> from:</p>
<ul>
<li><strong>fines</strong> and other penalties;</li>
<li>obligations under a <strong>family maintenance or property order</strong>;</li>
<li><strong>student loans</strong>;</li>
<li>damages for <strong>personal injury</strong> (unless the court orders otherwise);</li>
<li>debts incurred by <strong>fraud</strong> or fraudulent breach of trust.</li>
</ul>
<p>Where the bankrupt’s conduct was culpable, the court may make a <strong>bankruptcy restrictions order</strong>, or the bankrupt may give an <strong>undertaking</strong>, for between <strong>two and fifteen years</strong>, continuing the restrictions after discharge.</p>
<p><strong>Clawback in bankruptcy</strong> mirrors the corporate provisions: <strong>s.339</strong> transactions at an undervalue (<strong>5 years</strong>), <strong>s.340</strong> preferences (<strong>6 months</strong>, or <strong>2 years</strong> if in favour of an <strong>associate</strong>), with the insolvency requirement presumed for associates, and <strong>s.423</strong> transactions defrauding creditors.</p>
</section>
<section id="the-alternatives" class="level3" data-number="7.7.4">
<h3 data-number="7.7.4" class="anchored" data-anchor-id="the-alternatives"><span class="header-section-number">7.7.4</span> The alternatives</h3>
<p><strong>Individual voluntary arrangement</strong> (Part VIII IA 1986). A composition or scheme with creditors, proposed by the debtor with a <strong>nominee</strong> and, if approved, implemented by a <strong>supervisor</strong>. The debtor may apply for an <strong>interim order</strong> giving protection from enforcement while the proposal is considered. Approval requires <strong>75% or more in value</strong> of the creditors responding to the decision procedure, and is invalid if <strong>more than half in value of the creditors who are not associates</strong> vote against. It binds every unsecured creditor entitled to vote who had notice, and does not affect secured creditors’ rights without consent. A creditor may challenge within 28 days for unfair prejudice or material irregularity.</p>
<p>An IVA avoids the stigma, the restrictions and the automatic vesting of bankruptcy, and usually produces a better return for creditors — which is why it is the answer where the debtor has a continuing income or a business worth preserving.</p>
<p><strong>Debt relief order.</strong> For debtors with very little: <strong>qualifying debts of £50,000 or less</strong>, <strong>assets of £2,000 or less</strong> (disregarding a single motor vehicle worth up to <strong>£4,000</strong>), and <strong>surplus monthly income of £75 or less</strong>. Applied for through an approved intermediary to the official receiver, with no fee. It imposes a <strong>12-month moratorium</strong>, after which the qualifying debts are discharged.</p>
</section>
<section id="check-yourself-insolvency-and-bankruptcy" class="level3" data-number="7.7.5">
<h3 data-number="7.7.5" class="anchored" data-anchor-id="check-yourself-insolvency-and-bankruptcy"><span class="header-section-number">7.7.5</span> Check yourself: insolvency and bankruptcy</h3>
<p><strong>Q1.</strong> Eight months before the company entered insolvent liquidation, a director procured the company to repay in full a £70,000 loan he had made to it, at a time when the company was unable to pay its debts. Other creditors received nothing.</p>
<p>Which of the following is correct?</p>
<p>A. There is no remedy, because the director was entitled to be repaid a debt genuinely owed.</p>
<p>B. The liquidator may apply to set the repayment aside as a <strong>preference</strong> under s.239: the director is a creditor who was put in a better position, the look-back period for a connected person is two years, and the desire to prefer is presumed.</p>
<p>C. The liquidator may apply under s.238, because the company received no consideration for the payment.</p>
<p>D. The repayment may be attacked only under s.423, because there is no time limit.</p>
<p>E. There is no remedy, because the payment was made more than six months before the liquidation.</p>
<p><strong>Q2.</strong> A company granted a floating charge to its bank on 1 September to secure its existing overdraft of £250,000. The bank advanced no new money afterwards. The company, which was unable to pay its debts on 1 September, entered administration on 1 June the following year. The bank is unconnected with the company.</p>
<p>Which of the following is correct?</p>
<p>A. The charge is valid in full, because it was properly registered within 21 days.</p>
<p>B. The charge is invalid in full under s.245 IA 1986, because no money was paid, no goods or services were supplied and no debt was discharged at the same time as or after its creation; the bank ranks as an unsecured creditor for the £250,000.</p>
<p>C. The charge is valid, because the look-back period for an unconnected person is six months.</p>
<p>D. The charge is invalid, and the underlying debt of £250,000 is also extinguished.</p>
<p>E. The charge is valid, because the company received consideration in the form of the bank’s forbearance.</p>
<p><strong>Q3.</strong> A company goes into liquidation. After paying the fixed charge holder out of the charged property and meeting the expenses of the liquidation, the liquidator has £900,000 of floating charge realisations. Employees are owed £30,000 in wages for the last four months (five employees, £6,000 each), HMRC is owed £120,000 of VAT and PAYE and £80,000 of corporation tax, and the floating charge holder is owed £2 million. Unsecured trade creditors are owed £700,000. The floating charge was created in 2023.</p>
<p>Which of the following correctly states the order in which the £900,000 is applied?</p>
<p>A. Floating charge holder in full, then anything left to the preferential creditors and then the unsecured creditors.</p>
<p>B. Preferential debts (employees up to £800 each, then HMRC’s VAT and PAYE), then the prescribed part for the unsecured creditors, then the floating charge holder, then the remaining unsecured creditors including HMRC’s corporation tax claim.</p>
<p>C. All of HMRC’s claims as preferential debts, then the employees, then the floating charge holder.</p>
<p>D. The unsecured creditors <em>pari passu</em> with the floating charge holder.</p>
<p>E. Employees in full, then the floating charge holder, then HMRC.</p>
<p><strong>Q4.</strong> A bankrupt’s only substantial asset is a half share in the family home, in which his spouse and two young children live. Fourteen months after the bankruptcy order, the trustee applies for an order for sale. The spouse resists on the ground that the children would have to change schools.</p>
<p>Which of the following is correct?</p>
<p>A. The court will refuse an order for sale, because the interests of the children are paramount.</p>
<p>B. The trustee cannot apply, because the interest in the home has revested in the bankrupt.</p>
<p>C. Under s.335A IA 1986, more than one year having elapsed since the interest vested in the trustee, the court must assume that the interests of the creditors outweigh all other considerations unless the circumstances are exceptional; the need to change schools is unlikely to be exceptional.</p>
<p>D. The court will postpone sale until the youngest child reaches 18.</p>
<p>E. The bankrupt’s interest in a family home never forms part of the estate.</p>
<p><strong>Q5.</strong> A director realises that his company has no reasonable prospect of avoiding insolvent liquidation. He continues trading for a further eight months, hoping for a large contract that never comes, and takes no advice. The company’s net deficiency increases by £400,000 over that period.</p>
<p>Which of the following is correct?</p>
<p>A. He is liable for fraudulent trading under s.213, because he knew the company could not pay.</p>
<p>B. He has a defence under s.214(3), because he honestly believed the contract would materialise.</p>
<p>C. He may be ordered to contribute to the company’s assets for wrongful trading under s.214: he ought to have concluded there was no reasonable prospect of avoiding insolvent liquidation, and he did not take every step to minimise the potential loss to creditors; the measure is the increase in the net deficiency.</p>
<p>D. He has no liability, because a director owes duties only to the company and not to creditors.</p>
<p>E. He may resign to avoid liability, because s.214 applies only to directors in office at the date of liquidation.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — B.</strong> Section 239: the repayment put a <strong>creditor</strong> (the director) in a better position on the company’s insolvent liquidation than he would otherwise have been in. He is a <strong>connected person</strong>, so the relevant time under s.240 is <strong>two years</strong> rather than six months, and the requisite <strong>desire to prefer</strong> is <strong>presumed</strong> unless he rebuts it. The company was insolvent at the time, satisfying s.240(2).</p>
<ul>
<li><strong>A</strong> confuses entitlement to the debt with the propriety of paying it ahead of everyone else.</li>
<li><strong>C</strong> misidentifies the provision: the company discharged a genuine liability, so it received consideration and this is not a transaction at an undervalue.</li>
<li><strong>D</strong> is available in principle only if the transaction were at an undervalue, which it is not.</li>
<li><strong>E</strong> applies the unconnected look-back period.</li>
</ul>
<p><strong>Q2 — B.</strong> Section 245. The charge was created within <strong>12 months</strong> of the onset of insolvency and the company was unable to pay its debts at the time, so the charge is invalid <strong>except to the extent of</strong> value given <strong>at the same time as or after</strong> its creation. Nothing was given: the charge secured a <strong>past</strong> debt. The charge is therefore invalid in its entirety and the bank is unsecured for £250,000.</p>
<ul>
<li><strong>A</strong> confuses registration with validity. A properly registered charge can still be avoided by s.245.</li>
<li><strong>C</strong> states the wrong period.</li>
<li><strong>D</strong> overstates the effect: s.245 invalidates the <strong>security</strong>, not the debt.</li>
<li><strong>E</strong> is the tempting commercial answer, but forbearance is not “money paid, or goods or services supplied” within s.245(2).</li>
</ul>
<p><strong>Q3 — B.</strong> The statutory order. Preferential debts come before the floating charge holder: the employees’ wages, but capped at <strong>£800 each</strong> (£4,000 in total, with the remaining £26,000 ranking as unsecured), and HMRC’s <strong>VAT and PAYE</strong> as secondary preferential debts. <strong>Corporation tax is not preferential</strong> and ranks as an ordinary unsecured debt. The <strong>prescribed part</strong> is then carved out of the floating charge realisations for the unsecured creditors — 50% of the first £10,000 plus 20% of the remainder, capped at £800,000. Only then does the floating charge holder take.</p>
<ul>
<li><strong>A</strong> inverts the whole ranking.</li>
<li><strong>C</strong> treats all of HMRC’s claims as preferential and puts them ahead of the employees; ordinary preferential debts rank ahead of secondary preferential debts.</li>
<li><strong>D</strong> ignores the security altogether.</li>
<li><strong>E</strong> pays the employees in full, ignoring the £800 cap, and omits the prescribed part.</li>
</ul>
<p><strong>Q4 — C.</strong> Section 335A(3): where the application is made <strong>more than one year</strong> after the first vesting of the estate in the trustee, the court must assume, <strong>unless the circumstances of the case are exceptional</strong>, that the interests of the bankrupt’s creditors <strong>outweigh all other considerations</strong>. The ordinary consequences of a family losing its home — including disruption to children’s schooling — are not exceptional.</p>
<ul>
<li><strong>A</strong> applies a paramountcy principle that does not exist here.</li>
<li><strong>B</strong> misapplies s.283A: revesting occurs after <strong>three years</strong>, and only if the trustee has taken no relevant step. Fourteen months is well within the period, and the application is itself a relevant step.</li>
<li><strong>D</strong> describes an order the court would make only in genuinely exceptional circumstances.</li>
<li><strong>E</strong> is simply wrong: the bankrupt’s beneficial interest in the home forms part of the estate.</li>
</ul>
<p><strong>Q5 — C.</strong> Section 214 IA 1986. The company went into insolvent liquidation; before the commencement the director knew, or ought to have concluded, that there was no reasonable prospect of avoiding it; and he cannot show under s.214(3) that he took <strong>every step</strong> with a view to minimising the potential loss to creditors — trading on in hope, without advice, is the opposite. The contribution is measured by the <strong>increase in the net deficiency</strong> caused (<em>Re Produce Marketing Consortium (No 2)</em>), here £400,000, subject to the causation requirement in <em>Re Continental Assurance</em>.</p>
<ul>
<li><strong>A</strong> requires <strong>dishonesty</strong> and “real moral blame” (<em>Re Patrick and Lyon</em>). Misplaced optimism is not fraud.</li>
<li><strong>B</strong> misstates the defence: honest belief is not the test; taking <strong>every step</strong> to minimise loss is.</li>
<li><strong>D</strong> is the <em>Sequana</em> structural error, and in any event s.214 is a statutory liability independent of the general duties.</li>
<li><strong>E</strong> is wrong: s.214 applies to a person who <strong>was</strong> a director at the relevant time, and resigning is generally not a step that minimises loss to creditors.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="the-solicitors-position" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="the-solicitors-position"><span class="header-section-number">7.8</span> The solicitor’s position</h2>
<p><strong>Discovering that a client company is trading while insolvent.</strong> This is the scenario the specification invites, and the answer has several strands:</p>
<ul>
<li><strong>Advise the directors</strong> of their duties: that the s.172 duty is now modified so that creditors’ interests must be considered (<em>Sequana</em>), and of the risk of personal liability under s.214, of disqualification, and of the clawback provisions.</li>
<li><strong>Advise them to take specialist insolvency advice</strong> immediately, from a licensed insolvency practitioner, and to keep a written record of the board’s deliberations. The record is often the best evidence of whether they took every step to minimise loss.</li>
<li><strong>Do not advise or assist a course of action that would be a fraud on creditors</strong> — disposing of assets at an undervalue, preferring a connected creditor, or continuing to take deposits for goods that cannot be supplied. Assisting knowingly makes the solicitor a party to fraudulent trading under s.213 and, in the criminal sphere, s.993 CA 2006.</li>
<li><strong>Remember who the client is.</strong> The company is the client, not the directors. Where their interests diverge — as they do once personal liability is in prospect — the directors need separate advice.</li>
<li><strong>Confidentiality</strong> is owed to the company and survives; it is not displaced merely because the solicitor disapproves of the directors’ conduct. The limited exceptions are narrow.</li>
<li><strong>Money laundering.</strong> If the solicitor knows or suspects that property represents the proceeds of criminal conduct, the reporting obligations under the Proceeds of Crime Act 2002 are engaged, and tipping off is an offence.</li>
<li><strong>Fees.</strong> A solicitor who takes payment from a company they know to be insolvent, in preference to other creditors, may find the payment attacked as a preference — and should consider taking money on account from a third party instead.</li>
</ul>
</section>
<section id="chapter-review" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="chapter-review"><span class="header-section-number">7.9</span> Chapter review</h2>
<p><strong>Q1.</strong> A company has ceased trading, has no assets and no liabilities, and its two directors want the cheapest way to bring it to an end. It last traded five months ago and has done nothing since except close its bank account.</p>
<p>Which of the following is correct?</p>
<p>A. It must go into members’ voluntary liquidation, because only a liquidator can dissolve a company.</p>
<p>B. The directors may apply to the Registrar to strike the company off under s.1003 CA 2006, having not traded for more than three months; they must send a copy of the application to every member, creditor, employee and pension trustee within seven days.</p>
<p>C. It must go into creditors’ voluntary liquidation, because it has ceased trading.</p>
<p>D. The directors may simply stop filing, and the company will be struck off automatically without further obligation.</p>
<p>E. Striking off is unavailable because the company has traded within the last twelve months.</p>
<p><strong>Q2.</strong> Which of the following statements about the <em>Sequana</em> creditor duty is correct?</p>
<p>A. It is a free-standing duty owed directly to creditors, who may sue the directors.</p>
<p>B. It is engaged whenever a company has any contingent liability that might one day exceed its assets.</p>
<p>C. It is a modification of the s.172 duty owed to the company, engaged when the company is insolvent or bordering on insolvency, or when an insolvent liquidation or administration is probable, with creditors’ interests weighing more heavily as insolvency approaches.</p>
<p>D. It replaces the s.172 duty entirely from the moment the company makes a loss.</p>
<p>E. It applies only after a liquidator has been appointed.</p>
<p><strong>Q3.</strong> An individual owes £46,000 to a range of creditors, has no assets beyond a car worth £3,200 and household goods, and has £60 a month of surplus income after meeting reasonable domestic needs.</p>
<p>Which procedure is most likely to be appropriate?</p>
<p>A. Bankruptcy on a creditor’s petition, since the debts exceed £5,000.</p>
<p>B. An individual voluntary arrangement, since 75% in value of the creditors will approve it.</p>
<p>C. A debt relief order: the qualifying debts are under £50,000, the assets are under £2,000 disregarding a motor vehicle worth up to £4,000, and the surplus monthly income is under £75.</p>
<p>D. A Part A1 moratorium.</p>
<p>E. A company voluntary arrangement.</p>
<p><strong>Q4.</strong> A creditor is owed £4,000 by a company which has ignored every request for payment. The creditor wishes to present a winding-up petition and serves a statutory demand.</p>
<p>Which of the following is correct?</p>
<p>A. The demand is ineffective, because a company statutory demand requires a debt of at least £5,000.</p>
<p>B. The demand may found a petition: s.123(1)(a) requires only a debt exceeding £750, and the creditor may petition once three weeks have elapsed — though the company may restrain the petition if it disputes the debt on substantial grounds.</p>
<p>C. The demand is effective, but the creditor must in addition prove that the company is balance sheet insolvent under s.123(2).</p>
<p>D. The creditor must first obtain judgment against the company before serving a statutory demand.</p>
<p>E. The demand is effective only if it is served personally on a director of the company.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — B.</strong> Section 1003 CA 2006 permits a company to apply to be struck off provided it has not, in the <strong>previous three months</strong>, traded, changed its name, disposed of property for value held for disposal in the normal course of trading, or engaged in any other activity except one necessary for the application or for concluding its affairs. Five months since trading satisfies that. Section 1006 requires the copy application to go to members, creditors, employees, non-signing directors and pension trustees within <strong>seven days</strong>.</p>
<ul>
<li><strong>A</strong> and <strong>C</strong> impose a liquidation that is unnecessary where there are no assets and no liabilities.</li>
<li><strong>D</strong> describes what may happen in practice but ignores the application procedure and the directors’ obligations, and exposes them to filing offences and disqualification under s.3 CDDA.</li>
<li><strong>E</strong> applies the wrong period; the bar is three months, not twelve.</li>
</ul>
<p><strong>Q2 — C.</strong> <em>BTI 2014 LLC v Sequana SA</em> [2022] UKSC 25.</p>
<ul>
<li><strong>A</strong> is the recurring structural error; the duty is owed to the company.</li>
<li><strong>B</strong> applies the “real risk” trigger the Supreme Court rejected.</li>
<li><strong>D</strong> and <strong>E</strong> state the wrong trigger points; the duty modifies s.172 rather than replacing it, and it operates before any office-holder is appointed.</li>
</ul>
<p><strong>Q3 — C.</strong> The DRO criteria are met on every limb: qualifying debts of £50,000 or less, assets of £2,000 or less disregarding a single motor vehicle worth up to £4,000, and surplus monthly income of £75 or less. A DRO costs nothing and produces discharge after a 12-month moratorium.</p>
<ul>
<li><strong>A</strong> is available to a creditor but is disproportionate and would recover almost nothing.</li>
<li><strong>B</strong> presupposes an outcome and, with £60 a month, offers creditors very little.</li>
<li><strong>D</strong> and <strong>E</strong> are corporate procedures and are not available to an individual.</li>
</ul>
<p><strong>Q4 — B.</strong> Section 123(1)(a) requires a debt <strong>exceeding £750</strong>, and £4,000 does. The £5,000 threshold belongs to a <strong>bankruptcy</strong> petition against an individual, and that contrast is what the question is testing. The qualification in option B is real: a company that disputes the debt on <strong>substantial grounds</strong> can restrain the petition as an abuse of process, so a statutory demand is the wrong tool for a genuinely disputed debt.</p>
<ul>
<li><strong>A</strong> imports the bankruptcy threshold.</li>
<li><strong>C</strong> treats the s.123 tests as cumulative. They are <strong>alternatives</strong>: satisfying s.123(1)(a) is enough, and the balance sheet test need not also be proved.</li>
<li><strong>D</strong> invents a judgment requirement; the statutory demand exists precisely so that judgment is not needed.</li>
<li><strong>E</strong> invents a service requirement. Section 123(1)(a) requires the demand to be served by leaving it at the company’s <strong>registered office</strong>.</li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../flk1/blp-05-taxation.html" class="pagination-link" aria-label="Taxation of the business and its stakeholders">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../flk1/dr-00-overview.html" class="pagination-link" aria-label="Dispute Resolution: what is examined">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Dispute Resolution: what is examined</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>