<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Taxation of the business and its stakeholders – Functioning Legal Knowledge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../flk1/blp-06-termination.html" rel="next">
<link href="../flk1/blp-04-finance.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0a4414a393388c898190164198f83909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../flk1/blp-00-overview.html">Business Law and Practice</a></li><li class="breadcrumb-item"><a href="../flk1/blp-05-taxation.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Functioning Legal Knowledge</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to use this text</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Business Law and Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-00-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Business Law and Practice: what is examined</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-01-vehicles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Choosing and forming the vehicle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-02-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Running the business</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-03-stakeholders.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Stakeholders: rights, powers and protection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-04-finance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Financing the business</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-05-taxation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-06-termination.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-07-authorities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Authorities and numbers</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#how-to-use-this-chapter" id="toc-how-to-use-this-chapter" class="nav-link active" data-scroll-target="#how-to-use-this-chapter"><span class="header-section-number">6.1</span> How to use this chapter</a></li>
  <li><a href="#the-map" id="toc-the-map" class="nav-link" data-scroll-target="#the-map"><span class="header-section-number">6.2</span> The map</a></li>
  <li><a href="#income-tax" id="toc-income-tax" class="nav-link" data-scroll-target="#income-tax"><span class="header-section-number">6.3</span> Income tax</a>
  <ul class="collapse">
  <li><a href="#who-and-what" id="toc-who-and-what" class="nav-link" data-scroll-target="#who-and-what"><span class="header-section-number">6.3.1</span> Who and what</a></li>
  <li><a href="#the-computation" id="toc-the-computation" class="nav-link" data-scroll-target="#the-computation"><span class="header-section-number">6.3.2</span> The computation</a></li>
  <li><a href="#computing-trading-profits" id="toc-computing-trading-profits" class="nav-link" data-scroll-target="#computing-trading-profits"><span class="header-section-number">6.3.3</span> Computing trading profits</a></li>
  <li><a href="#capital-allowances" id="toc-capital-allowances" class="nav-link" data-scroll-target="#capital-allowances"><span class="header-section-number">6.3.4</span> Capital allowances</a></li>
  <li><a href="#relieving-trading-losses" id="toc-relieving-trading-losses" class="nav-link" data-scroll-target="#relieving-trading-losses"><span class="header-section-number">6.3.5</span> Relieving trading losses</a></li>
  <li><a href="#collection" id="toc-collection" class="nav-link" data-scroll-target="#collection"><span class="header-section-number">6.3.6</span> Collection</a></li>
  <li><a href="#check-yourself-income-tax" id="toc-check-yourself-income-tax" class="nav-link" data-scroll-target="#check-yourself-income-tax"><span class="header-section-number">6.3.7</span> Check yourself: income tax</a></li>
  </ul></li>
  <li><a href="#national-insurance-contributions" id="toc-national-insurance-contributions" class="nav-link" data-scroll-target="#national-insurance-contributions"><span class="header-section-number">6.4</span> National Insurance contributions</a></li>
  <li><a href="#capital-gains-tax" id="toc-capital-gains-tax" class="nav-link" data-scroll-target="#capital-gains-tax"><span class="header-section-number">6.5</span> Capital gains tax</a>
  <ul class="collapse">
  <li><a href="#the-four-questions" id="toc-the-four-questions" class="nav-link" data-scroll-target="#the-four-questions"><span class="header-section-number">6.5.1</span> The four questions</a></li>
  <li><a href="#the-computation-1" id="toc-the-computation-1" class="nav-link" data-scroll-target="#the-computation-1"><span class="header-section-number">6.5.2</span> The computation</a></li>
  <li><a href="#the-business-reliefs" id="toc-the-business-reliefs" class="nav-link" data-scroll-target="#the-business-reliefs"><span class="header-section-number">6.5.3</span> The business reliefs</a></li>
  <li><a href="#check-yourself-capital-gains-tax" id="toc-check-yourself-capital-gains-tax" class="nav-link" data-scroll-target="#check-yourself-capital-gains-tax"><span class="header-section-number">6.5.4</span> Check yourself: capital gains tax</a></li>
  </ul></li>
  <li><a href="#corporation-tax" id="toc-corporation-tax" class="nav-link" data-scroll-target="#corporation-tax"><span class="header-section-number">6.6</span> Corporation tax</a>
  <ul class="collapse">
  <li><a href="#the-charge" id="toc-the-charge" class="nav-link" data-scroll-target="#the-charge"><span class="header-section-number">6.6.1</span> The charge</a></li>
  <li><a href="#chargeable-gains-in-a-company" id="toc-chargeable-gains-in-a-company" class="nav-link" data-scroll-target="#chargeable-gains-in-a-company"><span class="header-section-number">6.6.2</span> Chargeable gains in a company</a></li>
  <li><a href="#rates" id="toc-rates" class="nav-link" data-scroll-target="#rates"><span class="header-section-number">6.6.3</span> Rates</a></li>
  <li><a href="#relieving-trading-losses-1" id="toc-relieving-trading-losses-1" class="nav-link" data-scroll-target="#relieving-trading-losses-1"><span class="header-section-number">6.6.4</span> Relieving trading losses</a></li>
  <li><a href="#payment-and-collection" id="toc-payment-and-collection" class="nav-link" data-scroll-target="#payment-and-collection"><span class="header-section-number">6.6.5</span> Payment and collection</a></li>
  <li><a href="#distributions-and-close-companies" id="toc-distributions-and-close-companies" class="nav-link" data-scroll-target="#distributions-and-close-companies"><span class="header-section-number">6.6.6</span> Distributions and close companies</a></li>
  <li><a href="#anti-avoidance-in-outline" id="toc-anti-avoidance-in-outline" class="nav-link" data-scroll-target="#anti-avoidance-in-outline"><span class="header-section-number">6.6.7</span> Anti-avoidance in outline</a></li>
  </ul></li>
  <li><a href="#value-added-tax" id="toc-value-added-tax" class="nav-link" data-scroll-target="#value-added-tax"><span class="header-section-number">6.7</span> Value added tax</a>
  <ul class="collapse">
  <li><a href="#the-scope-of-the-charge" id="toc-the-scope-of-the-charge" class="nav-link" data-scroll-target="#the-scope-of-the-charge"><span class="header-section-number">6.7.1</span> The scope of the charge</a></li>
  <li><a href="#rates-and-categories" id="toc-rates-and-categories" class="nav-link" data-scroll-target="#rates-and-categories"><span class="header-section-number">6.7.2</span> Rates and categories</a></li>
  <li><a href="#registration" id="toc-registration" class="nav-link" data-scroll-target="#registration"><span class="header-section-number">6.7.3</span> Registration</a></li>
  <li><a href="#input-tax-tax-points-invoices-and-returns" id="toc-input-tax-tax-points-invoices-and-returns" class="nav-link" data-scroll-target="#input-tax-tax-points-invoices-and-returns"><span class="header-section-number">6.7.4</span> Input tax, tax points, invoices and returns</a></li>
  </ul></li>
  <li><a href="#inheritance-tax-business-property-relief" id="toc-inheritance-tax-business-property-relief" class="nav-link" data-scroll-target="#inheritance-tax-business-property-relief"><span class="header-section-number">6.8</span> Inheritance tax: business property relief</a>
  <ul class="collapse">
  <li><a href="#what-qualifies-and-at-what-rate" id="toc-what-qualifies-and-at-what-rate" class="nav-link" data-scroll-target="#what-qualifies-and-at-what-rate"><span class="header-section-number">6.8.1</span> What qualifies, and at what rate</a></li>
  <li><a href="#the-conditions" id="toc-the-conditions" class="nav-link" data-scroll-target="#the-conditions"><span class="header-section-number">6.8.2</span> The conditions</a></li>
  </ul></li>
  <li><a href="#putting-it-together-the-structuring-questions" id="toc-putting-it-together-the-structuring-questions" class="nav-link" data-scroll-target="#putting-it-together-the-structuring-questions"><span class="header-section-number">6.9</span> Putting it together: the structuring questions</a>
  <ul class="collapse">
  <li><a href="#salary-or-dividend" id="toc-salary-or-dividend" class="nav-link" data-scroll-target="#salary-or-dividend"><span class="header-section-number">6.9.1</span> Salary or dividend?</a></li>
  <li><a href="#incorporating-an-existing-business" id="toc-incorporating-an-existing-business" class="nav-link" data-scroll-target="#incorporating-an-existing-business"><span class="header-section-number">6.9.2</span> Incorporating an existing business</a></li>
  </ul></li>
  <li><a href="#the-solicitors-position" id="toc-the-solicitors-position" class="nav-link" data-scroll-target="#the-solicitors-position"><span class="header-section-number">6.10</span> The solicitor’s position</a></li>
  <li><a href="#chapter-review" id="toc-chapter-review" class="nav-link" data-scroll-target="#chapter-review"><span class="header-section-number">6.11</span> Chapter review</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../flk1/blp-00-overview.html">Business Law and Practice</a></li><li class="breadcrumb-item"><a href="../flk1/blp-05-taxation.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-blp-taxation" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><em>Assessment objective 5: taxation of a business and its stakeholders.</em></p>
</blockquote>
<section id="how-to-use-this-chapter" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="how-to-use-this-chapter"><span class="header-section-number">6.1</span> How to use this chapter</h2>
<div class="callout callout-style-default callout-caution callout-titled" title="Learn the mechanics; the figures will be given to you">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Learn the mechanics; the figures will be given to you
</div>
</div>
<div class="callout-body-container callout-body">
<p>The SQE1 assessment specification states that where candidates are required to apply the monetary value of any exemptions and reliefs, or particular rates or thresholds, <strong>these will be provided</strong>. What you must supply is everything else: which tax applies, to which person, on which receipt, in which order the computation runs, and which relief is available on the facts.</p>
<p>Every figure in this chapter is given for <strong>2026/27</strong> (financial year 2026 for corporation tax) and is marked so you can check it. Learn the structure of each computation; treat the numbers as illustrations.</p>
</div>
</div>
</section>
<section id="the-map" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-map"><span class="header-section-number">6.2</span> The map</h2>
<p>Five taxes, and the first job in any question is to identify which are in play and on whom.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tax</th>
<th>Charged on</th>
<th>Charged to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Income tax</strong></td>
<td>Income profits</td>
<td>Individuals: sole traders, partners, LLP members, employees, shareholders on dividends, lenders on interest</td>
</tr>
<tr class="even">
<td><strong>National Insurance</strong></td>
<td>Earnings and trading profits</td>
<td>Employees, employers, the self-employed</td>
</tr>
<tr class="odd">
<td><strong>Capital gains tax</strong></td>
<td>Capital gains</td>
<td>Individuals, partners, trustees, personal representatives</td>
</tr>
<tr class="even">
<td><strong>Corporation tax</strong></td>
<td>Income profits <strong>and</strong> chargeable gains</td>
<td>Companies (and other bodies corporate)</td>
</tr>
<tr class="odd">
<td><strong>VAT</strong></td>
<td>Taxable supplies</td>
<td>The business, as a collector; the final consumer bears it</td>
</tr>
<tr class="even">
<td><strong>Inheritance tax</strong></td>
<td>Transfers of value</td>
<td>Individuals and their estates — examined here <strong>only</strong> for business property relief</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Transparency is the organising idea.</strong> A sole trader, a partnership and an LLP are <strong>transparent</strong>: the business pays no tax on its profits; the individuals are charged to income tax on their shares as the profits arise, <strong>whether or not drawn</strong>. A company is <strong>opaque</strong>: it pays corporation tax on its own profits, and the shareholder is taxed separately, and only when money comes out.</p>
<p>The two errors this generates are (i) charging corporation tax on an LLP’s profits, and (ii) taxing a partner only on drawings. Both appear regularly.</p>
</div>
</div>
</section>
<section id="income-tax" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="income-tax"><span class="header-section-number">6.3</span> Income tax</h2>
<section id="who-and-what" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="who-and-what"><span class="header-section-number">6.3.1</span> Who and what</h3>
<p>Income tax is charged for a <strong>tax year</strong> running from <strong>6 April to 5 April</strong> on the income of individuals. The categories that matter here:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Charging regime</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Trading profits</strong> of a sole trader or partner</td>
<td>ITTOIA 2005 Part 2</td>
</tr>
<tr class="even">
<td><strong>Employment income</strong> (salary, bonus, benefits in kind)</td>
<td>ITEPA 2003</td>
</tr>
<tr class="odd">
<td><strong>Property income</strong></td>
<td>ITTOIA 2005 Part 3</td>
</tr>
<tr class="even">
<td><strong>Savings income</strong> — interest, including on a director’s loan or a debenture</td>
<td>ITTOIA 2005 Part 4</td>
</tr>
<tr class="odd">
<td><strong>Dividend income</strong></td>
<td>ITTOIA 2005 Part 4</td>
</tr>
</tbody>
</table>
<p>A <strong>partner</strong> is charged on their share of the partnership’s trading profit as computed for the firm as a whole; the firm files a partnership return, but the tax is the partner’s. The same is true of an <strong>LLP member</strong>. A <strong>debenture holder or lender</strong> is charged on interest as savings income. A <strong>shareholder</strong> is charged on dividends as dividend income.</p>
</section>
<section id="the-computation" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="the-computation"><span class="header-section-number">6.3.2</span> The computation</h3>
<p>Income tax is calculated in a fixed sequence (ITA 2007 s.23). Follow it; questions are built to punish short cuts.</p>
<p><strong>Step 1 — Total income.</strong> Add the income from every source, before any deductions personal to the taxpayer.</p>
<p><strong>Step 2 — Deduct reliefs → net income.</strong> Reliefs deductible from total income include trading loss relief under s.64 ITA 2007 and interest on qualifying loans (for example, a loan to buy an interest in a partnership or shares in a close company).</p>
<p><strong>Step 3 — Deduct the personal allowance → taxable income.</strong> The personal allowance is <strong>£12,570</strong>, and is reduced by <strong>£1 for every £2</strong> of adjusted net income above <strong>£100,000</strong>, so it is extinguished at <strong>£125,140</strong>. Deduct it from the income taxed at the highest rates first — in practice, allocate it against non-savings income.</p>
<p><strong>Step 4 — Split the taxable income into three slices and tax them in this order:</strong></p>
<ol type="1">
<li><strong>Non-savings income</strong> (trading and employment income, property income)</li>
<li><strong>Savings income</strong> (interest)</li>
<li><strong>Dividend income</strong></li>
</ol>
<p>Dividends always sit at the <strong>top</strong>, which is why they are taxed at the taxpayer’s highest marginal rate.</p>
<p><strong>Step 5 — Apply the rates.</strong></p>
<div class="callout callout-style-default callout-caution callout-titled" title="Rates and allowances — 2026/27">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Rates and allowances — 2026/27
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Band of taxable income</th>
<th>Non-savings</th>
<th>Savings</th>
<th>Dividends</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Basic rate</td>
<td>First <strong>£37,700</strong></td>
<td>20%</td>
<td>20%</td>
<td><strong>10.75%</strong></td>
</tr>
<tr class="even">
<td>Higher rate</td>
<td>To <strong>£125,140</strong></td>
<td>40%</td>
<td>40%</td>
<td><strong>35.75%</strong></td>
</tr>
<tr class="odd">
<td>Additional rate</td>
<td>Above £125,140</td>
<td>45%</td>
<td>45%</td>
<td><strong>39.35%</strong></td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Personal allowance</strong>: £12,570, tapered above £100,000</li>
<li><strong>Dividend allowance</strong>: <strong>£500</strong>, taxed at 0% but still using up band</li>
<li><strong>Personal savings allowance</strong>: £1,000 (basic rate taxpayer), £500 (higher rate), <strong>nil</strong> (additional rate)</li>
<li><strong>Starting rate for savings</strong>: £5,000 at 0%, available only to the extent non-savings income does not exceed the personal allowance plus £5,000</li>
</ul>
<p>The dividend rates rose by two percentage points at the basic and higher rates with effect from <strong>6 April 2026</strong>. Scotland sets its own rates and bands for non-savings, non-dividend income.</p>
</div>
</div>
<p><strong>Step 6 — Deduct tax reductions</strong> (marriage allowance, EIS and VCT relief), then <strong>Step 7 — deduct tax already paid</strong> (PAYE, tax deducted at source) to reach the amount payable.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Worked example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Worked example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Nadia is the sole shareholder and director of a trading company. In 2026/27 she takes a salary of £20,000 and a dividend of £45,000. She has no other income.</p>
<ul>
<li><strong>Total income</strong> £65,000; no reliefs; <strong>net income</strong> £65,000.</li>
<li><strong>Personal allowance</strong> £12,570, set against the salary. Taxable non-savings income: £20,000 − £12,570 = <strong>£7,430</strong>. Taxable dividend income: <strong>£45,000</strong>.</li>
<li><strong>Non-savings</strong>: £7,430 at 20% = <strong>£1,486</strong>.</li>
<li><strong>Dividends</strong>: the £500 dividend allowance is taxed at 0% but <strong>uses up band</strong>. The basic rate band is £37,700, of which £7,430 is already used, leaving <strong>£30,270</strong>.
<ul>
<li>£500 at 0% = <strong>£0</strong> (and it consumes £500 of the remaining band, leaving £29,770)</li>
<li>£29,770 at 10.75% = <strong>£3,200.28</strong></li>
<li>The balance of the dividend, £45,000 − £500 − £29,770 = <strong>£14,730</strong>, falls into the higher rate band at 35.75% = <strong>£5,265.98</strong></li>
</ul></li>
<li><strong>Total liability</strong>: £1,486 + £3,200.28 + £5,265.98 = <strong>£9,952.26</strong>, less PAYE already deducted on the salary.</li>
</ul>
<p>The two mechanical points being tested: dividends are taxed <strong>last</strong>, and the dividend allowance is a <strong>nil-rate band</strong>, not an exemption — it uses up the basic rate band as it goes.</p>
</div>
</div>
</section>
<section id="computing-trading-profits" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="computing-trading-profits"><span class="header-section-number">6.3.3</span> Computing trading profits</h3>
<p>The accounting profit is not the taxable profit. Adjust it:</p>
<p><strong>Add back</strong> — amounts deducted in the accounts that are not deductible for tax:</p>
<ul>
<li><strong>Capital expenditure</strong> and <strong>depreciation or amortisation</strong> (capital allowances take their place)</li>
<li>Expenditure not incurred <strong>wholly and exclusively</strong> for the purposes of the trade — the private proportion of a car, a home, or a phone</li>
<li><strong>Client entertaining</strong> (staff entertaining within limits is allowable)</li>
<li><strong>Fines and penalties</strong> for breaking the law</li>
<li><strong>General provisions</strong> (specific bad debt provisions are allowable)</li>
<li><strong>Appropriations of profit</strong>: the proprietor’s own drawings or “salary”, and interest on their capital</li>
</ul>
<p><strong>Deduct</strong> — amounts not in the accounts, or income taxed elsewhere:</p>
<ul>
<li><strong>Capital allowances</strong></li>
<li>Income assessable under another head (rental income, bank interest) — taken out here and taxed in its own category</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled" title="Two recent structural changes">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Two recent structural changes
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>The cash basis is now the default</strong> for unincorporated businesses (from 2024/25). A sole trader or partnership computes profits on money in and money out unless it elects for the accruals basis; the former turnover restrictions have gone.</p>
<p><strong>Basis periods were reformed</strong> from 2024/25. Unincorporated businesses are taxed on the profits <strong>arising in the tax year</strong> itself, rather than on the profits of the accounting period ending in it. The old overlap profits were relieved in the 2023/24 transition year.</p>
</div>
</div>
</section>
<section id="capital-allowances" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="capital-allowances"><span class="header-section-number">6.3.4</span> Capital allowances</h3>
<p>Capital expenditure is not deductible, but <strong>capital allowances</strong> give relief for plant and machinery:</p>
<ul>
<li><strong>Annual investment allowance</strong>: <strong>100%</strong> of qualifying expenditure in the period, up to <strong>£1,000,000</strong> a year. Available to sole traders, partnerships and companies. Not available on cars.</li>
<li><strong>Writing down allowance</strong>: on the balance of the <strong>main pool</strong>, <strong>18%</strong> a year on a reducing balance; on the <strong>special rate pool</strong> (long-life assets, integral features, cars with higher emissions), <strong>6%</strong>.</li>
<li><strong>Full expensing</strong> — a <strong>100%</strong> first-year allowance on new and unused main-rate plant and machinery, with a <strong>50%</strong> first-year allowance on new special rate expenditure. This is available to <strong>companies only</strong>, and is one of the real tax advantages of incorporation.</li>
</ul>
</section>
<section id="relieving-trading-losses" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="relieving-trading-losses"><span class="header-section-number">6.3.5</span> Relieving trading losses</h3>
<p>For a <strong>sole trader or partner</strong>, a trading loss can be used in several ways, and the discrimination between them is examinable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Relief</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>s.64 ITA 2007</strong></td>
<td>Set the loss against <strong>net income</strong> of the <strong>tax year of the loss</strong>, the <strong>preceding</strong> tax year, or both</td>
</tr>
<tr class="even">
<td><strong>s.72 ITA 2007</strong></td>
<td><strong>Early trade losses</strong>: a loss in any of the <strong>first four</strong> tax years may be carried back <strong>three</strong> years, against income of the earliest year first</td>
</tr>
<tr class="odd">
<td><strong>s.83 ITA 2007</strong></td>
<td>Carry <strong>forward</strong> against future profits of the <strong>same trade</strong>, indefinitely</td>
</tr>
<tr class="even">
<td><strong>s.89 ITA 2007</strong></td>
<td><strong>Terminal loss relief</strong>: a loss of the final 12 months of trading carried back <strong>three</strong> years, latest first</td>
</tr>
<tr class="odd">
<td><strong>s.261B TCGA 1992</strong></td>
<td>Having made a s.64 claim, extend it against <strong>chargeable gains</strong> of the same year</td>
</tr>
<tr class="even">
<td><strong>s.86 ITA 2007</strong></td>
<td>On <strong>incorporation</strong>, carry the loss forward against income received <strong>from the company</strong></td>
</tr>
</tbody>
</table>
<p>Two constraints:</p>
<ul>
<li>A <strong>s.64 claim is all or nothing</strong> for the year claimed: you cannot restrict it to preserve the personal allowance, so a claim can waste the allowance.</li>
<li>A <strong>cap</strong> applies (s.24A ITA 2007) to the total of certain reliefs, including s.64, set against general income: the greater of <strong>£50,000</strong> or <strong>25% of adjusted total income</strong>. It does not apply to losses set against profits of the same trade.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Match the relief to what the question tells you about the client. A <strong>new</strong> business with a loss and a previous employment history is a s.72 question — carry back three years to recover PAYE. A business that has <strong>just ceased</strong> is a s.89 question. A client who wants cash <strong>now</strong> points to s.64 or s.72; a client with no other income points to s.83. If the question mentions a large capital gain in the same year, s.261B is in play.</p>
</div>
</div>
</section>
<section id="collection" class="level3" data-number="6.3.6">
<h3 data-number="6.3.6" class="anchored" data-anchor-id="collection"><span class="header-section-number">6.3.6</span> Collection</h3>
<p>Income tax on employment income is collected through <strong>PAYE</strong>. Everything else goes through <strong>self assessment</strong>:</p>
<ul>
<li><strong>Filing</strong>: paper return by <strong>31 October</strong> following the end of the tax year; online by <strong>31 January</strong>.</li>
<li><strong>Balancing payment</strong>: <strong>31 January</strong> following the end of the tax year.</li>
<li><strong>Payments on account</strong>: two instalments, on <strong>31 January</strong> during the tax year and <strong>31 July</strong> after it, each of <strong>50%</strong> of the previous year’s liability. Not required where the previous year’s liability was under £1,000 or where 80% or more was collected at source.</li>
</ul>
</section>
<section id="check-yourself-income-tax" class="level3" data-number="6.3.7">
<h3 data-number="6.3.7" class="anchored" data-anchor-id="check-yourself-income-tax"><span class="header-section-number">6.3.7</span> Check yourself: income tax</h3>
<p><strong>Q1.</strong> A partner in a trading partnership is allocated a 40% share of the firm’s profit of £200,000 for the tax year. She draws only £50,000, leaving the balance in the firm.</p>
<p>On what amount is she charged to income tax in respect of the partnership?</p>
<p>A. £50,000, being the amount actually drawn.</p>
<p>B. £80,000, being her allocated share, whether or not drawn.</p>
<p>C. £200,000, because partners are jointly liable for the firm’s tax.</p>
<p>D. Nothing; the partnership pays income tax on the whole £200,000.</p>
<p>E. £80,000, but only when the balance is eventually withdrawn.</p>
<p><strong>Q2.</strong> A taxpayer has employment income of £45,000, bank interest of £2,000 and dividends of £8,000.</p>
<p>In what order is her income taxed, and where does the dividend income sit?</p>
<p>A. Dividends first, then savings income, then non-savings income.</p>
<p>B. Non-savings income first, then savings income, then dividends, which are treated as the top slice of income.</p>
<p>C. All income is aggregated and taxed at a single rate.</p>
<p>D. Savings income first, then dividends, then non-savings income.</p>
<p>E. Dividends are taxed separately at a flat rate regardless of the taxpayer’s other income.</p>
<p><strong>Q3.</strong> A client started trading as a sole trader eighteen months ago after twelve years in well-paid employment. Her first two tax years of trading have both produced substantial losses, and she has no other current income. She needs cash urgently.</p>
<p>Which loss relief is most likely to help?</p>
<p>A. Section 83 ITA 2007, carrying the losses forward against future trading profits.</p>
<p>B. Section 89 ITA 2007, terminal loss relief.</p>
<p>C. Section 72 ITA 2007, early trade losses relief, carrying the loss back three years against the income of the earliest year first, generating a repayment of tax paid under PAYE.</p>
<p>D. Section 261B TCGA 1992, setting the loss against chargeable gains.</p>
<p>E. No relief is available, because she has no income in the current year.</p>
<p><strong>Q4.</strong> Which of the following would be <strong>added back</strong> in computing a sole trader’s taxable trading profit from the accounting profit?</p>
<p>A. Rent paid on the trading premises.</p>
<p>B. A specific provision for a bad debt owed by a named customer.</p>
<p>C. The proprietor’s own drawings recorded in the accounts as “salary”.</p>
<p>D. Employer’s National Insurance contributions on staff wages.</p>
<p>E. Interest paid on a business loan.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — B.</strong> A partnership is <strong>transparent</strong>. It pays no income tax itself; each partner is charged on their <strong>allocated share</strong> of the profit as computed for the firm, whether or not it is drawn. 40% × £200,000 = £80,000.</p>
<ul>
<li><strong>A</strong> and <strong>E</strong> tax drawings, which is the company model, not the partnership model.</li>
<li><strong>C</strong> confuses joint liability for the firm’s <strong>debts</strong> with liability for tax, which is several.</li>
<li><strong>D</strong> treats the partnership as an opaque entity.</li>
</ul>
<p><strong>Q2 — B.</strong> The statutory order in ITA 2007 is non-savings income, then savings income, then dividend income. Dividends are the <strong>top slice</strong>, which is why an additional slice of dividend income is taxed at the taxpayer’s highest marginal rate.</p>
<ul>
<li><strong>A</strong> and <strong>D</strong> reverse the order.</li>
<li><strong>C</strong> ignores the three-slice structure and the different dividend rates.</li>
<li><strong>E</strong> describes a flat charge that does not exist; dividend rates are banded.</li>
</ul>
<p><strong>Q3 — C.</strong> Section 72 ITA 2007 applies to a loss made in any of the <strong>first four</strong> tax years of a new trade, and allows it to be carried back <strong>three</strong> years against the taxpayer’s general income, taking the <strong>earliest</strong> year first. With twelve years of employment behind her, that generates a repayment of PAYE — which is exactly the cash she needs.</p>
<ul>
<li><strong>A</strong> gives relief only in the future, and she has no profits yet.</li>
<li><strong>B</strong> applies only on <strong>cessation</strong>.</li>
<li><strong>D</strong> requires chargeable gains, which the facts do not give her, and requires a s.64 claim first.</li>
<li><strong>E</strong> ignores the carry-back reliefs entirely.</li>
</ul>
<p><strong>Q4 — C.</strong> Drawings are an <strong>appropriation of profit</strong>, not an expense of the trade, however they are labelled in the accounts. A sole trader cannot be employed by their own business, so there is no salary to deduct. All the other items are incurred wholly and exclusively for the purposes of the trade and are deductible; note in particular that a <strong>specific</strong> bad debt provision is allowable, whereas a general provision is not.</p>
</div>
</div>
</div>
</section>
</section>
<section id="national-insurance-contributions" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="national-insurance-contributions"><span class="header-section-number">6.4</span> National Insurance contributions</h2>
<p>NICs are a separate charge with their own thresholds, and they are the main reason the salary/dividend question has an answer.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Rates — 2026/27">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Rates — 2026/27
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Class</th>
<th>Payer</th>
<th>Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Class 1 primary</strong></td>
<td>Employee</td>
<td><strong>8%</strong> between the primary threshold and the upper earnings limit; <strong>2%</strong> above</td>
</tr>
<tr class="even">
<td><strong>Class 1 secondary</strong></td>
<td><strong>Employer</strong></td>
<td><strong>15%</strong> on earnings above the secondary threshold</td>
</tr>
<tr class="odd">
<td><strong>Class 1A / 1B</strong></td>
<td>Employer</td>
<td><strong>15%</strong> on most benefits in kind and PAYE settlement agreements</td>
</tr>
<tr class="even">
<td><strong>Class 2</strong></td>
<td>Self-employed</td>
<td>Effectively <strong>abolished</strong>: no liability where profits are at or above the small profits threshold, and a National Insurance credit is given instead. Voluntary contributions remain available at a small weekly rate for those below it</td>
</tr>
<tr class="odd">
<td><strong>Class 4</strong></td>
<td>Self-employed</td>
<td><strong>6%</strong> on profits between the lower and upper profits limits; <strong>2%</strong> above</td>
</tr>
<tr class="even">
<td><strong>Class 3</strong></td>
<td>Anyone</td>
<td>Voluntary, to fill gaps in a contribution record</td>
</tr>
</tbody>
</table>
<p>The <strong>employment allowance</strong> (£10,500) reduces an eligible employer’s secondary Class 1 bill. It cannot be claimed by a company whose only employee is a <strong>sole director</strong>.</p>
</div>
</div>
<p>Three consequences worth holding on to:</p>
<ul>
<li><strong>Dividends bear no National Insurance at all</strong> — not employee’s, not employer’s. That is the whole arithmetic of the owner-manager remuneration question.</li>
<li><strong>Employer’s NIC is a real cost of paying salary</strong>, and it is itself deductible in computing the company’s taxable profit.</li>
<li>The <strong>self-employed pay less</strong> than the combined employee-plus-employer burden on the same money, which is why the employment status question matters to HMRC.</li>
</ul>
</section>
<section id="capital-gains-tax" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="capital-gains-tax"><span class="header-section-number">6.5</span> Capital gains tax</h2>
<section id="the-four-questions" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="the-four-questions"><span class="header-section-number">6.5.1</span> The four questions</h3>
<p>A CGT charge requires a <strong>chargeable person</strong> making a <strong>chargeable disposal</strong> of a <strong>chargeable asset</strong> producing a <strong>gain</strong>.</p>
<p><strong>Chargeable person</strong>: an individual, a partner (each partner is charged on their share of a partnership asset), a trustee, a personal representative. <strong>Not</strong> a company — a company’s gains fall within corporation tax.</p>
<p><strong>Chargeable disposal</strong>: a sale, a <strong>gift</strong>, an exchange, or the loss or destruction of an asset. Note two things: a <strong>gift is a disposal</strong> and gives rise to a gain computed on market value; and <strong>death is not a disposal</strong> — the personal representatives take the assets at probate value, so the death uplift wipes out the accrued gain.</p>
<p><strong>Chargeable asset</strong>: everything except the exempt list — the taxpayer’s main residence (within private residence relief), cars, gilts and qualifying corporate bonds, ISAs, assets held in a pension, chattels sold for £6,000 or less, and wasting chattels.</p>
</section>
<section id="the-computation-1" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="the-computation-1"><span class="header-section-number">6.5.2</span> The computation</h3>
<pre><code>    Consideration (or market value, if a gift or a disposal to a connected person)
  − Incidental costs of disposal (legal fees, agent's commission, advertising)
  − Acquisition cost (or probate/market value)
  − Incidental costs of acquisition
  − Enhancement expenditure reflected in the state of the asset at disposal
  = Chargeable gain</code></pre>
<p>Then, across all disposals in the tax year:</p>
<pre><code>    Total chargeable gains
  − Current year allowable losses (compulsory, in full)
  − Losses brought forward (only to the extent they reduce gains to the annual exempt amount)
  − Annual exempt amount
  = Taxable gains</code></pre>
<div class="callout callout-style-default callout-caution callout-titled" title="Rates and allowances — 2026/27">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Rates and allowances — 2026/27
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Annual exempt amount</strong>: <strong>£3,000</strong></li>
<li><strong>Main rates</strong>: <strong>18%</strong> to the extent gains fall within the taxpayer’s unused <strong>basic rate band</strong>; <strong>24%</strong> above it. The taxpayer’s taxable income is stacked first, and gains sit on top.</li>
<li><strong>Business asset disposal relief</strong>: <strong>18%</strong> on qualifying gains, subject to a <strong>£1 million lifetime limit</strong>. (The rate was 10% until 5 April 2025, 14% for 2025/26, and 18% from 6 April 2026.)</li>
<li><strong>Investors’ relief</strong>: <strong>18%</strong>, £1 million lifetime limit.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>The stacking order decides the rate. <strong>Taxable income first, gains on top.</strong> A taxpayer with £30,000 of taxable income and a £40,000 gain has £7,700 of basic rate band left (£37,700 − £30,000), so £7,700 of the gain is taxed at 18% and the rest at 24%. Candidates who tax the whole gain at one rate lose the mark.</p>
<p>The second trap is the <strong>order of deductions</strong>: current year losses are set off <strong>in full and compulsorily</strong>, even if that wastes the annual exempt amount; brought-forward losses are used only down to the annual exempt amount, preserving it.</p>
</div>
</div>
</section>
<section id="the-business-reliefs" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="the-business-reliefs"><span class="header-section-number">6.5.3</span> The business reliefs</h3>
<p><strong>Business asset disposal relief.</strong> A reduced rate on qualifying gains up to a £1 million lifetime limit. The qualifying period is <strong>two years</strong> ending with the disposal. It applies to:</p>
<ul>
<li>the disposal of the whole or part of a <strong>business</strong> carried on by the individual, alone or in partnership (a disposal of individual assets used in a continuing business does <strong>not</strong> qualify);</li>
<li>the disposal of <strong>assets of a business that has ceased</strong>, provided the disposal is within <strong>three years</strong> of cessation;</li>
<li>the disposal of <strong>shares in a personal trading company</strong>, where throughout the two years the individual was an <strong>officer or employee</strong> of the company and held at least <strong>5%</strong> of the ordinary share capital and voting rights, plus (broadly) an entitlement to <strong>5%</strong> of the profits available for distribution and of assets on a winding up, or to 5% of the proceeds on a sale of the whole of the ordinary share capital;</li>
<li><strong>associated disposals</strong> of assets used in the business, alongside a qualifying disposal of the business or shares, restricted where rent has been charged.</li>
</ul>
<p><strong>Rollover relief on the replacement of business assets</strong> (s.152 TCGA 1992). Where the proceeds of a qualifying business asset are reinvested in another qualifying asset within the period beginning <strong>one year before</strong> and ending <strong>three years after</strong> the disposal, the gain is <strong>rolled over</strong> — deducted from the base cost of the new asset — so tax is deferred rather than saved. Qualifying assets include land and buildings occupied and used for the trade, and fixed plant and machinery (and goodwill, for an unincorporated business). Only the amount <strong>reinvested</strong> attracts relief: proceeds retained are charged.</p>
<p><strong>Hold-over relief on gifts of business assets</strong> (s.165 TCGA 1992). On a <strong>gift</strong> (or a sale at undervalue) of qualifying business assets, the donor and donee may <strong>jointly elect</strong> for the gain to be held over: the donor pays nothing, and the donee’s base cost is reduced by the held-over gain, so the tax comes home when the donee sells. Qualifying assets include assets used in the donor’s trade and shares in an unquoted trading company.</p>
<p><strong>Incorporation relief</strong> (s.162 TCGA 1992). Where a person transfers a business <strong>as a going concern</strong>, with <strong>all its assets</strong> (cash may be excluded), to a company <strong>wholly or partly in exchange for shares</strong>, the gain on the transferred assets is <strong>rolled into the base cost of the shares</strong>. The relief is <strong>automatic</strong> unless disapplied by election under s.162A, and is <strong>restricted proportionately</strong> where part of the consideration is not shares.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Distinguish the three deferral reliefs by the transaction:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Facts</th>
<th>Relief</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sold a business asset and bought a replacement</td>
<td><strong>Rollover</strong> (s.152)</td>
</tr>
<tr class="even">
<td>Gave away a business asset or shares</td>
<td><strong>Hold-over</strong> (s.165), by joint election</td>
</tr>
<tr class="odd">
<td>Transferred the whole business to a company for shares</td>
<td><strong>Incorporation relief</strong> (s.162), automatic</td>
</tr>
</tbody>
</table>
<p>And distinguish all three from <strong>business asset disposal relief</strong>, which does not defer anything — it reduces the rate on a gain that is charged now.</p>
</div>
</div>
<p><strong>Other points frequently tested:</strong></p>
<ul>
<li><strong>Spouses and civil partners</strong>: transfers between them living together are <strong>no gain, no loss</strong> — the transferee takes the transferor’s base cost. This is the standard planning device for using two annual exempt amounts and two basic rate bands.</li>
<li><strong>Connected persons</strong> (relatives in the wider sense, partners, controlled companies): the disposal is deemed to be at <strong>market value</strong>, and a loss on a disposal to a connected person can only be set against gains on later disposals to the <strong>same</strong> person.</li>
<li><strong>Payment</strong>: <strong>31 January</strong> following the end of the tax year, with the return. A disposal of UK <strong>residential property</strong> giving rise to a liability must be reported and the tax paid within <strong>60 days</strong>.</li>
</ul>
</section>
<section id="check-yourself-capital-gains-tax" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="check-yourself-capital-gains-tax"><span class="header-section-number">6.5.4</span> Check yourself: capital gains tax</h3>
<p><strong>Q1.</strong> A taxpayer has taxable income (after the personal allowance) of £30,000. In the same tax year she realises a chargeable gain of £43,000 on the sale of a buy-to-let flat. She has no losses and the annual exempt amount is £3,000. The basic rate band is £37,700, of which her income has used £30,000.</p>
<p>At what rate or rates is the gain taxed?</p>
<p>A. The whole gain at 24%.</p>
<p>B. The whole gain at 18%.</p>
<p>C. £7,700 at 18% and the balance at 24%.</p>
<p>D. The annual exempt amount covers £3,000 of the gain; of the remainder, £7,700 is taxed at 18% and the balance at 24%.</p>
<p>E. The annual exempt amount covers £3,000 of the gain and the balance is taxed at 24%.</p>
<p><strong>Q2.</strong> A client has run a printing business as a sole trader for eleven years. She transfers the entire business, including all its assets other than cash, to a newly formed company in exchange for the whole of the issued share capital. The assets stand at a substantial gain.</p>
<p>Which relief applies?</p>
<p>A. Business asset disposal relief, charging the gain at the reduced rate.</p>
<p>B. Rollover relief on the replacement of business assets.</p>
<p>C. Incorporation relief under s.162 TCGA 1992: the gain is rolled into the base cost of the shares, and the relief applies automatically unless disapplied by election.</p>
<p>D. Hold-over relief under s.165, provided the client and the company jointly elect.</p>
<p>E. No relief; the transfer is a disposal at market value to a connected person.</p>
<p><strong>Q3.</strong> A father gives his adult son shares in the family’s unquoted trading company. The shares stand at a gain of £250,000. The father wishes to pay no capital gains tax now.</p>
<p>Which of the following is correct?</p>
<p>A. No CGT arises, because a gift is not a disposal.</p>
<p>B. No CGT arises, because transfers between family members are treated as no gain, no loss.</p>
<p>C. CGT arises on a deemed disposal at market value, but father and son may <strong>jointly elect</strong> to hold the gain over under s.165, so that the son’s base cost is reduced by the held-over gain.</p>
<p>D. CGT arises and cannot be deferred; only business asset disposal relief is available.</p>
<p>E. CGT arises but is automatically deferred until the son disposes of the shares.</p>
<p><strong>Q4.</strong> A client sells a warehouse used in her trade for £900,000, realising a gain of £300,000. Fourteen months later she buys a replacement warehouse for £700,000, also for use in the trade, and retains the remaining £200,000.</p>
<p>Which of the following is correct?</p>
<p>A. The whole gain may be rolled over, because a replacement asset was acquired within three years.</p>
<p>B. No relief is available, because the replacement cost less than the proceeds of the original.</p>
<p>C. Rollover relief is available on the amount reinvested; the £200,000 of proceeds retained is immediately chargeable, so £200,000 of the gain crystallises and £100,000 is rolled over.</p>
<p>D. Relief is available only if the replacement was acquired within twelve months of the disposal.</p>
<p>E. Hold-over relief under s.165 applies, because both assets were used in the trade.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — D.</strong> Deduct the annual exempt amount from the gain first: £43,000 − £3,000 = £40,000 taxable. Then stack: taxable income of £30,000 uses part of the £37,700 basic rate band, leaving <strong>£7,700</strong>. £7,700 of the gain is taxed at <strong>18%</strong>; the remaining £32,300 at <strong>24%</strong>.</p>
<ul>
<li><strong>A</strong> and <strong>B</strong> apply a single rate.</li>
<li><strong>C</strong> omits the annual exempt amount.</li>
<li><strong>E</strong> wastes the unused basic rate band.</li>
</ul>
<p><strong>Q2 — C.</strong> Section 162 TCGA 1992: the transfer of a business as a <strong>going concern</strong>, with <strong>all its assets</strong> (cash may be excluded), to a company <strong>wholly or partly in exchange for shares</strong>, rolls the gain into the base cost of the shares. The relief applies <strong>automatically</strong> unless the taxpayer elects under s.162A to disapply it.</p>
<ul>
<li><strong>A</strong> would charge the gain now at the BADR rate; incorporation relief defers it entirely, and the question is which relief <strong>applies</strong>, not which could be claimed.</li>
<li><strong>B</strong> requires the acquisition of a replacement asset, not the transfer of a business.</li>
<li><strong>D</strong> applies to gifts and requires a joint election; this is a transfer for consideration in shares.</li>
<li><strong>E</strong> ignores the relief.</li>
</ul>
<p><strong>Q3 — C.</strong> A gift is a chargeable disposal, deemed to be at market value because father and son are connected. Section 165 permits a <strong>joint election</strong> to hold over the gain on a gift of qualifying business assets, including shares in an unquoted trading company. The son takes the shares with a base cost reduced by the held-over gain.</p>
<ul>
<li><strong>A</strong> is wrong: a gift is a disposal.</li>
<li><strong>B</strong> applies the spouse rule to a parent and child.</li>
<li><strong>D</strong> overlooks s.165.</li>
<li><strong>E</strong> is the near-miss: hold-over is <strong>not automatic</strong> — it requires a joint claim by both parties.</li>
</ul>
<p><strong>Q4 — C.</strong> Rollover relief under s.152 requires reinvestment in the window from <strong>one year before</strong> to <strong>three years after</strong> the disposal, which fourteen months satisfies. But relief extends only to the amount <strong>reinvested</strong>: where proceeds are retained, the gain crystallises pound for pound with the retained proceeds. £200,000 retained means £200,000 of the £300,000 gain is chargeable now and £100,000 is rolled over into the base cost of the new warehouse.</p>
<ul>
<li><strong>A</strong> ignores the retained proceeds.</li>
<li><strong>B</strong> treats partial reinvestment as fatal.</li>
<li><strong>D</strong> misstates the window.</li>
<li><strong>E</strong> applies the wrong relief; s.165 is for gifts.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="corporation-tax" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="corporation-tax"><span class="header-section-number">6.6</span> Corporation tax</h2>
<section id="the-charge" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="the-charge"><span class="header-section-number">6.6.1</span> The charge</h3>
<p>Corporation tax is charged on the <strong>taxable total profits</strong> of a company for an <strong>accounting period</strong>, which cannot exceed 12 months. Unlike an individual, a company pays a single tax on <strong>both</strong> its income profits and its capital gains.</p>
<pre><code>    Trading income (adjusted profits, after capital allowances)
  + Property income
  + Non-trading loan relationship profits (interest receivable)
  + Chargeable gains
  = Total profits
  − Reliefs and deductions (including loss relief and qualifying charitable donations)
  = Taxable total profits (TTP)</code></pre>
<p>Adjustments to the accounting profit follow the same logic as for a sole trader — add back depreciation, client entertaining, fines and capital expenditure; deduct capital allowances. <strong>Two differences matter</strong>: a company <strong>can</strong> deduct directors’ and employees’ salaries and the employer’s NICs on them (there is no appropriation problem, because the company is a separate person), and a company <strong>cannot</strong> deduct the dividends it pays.</p>
</section>
<section id="chargeable-gains-in-a-company" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="chargeable-gains-in-a-company"><span class="header-section-number">6.6.2</span> Chargeable gains in a company</h3>
<p>Computed broadly as for CGT, but with three differences:</p>
<ul>
<li><strong>No annual exempt amount.</strong></li>
<li><strong>Indexation allowance</strong> is available for the period of ownership up to <strong>December 2017</strong>, when it was frozen. It can reduce a gain to nil but cannot create or increase a loss.</li>
<li>The <strong>substantial shareholding exemption</strong> exempts gains on the disposal of shares where a trading company has held at least 10% of another trading company for a continuous 12-month period within the preceding six years.</li>
</ul>
<p>The rate is the corporation tax rate — there is no separate capital gains rate for companies.</p>
</section>
<section id="rates" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="rates"><span class="header-section-number">6.6.3</span> Rates</h3>
<div class="callout callout-style-default callout-caution callout-titled" title="Rates — financial year 2026">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Rates — financial year 2026
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Augmented profits</th>
<th>Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Up to <strong>£50,000</strong></td>
<td><strong>19%</strong> (small profits rate)</td>
</tr>
<tr class="even">
<td>£50,000 to £250,000</td>
<td>25% with <strong>marginal relief</strong>, giving an effective rate rising from 19% to 25% — and a <strong>marginal rate of 26.5%</strong> on each extra pound in the band</td>
</tr>
<tr class="odd">
<td><strong>£250,000</strong> and above</td>
<td><strong>25%</strong> (main rate)</td>
</tr>
</tbody>
</table>
<p>The marginal relief fraction is <strong>3/200</strong>. Both limits are divided by <strong>one plus the number of associated companies</strong>, and are reduced proportionately for an accounting period of less than 12 months.</p>
</div>
</div>
<p>Marginal relief is computed as:</p>
<pre><code>    Standard fraction × (Upper limit − Augmented profits) × (TTP ÷ Augmented profits)</code></pre>
<p>and is deducted from the tax charged at the main rate.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Worked example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Worked example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A company with no associated companies has taxable total profits of £100,000 for the year ended 31 March 2027, and no franked investment income, so augmented profits are also £100,000.</p>
<ul>
<li>Tax at the main rate: £100,000 × 25% = <strong>£25,000</strong></li>
<li>Marginal relief: 3/200 × (£250,000 − £100,000) × (£100,000 ÷ £100,000) = 3/200 × £150,000 = <strong>£2,250</strong></li>
<li>Corporation tax payable: £25,000 − £2,250 = <strong>£22,750</strong>, an effective rate of 22.75%</li>
</ul>
<p>Note the practical point that the effective rate is not the marginal rate. If the company earned one more pound of profit, that pound would bear tax at <strong>26.5%</strong> — higher than the main rate itself, which is why companies near the £250,000 threshold receive so much advice about timing.</p>
</div>
</div>
</section>
<section id="relieving-trading-losses-1" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="relieving-trading-losses-1"><span class="header-section-number">6.6.4</span> Relieving trading losses</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Relief</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>s.37 CTA 2010</strong></td>
<td>Set the loss against <strong>total profits</strong> of the <strong>same</strong> accounting period, and/or carry it <strong>back 12 months</strong> against total profits</td>
</tr>
<tr class="even">
<td><strong>s.45A CTA 2010</strong></td>
<td>Carry <strong>forward</strong> against <strong>total profits</strong> of later periods (for losses arising on or after 1 April 2017), and surrender within a group</td>
</tr>
<tr class="odd">
<td><strong>s.45 CTA 2010</strong></td>
<td>Losses arising before 1 April 2017 carry forward only against profits of the <strong>same trade</strong></td>
</tr>
<tr class="even">
<td>Terminal loss relief</td>
<td>On cessation, carry back <strong>three</strong> years</td>
</tr>
<tr class="odd">
<td><strong>Group relief</strong></td>
<td>Surrender current-period losses to a <strong>75% group</strong> company</td>
</tr>
</tbody>
</table>
<p>Carried-forward losses are subject to a <strong>restriction</strong>: a company (or group) may use its <strong>£5 million deductions allowance</strong> in full, but beyond that may relieve only <strong>50%</strong> of remaining profits with carried-forward losses.</p>
</section>
<section id="payment-and-collection" class="level3" data-number="6.6.5">
<h3 data-number="6.6.5" class="anchored" data-anchor-id="payment-and-collection"><span class="header-section-number">6.6.5</span> Payment and collection</h3>
<ul>
<li><strong>Payment</strong>: <strong>9 months and 1 day</strong> after the end of the accounting period, for a company that is not “large”.</li>
<li><strong>Large companies</strong> (augmented profits above £1.5 million) pay by <strong>quarterly instalments</strong>; <strong>very large</strong> companies (above £20 million) pay on an accelerated instalment timetable. The £1.5 million and £20 million limits are also divided among associated companies.</li>
<li><strong>Return</strong>: form CT600, within <strong>12 months</strong> of the end of the accounting period. Note that the filing deadline is later than the payment deadline, which is counter-intuitive and examinable.</li>
<li>A company must <strong>notify HMRC</strong> that it is chargeable within <strong>three months</strong> of starting business activity.</li>
</ul>
</section>
<section id="distributions-and-close-companies" class="level3" data-number="6.6.6">
<h3 data-number="6.6.6" class="anchored" data-anchor-id="distributions-and-close-companies"><span class="header-section-number">6.6.6</span> Distributions and close companies</h3>
<p><strong>Dividends paid</strong> by a company are a distribution of taxed profit and are <strong>not deductible</strong>. Dividends <strong>received</strong> by a UK company from another company are, in most cases, <strong>exempt</strong> from corporation tax, which prevents the same profit being taxed repeatedly as it moves up a group.</p>
<p>A <strong>close company</strong> is one under the control of five or fewer participators, or of participators who are directors. Almost every owner-managed company is close. Two anti-avoidance charges follow, and the first is regularly examined because it catches the director’s loan account:</p>
<ul>
<li><strong>Section 455 CTA 2010</strong>: where a close company makes a <strong>loan to a participator</strong>, the company must pay a charge on the amount of the loan at the <strong>dividend upper rate</strong>, due <strong>9 months and 1 day</strong> after the end of the accounting period. It is <strong>refundable</strong> when the loan is repaid, released or written off. The rate is <strong>35.75%</strong> for loans made on or after <strong>6 April 2026</strong> and 33.75% for loans made before then — it tracks the dividend upper rate, so it moved when that rate moved. This is a charge on the <strong>company</strong>, and it sits alongside — not instead of — the s.197 CA 2006 requirement for members’ approval and any benefit-in-kind charge on the director.</li>
<li><strong>Section 464A</strong>: a similar charge where a close company confers a benefit on a participator otherwise than by way of a loan.</li>
</ul>
</section>
<section id="anti-avoidance-in-outline" class="level3" data-number="6.6.7">
<h3 data-number="6.6.7" class="anchored" data-anchor-id="anti-avoidance-in-outline"><span class="header-section-number">6.6.7</span> Anti-avoidance in outline</h3>
<p>The specification asks for the <strong>scope</strong> of anti-avoidance provisions, not their detail:</p>
<ul>
<li>The <strong>General Anti-Abuse Rule</strong> (Finance Act 2013) counteracts tax advantages arising from <strong>abusive</strong> arrangements — those that cannot reasonably be regarded as a reasonable course of action — applying a “double reasonableness” test, with an independent GAAR Advisory Panel.</li>
<li><strong>Transfer pricing</strong> requires transactions between connected parties to be priced on <strong>arm’s length</strong> terms.</li>
<li><strong>DOTAS</strong> requires the <strong>disclosure</strong> of notifiable tax avoidance schemes, giving each a scheme reference number that users must report.</li>
<li>The <strong>corporate interest restriction</strong> limits the deductibility of interest for large groups.</li>
<li><strong>Transactions in securities</strong> rules counteract arrangements designed to convert what would be income into capital.</li>
<li>The distinction that underlies all of it: <strong>tax avoidance</strong> is lawful but may be counteracted; <strong>tax evasion</strong> is criminal, and a solicitor who assists it commits an offence and breaches the SRA Principles.</li>
</ul>
</section>
</section>
<section id="value-added-tax" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="value-added-tax"><span class="header-section-number">6.7</span> Value added tax</h2>
<section id="the-scope-of-the-charge" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="the-scope-of-the-charge"><span class="header-section-number">6.7.1</span> The scope of the charge</h3>
<p>VAT is charged on any <strong>supply of goods or services</strong> made in the <strong>United Kingdom</strong>, where it is a <strong>taxable supply</strong> made by a <strong>taxable person</strong> in the course or furtherance of any <strong>business</strong> carried on by them (s.4 VATA 1994). All four elements must be present.</p>
<p>VAT is a tax on <strong>consumption</strong>, collected in stages. A registered business charges <strong>output tax</strong> on its supplies, recovers <strong>input tax</strong> on its purchases, and accounts to HMRC for the difference. The burden falls on the final, unregistered consumer.</p>
</section>
<section id="rates-and-categories" class="level3" data-number="6.7.2">
<h3 data-number="6.7.2" class="anchored" data-anchor-id="rates-and-categories"><span class="header-section-number">6.7.2</span> Rates and categories</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Rate</th>
<th>Input tax recoverable?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Standard-rated</strong></td>
<td><strong>20%</strong></td>
<td>Yes</td>
</tr>
<tr class="even">
<td><strong>Reduced-rated</strong> — domestic fuel and power, children’s car seats, certain energy-saving materials</td>
<td><strong>5%</strong></td>
<td>Yes</td>
</tr>
<tr class="odd">
<td><strong>Zero-rated</strong> — most food, books and newspapers, children’s clothing, new residential construction, public transport, most drugs and medicines on prescription</td>
<td><strong>0%</strong></td>
<td><strong>Yes</strong></td>
</tr>
<tr class="even">
<td><strong>Exempt</strong> — insurance, most financial services, education, health and welfare, postal services, most supplies of land</td>
<td>No VAT charged</td>
<td><strong>No</strong></td>
</tr>
<tr class="odd">
<td><strong>Outside the scope</strong></td>
<td>No VAT</td>
<td>No</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Zero-rated is not the same as exempt</strong>, and the difference is worth real money. A business making zero-rated supplies charges no output tax <strong>but recovers its input tax in full</strong> — so it is typically in a repayment position with HMRC. A business making exempt supplies charges no output tax and <strong>cannot recover its input tax</strong>, which becomes an irrecoverable cost. This is the single most reliable VAT question in the subject.</p>
</div>
</div>
</section>
<section id="registration" class="level3" data-number="6.7.3">
<h3 data-number="6.7.3" class="anchored" data-anchor-id="registration"><span class="header-section-number">6.7.3</span> Registration</h3>
<div class="callout callout-style-default callout-caution callout-titled" title="Thresholds — 2026/27">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Thresholds — 2026/27
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Registration threshold</strong>: taxable turnover of <strong>£90,000</strong></li>
<li><strong>Deregistration threshold</strong>: <strong>£88,000</strong></li>
</ul>
<p>Both have been at these levels since 1 April 2024.</p>
</div>
</div>
<p>Registration is compulsory under either of two tests:</p>
<ul>
<li><strong>The historic test.</strong> Taxable turnover in the <strong>preceding 12 months</strong> (a rolling period, not a financial year) has exceeded the threshold. The business must <strong>notify HMRC within 30 days of the end of the month</strong> in which the threshold was exceeded, and is registered from the <strong>first day of the second month</strong> after that.</li>
<li><strong>The future test.</strong> There are reasonable grounds to believe that taxable turnover <strong>in the next 30 days alone</strong> will exceed the threshold. The business must notify <strong>by the end of that 30-day period</strong>, and is registered from the <strong>beginning</strong> of it.</li>
</ul>
<p><strong>Exception</strong>: HMRC may grant an exception from registration under the historic test where the business can satisfy them that turnover in the following 12 months will not exceed the <strong>deregistration</strong> threshold.</p>
<p><strong>Voluntary registration</strong> is available below the threshold, and is worth taking where the business makes zero-rated supplies or sells mainly to other registered businesses, because it unlocks input tax recovery.</p>
<p><strong>Deregistration</strong> may be requested where turnover falls below the deregistration threshold, and is compulsory where the business ceases to make taxable supplies.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>The two tests use different periods and produce different registration dates. The historic test looks <strong>back</strong> over 12 months and gives a start date roughly six weeks later; the future test looks <strong>forward 30 days only</strong> and registers the business from the <strong>start</strong> of that period, with no grace. A scenario in which a business wins a single large contract that will take it over the threshold within a month is a <strong>future test</strong> question, and the answer is immediate registration.</p>
</div>
</div>
</section>
<section id="input-tax-tax-points-invoices-and-returns" class="level3" data-number="6.7.4">
<h3 data-number="6.7.4" class="anchored" data-anchor-id="input-tax-tax-points-invoices-and-returns"><span class="header-section-number">6.7.4</span> Input tax, tax points, invoices and returns</h3>
<p><strong>Blocked input tax</strong> cannot be recovered even by a fully taxable business: <strong>business entertainment</strong>, <strong>cars</strong> (unless used exclusively for business), and anything not used for business purposes. Where a business makes both taxable and exempt supplies it is <strong>partially exempt</strong> and must apportion.</p>
<p><strong>The tax point</strong> determines the return period in which VAT is accounted for:</p>
<ul>
<li>The <strong>basic tax point</strong> is the date the goods are <strong>removed or made available</strong>, or the date the services are <strong>completed</strong>.</li>
<li>An <strong>actual tax point</strong> overrides it if a <strong>VAT invoice is issued or payment is received before</strong> the basic tax point (that earlier date applies), or if a VAT invoice is issued <strong>within 14 days after</strong> the basic tax point (the invoice date applies).</li>
</ul>
<p><strong>VAT invoices</strong> must be issued to other registered persons within <strong>30 days</strong> of the supply, and must contain the prescribed particulars — an identifying number, the supplier’s name, address and VAT registration number, the tax point, the customer’s name and address, a description of the goods or services, the amount excluding VAT, the rate, and the VAT charged.</p>
<p><strong>Returns and records</strong>: returns are normally <strong>quarterly</strong>, filed and paid within <strong>one month and seven days</strong> of the end of the period. <strong>Making Tax Digital</strong> requires digital record-keeping and submission through compatible software. Records must be kept for <strong>six years</strong>. Late filing is dealt with by a <strong>points-based</strong> penalty regime, and late payment by escalating penalties and interest.</p>
</section>
</section>
<section id="inheritance-tax-business-property-relief" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="inheritance-tax-business-property-relief"><span class="header-section-number">6.8</span> Inheritance tax: business property relief</h2>
<p>The specification limits IHT in Business Law and Practice to <strong>business property relief</strong>. What you need around it is minimal: IHT is charged at <strong>40%</strong> on the death estate above the <strong>nil rate band</strong> (£325,000), and at <strong>20%</strong> on lifetime chargeable transfers above it.</p>
<p><strong>Business property relief</strong> (IHTA 1984 ss.103–114) reduces the <strong>value transferred</strong> by a transfer of value attributable to <strong>relevant business property</strong>. It applies both to lifetime transfers and on death, and it is applied <strong>before</strong> the nil rate band.</p>
<section id="what-qualifies-and-at-what-rate" class="level3" data-number="6.8.1">
<h3 data-number="6.8.1" class="anchored" data-anchor-id="what-qualifies-and-at-what-rate"><span class="header-section-number">6.8.1</span> What qualifies, and at what rate</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Relevant business property</th>
<th>Rate (historic position)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A <strong>business or an interest in a business</strong> — a sole trade, or a partnership or LLP share</td>
<td><strong>100%</strong></td>
</tr>
<tr class="even">
<td><strong>Unquoted shares</strong> in a company</td>
<td><strong>100%</strong></td>
</tr>
<tr class="odd">
<td><strong>Quoted shares or securities</strong> which gave the transferor <strong>control</strong> of the company</td>
<td><strong>50%</strong></td>
</tr>
<tr class="even">
<td><strong>Land, buildings, plant or machinery</strong> owned personally and used in a business carried on by a company the transferor <strong>controlled</strong>, or by a <strong>partnership</strong> of which they were a partner</td>
<td><strong>50%</strong></td>
</tr>
<tr class="odd">
<td>Such assets held in a <strong>trust</strong> in which the transferor had an interest in possession and used in their business</td>
<td><strong>50%</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="the-conditions" class="level3" data-number="6.8.2">
<h3 data-number="6.8.2" class="anchored" data-anchor-id="the-conditions"><span class="header-section-number">6.8.2</span> The conditions</h3>
<ul>
<li><strong>Two years’ ownership</strong> (s.106). The property must have been owned by the transferor throughout the two years immediately before the transfer. Section 107 allows <strong>replacement</strong> property to count, and s.108/109 aggregate periods on <strong>succession</strong> — notably, property inherited from a spouse counts from the spouse’s acquisition, and the two-year test is dispensed with where the transferor inherited it on the spouse’s death.</li>
<li><strong>Not an excluded business</strong> (s.105(3)). No relief where the business consists <strong>wholly or mainly</strong> of <strong>dealing in securities, stocks or shares, land or buildings, or making or holding investments</strong>. This is the provision that denies relief to a property investment business, while a property <strong>development</strong> or <strong>trading</strong> business qualifies. The test is applied “in the round” to the business as a whole.</li>
<li><strong>No excepted assets</strong> (s.112). Relief is denied for the value attributable to assets that were neither used wholly or mainly for the business throughout the last two years nor required for its future use — the classic example being a large cash balance far in excess of the business’s needs.</li>
<li><strong>No binding contract for sale</strong> (s.113). If the property is subject to a binding contract for sale at the date of transfer, it is not relevant business property. This is why partnership and shareholders’ agreements use <strong>cross-option agreements</strong> (reciprocal put and call options, exercisable on death) rather than automatic buy-and-sell provisions: an option is not a binding contract for sale, so relief is preserved.</li>
</ul>
<div class="callout callout-style-default callout-caution callout-titled" title="A major change takes effect on 6 April 2026 — verify against your cut-off">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A major change takes effect on 6 April 2026 — verify against your cut-off
</div>
</div>
<div class="callout-body-container callout-body">
<p>From <strong>6 April 2026</strong> the 100% rate is <strong>capped</strong>. An <strong>allowance</strong> applies to the <strong>combined</strong> value of agricultural property qualifying for agricultural property relief and business property qualifying for BPR: value within the allowance attracts <strong>100%</strong> relief, and value <strong>above</strong> it attracts <strong>50%</strong>.</p>
<p>The allowance was announced at the Autumn Budget 2024 at £1 million, and was <strong>increased to £2.5 million</strong> on 23 December 2025. It is <strong>transferable between spouses and civil partners</strong>.</p>
<p>Separately, shares <strong>designated as “not listed”</strong> on the markets of a recognised stock exchange — AIM shares being the obvious case — move to a flat <strong>50%</strong> relief, and the allowance is <strong>not</strong> available against them.</p>
<p>This is recent, and the figure moved twice. Check the position at your sitting’s cut-off date before relying on it, and check whether the pre-6 April 2026 position (uncapped 100% relief) is the examinable one for you.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>The two BPR traps that appear most often are the <strong>investment business</strong> exclusion in s.105(3) — a company whose business is letting property gets <strong>no</strong> relief, however substantial — and the <strong>binding contract for sale</strong> point in s.113, which is set up by telling you the partnership agreement requires the surviving partners to buy the deceased’s share.</p>
</div>
</div>
</section>
</section>
<section id="putting-it-together-the-structuring-questions" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="putting-it-together-the-structuring-questions"><span class="header-section-number">6.9</span> Putting it together: the structuring questions</h2>
<section id="salary-or-dividend" class="level3" data-number="6.9.1">
<h3 data-number="6.9.1" class="anchored" data-anchor-id="salary-or-dividend"><span class="header-section-number">6.9.1</span> Salary or dividend?</h3>
<p>For an owner-manager, the arithmetic is driven by four facts:</p>
<ul>
<li><strong>Salary is deductible</strong> in computing the company’s corporation tax; a <strong>dividend is not</strong>.</li>
<li><strong>Salary attracts National Insurance</strong> — the employee’s Class 1 and, more expensively, the employer’s Class 1 secondary at 15%. A <strong>dividend attracts none</strong>.</li>
<li>A dividend can be paid <strong>only out of distributable profits</strong> (s.830 CA 2006 — see <a href="blp-04-finance.html" class="quarto-xref"><span>Chapter 5</span></a>). Paying one without them is unlawful, whatever its tax attractions.</li>
<li>Dividend income is taxed at <strong>lower rates</strong> than earned income, but out of <strong>already-taxed</strong> profits.</li>
</ul>
<p>The usual advice is a modest salary — enough to preserve a National Insurance record and to use allowances — with the balance as dividends, subject to there being distributable profits and to the company’s needs. The rise in dividend rates from 6 April 2026 has narrowed the advantage.</p>
</section>
<section id="incorporating-an-existing-business" class="level3" data-number="6.9.2">
<h3 data-number="6.9.2" class="anchored" data-anchor-id="incorporating-an-existing-business"><span class="header-section-number">6.9.2</span> Incorporating an existing business</h3>
<p>The tax consequences of transferring a sole trade or partnership to a company:</p>
<ul>
<li><strong>CGT</strong>: a disposal of the business assets at market value, with <strong>incorporation relief</strong> (s.162) available automatically where the whole business goes across as a going concern for shares — or <strong>hold-over relief</strong> (s.165) as an alternative on a transfer of assets. Business asset disposal relief may be preferable where the client wants to crystallise the gain at the reduced rate.</li>
<li><strong>Capital allowances</strong>: balancing charges or allowances arise unless the assets are transferred at tax written-down value under a joint election.</li>
<li><strong>VAT</strong>: a <strong>transfer of a going concern</strong> is outside the scope of VAT provided the conditions are met, including that the transferee is or becomes registered.</li>
<li><strong>Stamp duty land tax</strong> on any land transferred, and <strong>stamp duty</strong> on any subsequent transfer of the shares.</li>
<li><strong>Losses</strong>: unrelieved trading losses may be carried forward under s.86 ITA 2007 against income the individual receives <strong>from the company</strong>.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Incorporation relief is <strong>automatic</strong> where its conditions are met — the taxpayer does not claim it, they elect <strong>out</strong> of it under s.162A. That is the opposite of hold-over relief under s.165, which requires a <strong>joint claim</strong>. Questions test the difference by asking what the client must <strong>do</strong>.</p>
</div>
</div>
</section>
</section>
<section id="the-solicitors-position" class="level2" data-number="6.10">
<h2 data-number="6.10" class="anchored" data-anchor-id="the-solicitors-position"><span class="header-section-number">6.10</span> The solicitor’s position</h2>
<p><strong>Tax evasion.</strong> A solicitor who knowingly assists a client to evade tax commits a criminal offence and breaches the SRA Principles. The distinction from lawful avoidance is one of legality, not of morality: misrepresenting facts to HMRC, concealing income, or backdating documents is evasion.</p>
<p><strong>Failure to prevent the facilitation of tax evasion.</strong> The Criminal Finances Act 2017 creates corporate offences for a body (including a law firm) that fails to prevent an associated person from criminally facilitating tax evasion. The defence is having reasonable prevention procedures.</p>
<p><strong>Competence.</strong> A solicitor must only act within their competence. Business tax is a specialist field, and the right answer in many scenarios is that the solicitor should advise the client to obtain specialist tax advice rather than opine on a computation themselves.</p>
<p><strong>Reporting.</strong> Suspicion that funds represent the proceeds of crime — and tax evaded is a benefit from criminal conduct — engages the money laundering reporting obligations, and the solicitor must not tip the client off.</p>
</section>
<section id="chapter-review" class="level2" data-number="6.11">
<h2 data-number="6.11" class="anchored" data-anchor-id="chapter-review"><span class="header-section-number">6.11</span> Chapter review</h2>
<p><strong>Q1.</strong> A UK trading company has taxable total profits of £180,000 for the year ended 31 March 2027. It has no associated companies and no franked investment income.</p>
<p>Which of the following correctly describes the corporation tax position?</p>
<p>A. The whole profit is taxed at 19%, because it is below £250,000.</p>
<p>B. The whole profit is taxed at 25%, with no relief.</p>
<p>C. The profit is taxed at the main rate of 25% with marginal relief, giving an effective rate between 19% and 25%; each additional pound of profit in this band bears tax at a marginal rate of 26.5%.</p>
<p>D. The first £50,000 is taxed at 19% and the balance at 25%, as separate slices.</p>
<p>E. The company may choose between the small profits rate and the main rate.</p>
<p><strong>Q2.</strong> A business supplies children’s clothing, which is zero-rated. It incurs substantial input VAT on its purchases and overheads.</p>
<p>Which of the following is correct?</p>
<p>A. It cannot register for VAT, because it makes no standard-rated supplies.</p>
<p>B. It charges no output VAT and cannot recover its input VAT, which is an irrecoverable cost.</p>
<p>C. It charges output VAT at 0% and may recover its input VAT in full, so it will usually be in a repayment position with HMRC.</p>
<p>D. It charges output VAT at 5% and may recover its input VAT in full.</p>
<p>E. Its supplies are exempt, so registration is not available.</p>
<p><strong>Q3.</strong> A client owns 100% of the shares in an unquoted company whose business consists wholly of buying residential property, letting it to tenants and holding it for capital growth. He has owned the shares for fifteen years. He dies, leaving the shares to his son.</p>
<p>What is the position on business property relief?</p>
<p>A. 100% relief, because the shares are unquoted and were owned for more than two years.</p>
<p>B. 50% relief, because the shares gave him control.</p>
<p>C. No relief, because the business consists wholly or mainly of making or holding investments and is excluded by s.105(3) IHTA 1984.</p>
<p>D. 100% relief, but only up to the available allowance, with 50% above it.</p>
<p>E. Relief is available only if the son continues the business for two years.</p>
<p><strong>Q4.</strong> A close company lends £60,000 to its sole shareholder-director. The loan is outstanding at the end of the accounting period and remains outstanding nine months and one day afterwards.</p>
<p>Which of the following is correct?</p>
<p>A. There is no tax consequence, because a director’s loan is a balance sheet item.</p>
<p>B. The company must pay a charge under s.455 CTA 2010 on the amount of the loan at the dividend upper rate, due nine months and one day after the end of the accounting period; the charge is repayable when the loan is repaid, released or written off.</p>
<p>C. The shareholder must pay income tax on the loan as if it were a dividend.</p>
<p>D. The company must pay corporation tax on the loan at the main rate of 25%.</p>
<p>E. The loan is void, because a company may not lend to its own shareholder.</p>
<p><strong>Q5.</strong> A sole trader’s business is expanding fast. Her taxable turnover for the twelve months to 31 May 2027 was £71,000. On 3 June 2027 she signs a contract to deliver £95,000 of services within the following four weeks.</p>
<p>What must she do?</p>
<p>A. Nothing yet, because her turnover in the preceding 12 months has not exceeded £90,000.</p>
<p>B. Notify HMRC by 30 June 2027, because she has reasonable grounds to believe her taxable turnover in the next 30 days alone will exceed £90,000; she will be registered from the beginning of that 30-day period.</p>
<p>C. Notify HMRC within 30 days of the end of June 2027, and will be registered from 1 August 2027.</p>
<p>D. Register only once her rolling 12-month turnover exceeds £90,000.</p>
<p>E. Apply for an exception from registration, because the increase is a one-off.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — C.</strong> Augmented profits of £180,000 fall between the lower limit of £50,000 and the upper limit of £250,000, so tax is charged at the main rate of 25% and reduced by marginal relief of 3/200 × (£250,000 − £180,000) × (£180,000 ÷ £180,000) = £1,050. The result is an effective rate between 19% and 25%, and the marginal rate within the band is <strong>26.5%</strong>.</p>
<ul>
<li><strong>A</strong> applies the small profits rate above its limit.</li>
<li><strong>B</strong> ignores marginal relief.</li>
<li><strong>D</strong> describes a slice system that corporation tax does not use — this is the most common error, and it is borrowed from income tax.</li>
<li><strong>E</strong> invents an election.</li>
</ul>
<p><strong>Q2 — C.</strong> Zero-rated supplies are <strong>taxable</strong> supplies charged at 0%. The business charges no VAT to its customers but recovers input tax <strong>in full</strong>, and therefore usually reclaims from HMRC. It counts towards the registration threshold and may register voluntarily below it.</p>
<ul>
<li><strong>A</strong> and <strong>E</strong> confuse zero-rated with exempt.</li>
<li><strong>B</strong> describes the <strong>exempt</strong> position.</li>
<li><strong>D</strong> applies the reduced rate.</li>
</ul>
<p><strong>Q3 — C.</strong> Section 105(3) IHTA 1984 excludes from relevant business property a business consisting wholly or mainly of dealing in securities, stocks or shares, land or buildings, or <strong>making or holding investments</strong>. A residential property letting business is the paradigm case. No BPR is available, however long the shares have been held and however substantial the business.</p>
<ul>
<li><strong>A</strong> applies the general rule for unquoted shares without checking the exclusion.</li>
<li><strong>B</strong> applies the 50% rate for <strong>quoted</strong> controlling shareholdings.</li>
<li><strong>D</strong> applies the post-6 April 2026 allowance, which is irrelevant where the property is not relevant business property at all.</li>
<li><strong>E</strong> invents a continuation condition.</li>
</ul>
<p><strong>Q4 — B.</strong> Section 455 CTA 2010. A loan by a close company to a participator triggers a charge on the <strong>company</strong> at the <strong>dividend upper rate</strong> — 35.75% for loans made on or after 6 April 2026, and 33.75% for loans made before that date — payable at the same time as the corporation tax for the period, and <strong>refundable</strong> when the loan is repaid, released or written off. Note that the s.197 CA 2006 requirement for members’ approval applies independently, and there may also be a benefit-in-kind charge on the director if the loan is interest-free.</p>
<ul>
<li><strong>A</strong> ignores the charge entirely.</li>
<li><strong>C</strong> describes the treatment if the loan is <strong>written off</strong>, not while it is outstanding.</li>
<li><strong>D</strong> applies the wrong rate and mischaracterises the charge.</li>
<li><strong>E</strong> invents a prohibition.</li>
</ul>
<p><strong>Q5 — B.</strong> The <strong>future test</strong>: where there are reasonable grounds to believe that taxable turnover in the <strong>next 30 days alone</strong> will exceed the threshold, the business must notify HMRC <strong>by the end of that 30-day period</strong> and is registered from its <strong>beginning</strong>. £95,000 in four weeks exceeds £90,000.</p>
<ul>
<li><strong>A</strong> and <strong>D</strong> apply only the historic test and miss the forward-looking one.</li>
<li><strong>C</strong> applies the historic test’s notification and registration dates, which are different.</li>
<li><strong>E</strong> misapplies the exception, which is available under the <strong>historic</strong> test where future turnover will fall below the deregistration threshold — the opposite of these facts.</li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../flk1/blp-04-finance.html" class="pagination-link" aria-label="Financing the business">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Financing the business</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../flk1/blp-06-termination.html" class="pagination-link" aria-label="Termination, insolvency and bankruptcy">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>