<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Issuing, serving, pleading and responding – Functioning Legal Knowledge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../flk1/dr-04-case-management.html" rel="next">
<link href="../flk1/dr-02-preaction.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0a4414a393388c898190164198f83909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../flk1/dr-00-overview.html">Dispute Resolution</a></li><li class="breadcrumb-item"><a href="../flk1/dr-03-commencing.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Issuing, serving, pleading and responding</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Functioning Legal Knowledge</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to use this text</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Business Law and Practice</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-00-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Business Law and Practice: what is examined</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-01-vehicles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Choosing and forming the vehicle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-02-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Running the business</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-03-stakeholders.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Stakeholders: rights, powers and protection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-04-finance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Financing the business</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-05-taxation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Taxation of the business and its stakeholders</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-06-termination.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Termination, insolvency and bankruptcy</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Dispute Resolution</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-00-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Dispute Resolution: what is examined</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-01-merits-and-forum.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing the dispute and choosing the forum</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-02-preaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Before proceedings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-03-commencing.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Issuing, serving, pleading and responding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-04-case-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Running the claim</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-05-evidence-disclosure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Proving the case</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-06-trial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Trial, appeals and enforcement</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-07-costs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Who pays, and how much</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/blp-07-authorities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Authorities and numbers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../flk1/dr-08-authorities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Dispute Resolution: authorities, rules and numbers</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#issuing-the-claim-form" id="toc-issuing-the-claim-form" class="nav-link active" data-scroll-target="#issuing-the-claim-form"><span class="header-section-number">11.1</span> Issuing the claim form</a>
  <ul class="collapse">
  <li><a href="#the-claim-form-n1" id="toc-the-claim-form-n1" class="nav-link" data-scroll-target="#the-claim-form-n1"><span class="header-section-number">11.1.1</span> The claim form (N1)</a></li>
  <li><a href="#naming-the-parties" id="toc-naming-the-parties" class="nav-link" data-scroll-target="#naming-the-parties"><span class="header-section-number">11.1.2</span> Naming the parties</a></li>
  <li><a href="#adding-removing-and-substituting-parties" id="toc-adding-removing-and-substituting-parties" class="nav-link" data-scroll-target="#adding-removing-and-substituting-parties"><span class="header-section-number">11.1.3</span> Adding, removing and substituting parties</a></li>
  </ul></li>
  <li><a href="#serving-the-claim-form" id="toc-serving-the-claim-form" class="nav-link" data-scroll-target="#serving-the-claim-form"><span class="header-section-number">11.2</span> Serving the claim form</a>
  <ul class="collapse">
  <li><a href="#the-time-limit" id="toc-the-time-limit" class="nav-link" data-scroll-target="#the-time-limit"><span class="header-section-number">11.2.1</span> The time limit</a></li>
  <li><a href="#extending-time-for-service" id="toc-extending-time-for-service" class="nav-link" data-scroll-target="#extending-time-for-service"><span class="header-section-number">11.2.2</span> Extending time for service</a></li>
  <li><a href="#the-methods-and-the-address" id="toc-the-methods-and-the-address" class="nav-link" data-scroll-target="#the-methods-and-the-address"><span class="header-section-number">11.2.3</span> The methods and the address</a></li>
  <li><a href="#deemed-service" id="toc-deemed-service" class="nav-link" data-scroll-target="#deemed-service"><span class="header-section-number">11.2.4</span> Deemed service</a></li>
  <li><a href="#service-by-an-alternative-method" id="toc-service-by-an-alternative-method" class="nav-link" data-scroll-target="#service-by-an-alternative-method"><span class="header-section-number">11.2.5</span> Service by an alternative method</a></li>
  <li><a href="#service-out-of-the-jurisdiction" id="toc-service-out-of-the-jurisdiction" class="nav-link" data-scroll-target="#service-out-of-the-jurisdiction"><span class="header-section-number">11.2.6</span> Service out of the jurisdiction</a></li>
  </ul></li>
  <li><a href="#statements-of-case" id="toc-statements-of-case" class="nav-link" data-scroll-target="#statements-of-case"><span class="header-section-number">11.3</span> Statements of case</a>
  <ul class="collapse">
  <li><a href="#particulars-of-claim" id="toc-particulars-of-claim" class="nav-link" data-scroll-target="#particulars-of-claim"><span class="header-section-number">11.3.1</span> Particulars of claim</a></li>
  <li><a href="#defence" id="toc-defence" class="nav-link" data-scroll-target="#defence"><span class="header-section-number">11.3.2</span> Defence</a></li>
  <li><a href="#reply-part-20-claims-and-further-information" id="toc-reply-part-20-claims-and-further-information" class="nav-link" data-scroll-target="#reply-part-20-claims-and-further-information"><span class="header-section-number">11.3.3</span> Reply, Part 20 claims and further information</a></li>
  <li><a href="#amendments" id="toc-amendments" class="nav-link" data-scroll-target="#amendments"><span class="header-section-number">11.3.4</span> Amendments</a></li>
  <li><a href="#the-statement-of-truth" id="toc-the-statement-of-truth" class="nav-link" data-scroll-target="#the-statement-of-truth"><span class="header-section-number">11.3.5</span> The statement of truth</a></li>
  </ul></li>
  <li><a href="#responding-to-a-claim" id="toc-responding-to-a-claim" class="nav-link" data-scroll-target="#responding-to-a-claim"><span class="header-section-number">11.4</span> Responding to a claim</a>
  <ul class="collapse">
  <li><a href="#the-time-limits" id="toc-the-time-limits" class="nav-link" data-scroll-target="#the-time-limits"><span class="header-section-number">11.4.1</span> The time limits</a></li>
  <li><a href="#the-options" id="toc-the-options" class="nav-link" data-scroll-target="#the-options"><span class="header-section-number">11.4.2</span> The options</a></li>
  <li><a href="#default-judgment" id="toc-default-judgment" class="nav-link" data-scroll-target="#default-judgment"><span class="header-section-number">11.4.3</span> Default judgment</a></li>
  <li><a href="#discontinuance-and-settlement" id="toc-discontinuance-and-settlement" class="nav-link" data-scroll-target="#discontinuance-and-settlement"><span class="header-section-number">11.4.4</span> Discontinuance and settlement</a></li>
  </ul></li>
  <li><a href="#check-yourself" id="toc-check-yourself" class="nav-link" data-scroll-target="#check-yourself"><span class="header-section-number">11.5</span> Check yourself</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../flk1/dr-00-overview.html">Dispute Resolution</a></li><li class="breadcrumb-item"><a href="../flk1/dr-03-commencing.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Issuing, serving, pleading and responding</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-dr-commencing" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Issuing, serving, pleading and responding</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><em>Assessment objective 4: commencing, responding to or progressing a claim.</em></p>
</blockquote>
<section id="issuing-the-claim-form" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="issuing-the-claim-form"><span class="header-section-number">11.1</span> Issuing the claim form</h2>
<p>Proceedings are <strong>started</strong> when the court <strong>issues</strong> a claim form at the claimant’s request (CPR 7.2) — but for limitation purposes the claim is <strong>brought</strong> when the claim form is <strong>received</strong> by the court office. Both propositions matter, and they answer different questions.</p>
<p>The <strong>Part 7</strong> procedure is the standard route for a disputed claim. <strong>Part 8</strong> is for claims where there is unlikely to be a substantial dispute of fact, and where the rules require or permit it.</p>
<section id="the-claim-form-n1" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="the-claim-form-n1"><span class="header-section-number">11.1.1</span> The claim form (N1)</h3>
<p>CPR 16.2 requires the claim form to:</p>
<ul>
<li><strong>name the parties</strong> correctly;</li>
<li>contain a <strong>concise statement of the nature of the claim</strong>;</li>
<li><strong>specify the remedy</strong> sought — though the court may grant a remedy the claimant has not asked for;</li>
<li>where money is claimed, contain a <strong>statement of value</strong> (CPR 16.3): the amount claimed, or a statement that the claimant expects to recover not more than £10,000, more than £10,000 but not more than £25,000, more than £25,000 but not more than £100,000, or more than £100,000 — and, if issued in the High Court, why the claimant is entitled to issue there;</li>
<li>be verified by a <strong>statement of truth</strong>.</li>
</ul>
<p>The <strong>court fee</strong> is calculated on the value claimed, so pleading the claim too high is expensive and pleading it too low caps recovery.</p>
</section>
<section id="naming-the-parties" class="level3" data-number="11.1.2">
<h3 data-number="11.1.2" class="anchored" data-anchor-id="naming-the-parties"><span class="header-section-number">11.1.2</span> Naming the parties</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Defendant</th>
<th>Named as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Individual</td>
<td>Full name, with title</td>
</tr>
<tr class="even">
<td>Sole trader</td>
<td>“<em>Name</em> trading as <em>Business Name</em>”</td>
</tr>
<tr class="odd">
<td>Partnership</td>
<td>The firm name, where the partners carried on business under it when the cause of action accrued</td>
</tr>
<tr class="even">
<td>Company</td>
<td>The full registered name, including “Limited” or “plc”</td>
</tr>
<tr class="odd">
<td>LLP</td>
<td>The full registered name</td>
</tr>
<tr class="even">
<td>Child or protected party</td>
<td>By or through a <strong>litigation friend</strong></td>
</tr>
<tr class="odd">
<td>Estate</td>
<td>The personal representatives, or if none, an order appointing a person to represent the estate</td>
</tr>
</tbody>
</table>
</section>
<section id="adding-removing-and-substituting-parties" class="level3" data-number="11.1.3">
<h3 data-number="11.1.3" class="anchored" data-anchor-id="adding-removing-and-substituting-parties"><span class="header-section-number">11.1.3</span> Adding, removing and substituting parties</h3>
<p><strong>CPR 19.2</strong>: the court may <strong>remove</strong>, <strong>add</strong> or <strong>substitute</strong> a party where it is desirable so that the court can resolve all matters in dispute, or where there is an issue between an existing party and the new party which it is desirable to resolve.</p>
<p><strong>CPR 19.4</strong>: the court’s <strong>permission</strong> is required to add or substitute a party <strong>after</strong> the claim form has been served. Before service, the claimant may amend as of right.</p>
<p><strong>CPR 19.6 — after limitation has expired.</strong> This is the restrictive rule, and it is examined. The court may add or substitute a party <strong>only if</strong>:</p>
<ul>
<li>the relevant limitation period <strong>was current when the proceedings were started</strong>; <strong>and</strong></li>
<li>the addition or substitution is <strong>necessary</strong>.</li>
</ul>
<p>It is “necessary” <strong>only</strong> if the court is satisfied that:</p>
<ol type="a">
<li>the new party is to be <strong>substituted for a party who was named in the claim form by mistake</strong> for the new party;</li>
<li>the claim <strong>cannot properly be carried on</strong> by or against the original party unless the new party is added or substituted; or</li>
<li>the original party has <strong>died</strong> or had a <strong>bankruptcy order</strong> made against them and their interest or liability has passed to the new party.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>The mistake limb in CPR 19.6(3)(a) covers a mistake <strong>as to name</strong>, not a change of mind about <strong>who to sue</strong>. Naming “ABC Trading Ltd” when the contracting party was “ABC Trading (Northern) Ltd” is a mistake. Deciding, after limitation has expired, that you should have sued the director personally as well as the company is not — that is a new claim against a new party, and CPR 19.6 will not permit it.</p>
</div>
</div>
</section>
</section>
<section id="serving-the-claim-form" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="serving-the-claim-form"><span class="header-section-number">11.2</span> Serving the claim form</h2>
<section id="the-time-limit" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="the-time-limit"><span class="header-section-number">11.2.1</span> The time limit</h3>
<p><strong>CPR 7.5</strong>: the claimant must complete the <strong>step required</strong> by <strong>12.00 midnight on the calendar day four months after the date of issue</strong> of the claim form. Where the claim form is to be served <strong>out of the jurisdiction</strong>, the period is <strong>six months</strong> (CPR 7.5(2)).</p>
<p>The “step required” depends on the method:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Step required</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>First class post, DX or other next business day delivery</td>
<td><strong>Posting</strong>, leaving with, delivering to or collection by the relevant service provider</td>
</tr>
<tr class="even">
<td>Delivery to or leaving at a permitted address</td>
<td><strong>Delivering</strong> to or leaving the document at the relevant place</td>
</tr>
<tr class="odd">
<td>Personal service under CPR 6.5</td>
<td><strong>Leaving</strong> it with the individual</td>
</tr>
<tr class="even">
<td>Electronic method</td>
<td><strong>Sending</strong> the email or other transmission</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Under CPR 7.5 the claimant must complete the <strong>step</strong>, not achieve service, within four months. Posting the claim form by first class post on the last day is compliant even though deemed service falls afterwards. This is the single most frequently misunderstood rule in the service topic.</p>
</div>
</div>
</section>
<section id="extending-time-for-service" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="extending-time-for-service"><span class="header-section-number">11.2.2</span> Extending time for service</h3>
<p><strong>CPR 7.6.</strong> An application to extend must generally be made <strong>within</strong> the period for service. If made <strong>after</strong> it has expired, the court may only extend if:</p>
<ul>
<li>the court has <strong>failed to serve</strong> the claim form; or</li>
<li>the claimant has taken <strong>all reasonable steps</strong> to comply with CPR 7.5 but has been unable to do so; <strong>and</strong></li>
<li>in either case, the claimant has acted <strong>promptly</strong> in making the application.</li>
</ul>
<p>This is deliberately severe, because an extension after limitation has expired deprives the defendant of an accrued limitation defence.</p>
</section>
<section id="the-methods-and-the-address" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="the-methods-and-the-address"><span class="header-section-number">11.2.3</span> The methods and the address</h3>
<p><strong>CPR 6.3</strong> — permitted methods: personal service; first class post, DX or other next business day delivery service; leaving it at a specified place; fax or other means of <strong>electronic communication</strong>; or any method authorised by the court.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Service by <strong>email</strong> is valid only where the party to be served, or their solicitor, has <strong>indicated in writing</strong> that they are willing to accept service by that means and given an address for it. In <em>Barton v Wright Hassall LLP</em> [2018] UKSC 12 a litigant in person emailed the claim form to the defendant’s solicitors on the last day, without having established their willingness to accept email service. The Supreme Court refused to validate it retrospectively under CPR 6.15(2), and the claim was lost.</p>
</div>
</div>
<p><strong>Who to serve</strong> (CPR 6.7): if the defendant has given in writing the business address of a solicitor authorised to accept service, the claim form <strong>must</strong> be served on that solicitor. Otherwise CPR 6.9 supplies the place:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Defendant</th>
<th>Place of service</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Individual</td>
<td>Usual or last known <strong>residence</strong></td>
</tr>
<tr class="even">
<td>Individual being sued in the name of a business</td>
<td>Usual or last known residence, or the <strong>principal or last known place of business</strong></td>
</tr>
<tr class="odd">
<td>Partnership sued in the firm name</td>
<td>Usual or last known residence of a partner, or the <strong>principal or last known place of business</strong> of the partnership</td>
</tr>
<tr class="even">
<td><strong>Company</strong> registered in England and Wales</td>
<td>The <strong>principal office</strong>, or any place of business having a <strong>real connection</strong> with the claim</td>
</tr>
</tbody>
</table>
<p>A company may alternatively be served at its <strong>registered office</strong> under s.1139 Companies Act 2006.</p>
</section>
<section id="deemed-service" class="level3" data-number="11.2.4">
<h3 data-number="11.2.4" class="anchored" data-anchor-id="deemed-service"><span class="header-section-number">11.2.4</span> Deemed service</h3>
<p><strong>CPR 6.14 — the claim form.</strong> A claim form served within the United Kingdom is deemed to be served on the <strong>second business day after completion of the relevant step</strong> under CPR 7.5(1). There is a single rule and no method-by-method table, whatever the actual date of delivery.</p>
<p><strong>CPR 6.26 — every other document.</strong> Here there <em>is</em> a table:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Deemed date of service</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>First class post, DX or other next business day delivery</td>
<td>The <strong>second day</strong> after posting, if that is a business day; otherwise the <strong>next business day</strong> after that day</td>
</tr>
<tr class="even">
<td>Delivering to or leaving at a permitted address</td>
<td>If before <strong>4.30 p.m. on a business day</strong>, that day; otherwise the <strong>next business day</strong></td>
</tr>
<tr class="odd">
<td>Personal service</td>
<td>Same rule as above</td>
</tr>
<tr class="even">
<td>Fax</td>
<td>Same rule as above</td>
</tr>
<tr class="odd">
<td>Other electronic method</td>
<td>Same rule as above</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled" title="Worked example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Worked example
</div>
</div>
<div class="callout-body-container callout-body">
<p>A claim form is issued on Monday 4 May. The claimant posts it by first class post on Friday 28 August.</p>
<p><strong>Is service in time?</strong> The four-month period expires at midnight on 4 September. The <strong>step required</strong> for postal service is <strong>posting</strong>, which happened on 28 August. Service is in time.</p>
<p><strong>When is it deemed served?</strong> CPR 6.14: the <strong>second business day</strong> after completion of the step. Posting was Friday; the first business day after is Monday 31 August, the second is Tuesday 1 September. Deemed service is <strong>Tuesday 1 September</strong>, whatever day it actually arrived.</p>
<p><strong>When is the defence due?</strong> Fourteen days from service of the <strong>particulars of claim</strong>. If the particulars were served with the claim form, an acknowledgment of service or defence is due by 15 September; filing an acknowledgment extends the defence to 29 September.</p>
</div>
</div>
</section>
<section id="service-by-an-alternative-method" class="level3" data-number="11.2.5">
<h3 data-number="11.2.5" class="anchored" data-anchor-id="service-by-an-alternative-method"><span class="header-section-number">11.2.5</span> Service by an alternative method</h3>
<p><strong>CPR 6.15.</strong> Where there is a <strong>good reason</strong>, the court may authorise service by a method or at a place not otherwise permitted. Under <strong>CPR 6.15(2)</strong> it may also, on the same test, order that steps already taken to bring the claim form to the defendant’s attention are to be treated as good service. The order must specify the method, the <strong>deemed date of service</strong>, and the period for responding.</p>
</section>
<section id="service-out-of-the-jurisdiction" class="level3" data-number="11.2.6">
<h3 data-number="11.2.6" class="anchored" data-anchor-id="service-out-of-the-jurisdiction"><span class="header-section-number">11.2.6</span> Service out of the jurisdiction</h3>
<p>Two routes, and the distinction decides the question:</p>
<p><strong>Without permission</strong> (CPR 6.32–6.33). Available where the English court has power to determine the claim under the Civil Jurisdiction and Judgments Act 1982, where the contract contains a term to the effect that the <strong>English court shall have jurisdiction</strong>, or under the Hague 2005 Convention.</p>
<p><strong>With permission</strong> (CPR 6.36). The claimant must satisfy the <strong>three requirements</strong> set out in <a href="dr-02-preaction.html" class="quarto-xref"><span>Chapter 10</span></a>: a good arguable case within a <strong>PD 6B gateway</strong>, a <strong>serious issue to be tried</strong>, and that <strong>England is the proper place</strong>. The application is made without notice, supported by evidence, and the claimant owes a duty of <strong>full and frank disclosure</strong>.</p>
<p><strong>Mechanics abroad.</strong> Service may be effected through the <strong>foreign government or judicial authority</strong> or the British consular authority (CPR 6.42), through a <strong>Hague Service Convention</strong> channel where the destination state is a party, or by any method <strong>permitted by the law of the country</strong> in which service is to be effected (CPR 6.40(3)) — but <strong>never</strong> by a method that is contrary to that country’s law. The period for responding is extended by PD 6B according to the destination.</p>
</section>
</section>
<section id="statements-of-case" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="statements-of-case"><span class="header-section-number">11.3</span> Statements of case</h2>
<section id="particulars-of-claim" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="particulars-of-claim"><span class="header-section-number">11.3.1</span> Particulars of claim</h3>
<p><strong>CPR 16.4</strong>: a <strong>concise statement of the facts</strong> on which the claimant relies; a claim for <strong>interest</strong> if any, with the basis and, for a specified sum, the percentage rate, the dates from and to which it is claimed and the daily rate; any claim for <strong>aggravated or exemplary damages</strong> or <strong>provisional damages</strong>; and a <strong>statement of truth</strong>.</p>
<p>The particulars must be served with the claim form or <strong>within 14 days</strong> after service of the claim form (CPR 7.4), and in any event within the four-month period for serving the claim form.</p>
<p>The content follows the cause of action:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Contract claim</th>
<th>Tort (negligence) claim</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The status of the parties</td>
<td>The status of the parties</td>
</tr>
<tr class="even">
<td>The <strong>contract</strong>: date, parties, whether written or oral, consideration</td>
<td>The facts giving rise to a <strong>duty of care</strong></td>
</tr>
<tr class="odd">
<td>The <strong>terms</strong> relied on, express or implied</td>
<td>The <strong>duty</strong> owed</td>
</tr>
<tr class="even">
<td><strong>Performance</strong> by the claimant</td>
<td>The acts or omissions constituting <strong>breach</strong></td>
</tr>
<tr class="odd">
<td>The <strong>breach</strong>, with particulars</td>
<td><strong>Causation</strong></td>
</tr>
<tr class="even">
<td><strong>Causation</strong> and <strong>loss</strong>, with a schedule of loss</td>
<td>The <strong>damage</strong>, with a schedule of loss</td>
</tr>
<tr class="odd">
<td>Interest</td>
<td>Interest</td>
</tr>
</tbody>
</table>
</section>
<section id="defence" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="defence"><span class="header-section-number">11.3.2</span> Defence</h3>
<p><strong>CPR 16.5</strong> requires the defendant to state, in relation to <strong>each allegation</strong>, whether it is:</p>
<ul>
<li><strong>denied</strong> — and if so, the defendant must state the <strong>reasons</strong> for the denial and, if putting forward a different version of events, state that version;</li>
<li><strong>admitted</strong>; or</li>
<li><strong>neither admitted nor denied</strong>, because the defendant is unable to admit or deny it and requires the claimant to prove it.</li>
</ul>
<p><strong>Failure to deal with an allegation is a deemed admission</strong> — except that a defendant who fails to deal with an allegation but has set out the nature of their case in relation to the issue is taken to require it to be proved, and a defendant who fails to deal with an allegation about the <strong>amount of money claimed</strong> is taken to require it to be proved. The defence must dispute the claimant’s statement of value if the defendant disputes it, and must give its own.</p>
<p>The defence must also plead any <strong>positive case</strong> and any <strong>limitation</strong> defence, and must be verified by a statement of truth.</p>
</section>
<section id="reply-part-20-claims-and-further-information" class="level3" data-number="11.3.3">
<h3 data-number="11.3.3" class="anchored" data-anchor-id="reply-part-20-claims-and-further-information"><span class="header-section-number">11.3.3</span> Reply, Part 20 claims and further information</h3>
<p><strong>Reply</strong> (CPR 16.7). Optional. A claimant who does not file one is not taken to admit the matters raised in the defence. A reply is needed to answer a positive case in the defence that the particulars of claim do not already address.</p>
<p><strong>Additional claims under Part 20:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Claim</th>
<th>Permission needed?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Counterclaim against the claimant</strong></td>
<td><strong>No</strong>, if filed with the defence; otherwise yes (CPR 20.4)</td>
</tr>
<tr class="even">
<td>Counterclaim against a person <strong>other than</strong> the claimant</td>
<td><strong>Yes</strong> (CPR 20.5)</td>
</tr>
<tr class="odd">
<td>Claim for <strong>contribution or indemnity against a co-defendant</strong></td>
<td><strong>No</strong>, if filed with the defence, or within 28 days of a party being added (CPR 20.6)</td>
</tr>
<tr class="even">
<td>Any <strong>other additional claim</strong> — for example against a third party</td>
<td><strong>No</strong>, if issued <strong>before or at the same time as</strong> the defence is filed; otherwise <strong>yes</strong> (CPR 20.7)</td>
</tr>
</tbody>
</table>
<p>An additional claim is treated as a claim in its own right, and Part 20 applies the ordinary rules to it with modifications.</p>
<p><strong>Further information</strong> (CPR 18). A party may serve a <strong>written request</strong> for clarification of any matter in dispute or additional information about it, giving a date for response. If the other party does not comply, an <strong>application</strong> may be made. The request must be <strong>concise and strictly confined</strong> to what is reasonably necessary and proportionate.</p>
</section>
<section id="amendments" class="level3" data-number="11.3.4">
<h3 data-number="11.3.4" class="anchored" data-anchor-id="amendments"><span class="header-section-number">11.3.4</span> Amendments</h3>
<p><strong>CPR 17.1</strong>: a party may amend a statement of case <strong>at any time before it has been served</strong> on any other party. After service, amendment requires the <strong>written consent of all the other parties</strong> or the <strong>permission of the court</strong>.</p>
<p><strong>CPR 17.4 — amendment after limitation has expired.</strong> Where the relevant limitation period was current when the proceedings started, the court may allow an amendment only:</p>
<ul>
<li>to add or substitute a <strong>new claim</strong> arising out of <strong>the same facts or substantially the same facts</strong> as a claim already made; or</li>
<li>to correct a <strong>mistake as to the name of a party</strong>, where the mistake was <strong>genuine</strong> and not one which would cause reasonable doubt as to the identity of the party; or</li>
<li>to <strong>alter the capacity</strong> in which a party claims.</li>
</ul>
<p>The court will also consider whether the amendment is in accordance with the overriding objective — lateness, the effect on the trial date and the costs consequences all bear on the discretion.</p>
</section>
<section id="the-statement-of-truth" class="level3" data-number="11.3.5">
<h3 data-number="11.3.5" class="anchored" data-anchor-id="the-statement-of-truth"><span class="header-section-number">11.3.5</span> The statement of truth</h3>
<p>Every statement of case must be verified by a statement of truth. Since April 2020 the prescribed wording is:</p>
<blockquote class="blockquote">
<p>I believe that the facts stated in this [document] are true. I understand that proceedings for contempt of court may be brought against anyone who makes, or causes to be made, a false statement in a document verified by a statement of truth without an honest belief in its truth.</p>
</blockquote>
<p>It may be signed by the party, by a person with authority (for a company, a person holding a senior position, who must state which), or by the party’s legal representative — who signs on the party’s behalf and must have the party’s authority and have explained the consequences.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>A solicitor may sign a statement of truth on the client’s behalf, but may <strong>never</strong> verify a statement the solicitor knows or believes to be false. Where the client insists on advancing an account the solicitor knows to be untrue, the solicitor must not draft or sign it, and will usually have to <strong>cease to act</strong> — without disclosing the reason, because the reason is confidential.</p>
</div>
</div>
</section>
</section>
<section id="responding-to-a-claim" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="responding-to-a-claim"><span class="header-section-number">11.4</span> Responding to a claim</h2>
<section id="the-time-limits" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="the-time-limits"><span class="header-section-number">11.4.1</span> The time limits</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>Time limit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Acknowledgment of service</strong></td>
<td><strong>14 days</strong> after service of the particulars of claim (CPR 10.3)</td>
</tr>
<tr class="even">
<td><strong>Defence</strong>, where no acknowledgment filed</td>
<td><strong>14 days</strong> after service of the particulars of claim (CPR 15.4)</td>
</tr>
<tr class="odd">
<td><strong>Defence</strong>, where an acknowledgment has been filed</td>
<td><strong>28 days</strong> after service of the particulars of claim</td>
</tr>
<tr class="even">
<td><strong>Agreed extension</strong> of the defence</td>
<td>Up to a further <strong>28 days</strong>, by agreement, notifying the court in writing (CPR 15.5) — so a maximum of <strong>56 days</strong> without a court order</td>
</tr>
<tr class="odd">
<td><strong>Application disputing jurisdiction</strong></td>
<td><strong>14 days</strong> after filing the acknowledgment of service (CPR 11)</td>
</tr>
</tbody>
</table>
</section>
<section id="the-options" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="the-options"><span class="header-section-number">11.4.2</span> The options</h3>
<p><strong>Admit</strong> (Part 14). The defendant may admit the whole or part of the claim. For a <strong>specified</strong> sum, the claimant may then obtain judgment; the defendant may ask for time to pay, and the rate of payment is determined by the court or by agreement.</p>
<p><strong>Defend.</strong> File an acknowledgment of service and/or a defence, and consider a counterclaim.</p>
<p><strong>Dispute the court’s jurisdiction</strong> (Part 11). The defendant must <strong>first file an acknowledgment of service</strong> — filing one is not a submission to the jurisdiction — and then apply <strong>within 14 days</strong>. If the defendant files a <strong>defence</strong> without applying, they are <strong>treated as having accepted</strong> that the court has jurisdiction.</p>
<p><strong>Do nothing</strong> — and face default judgment.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Exam trap">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exam trap
</div>
</div>
<div class="callout-body-container callout-body">
<p>To challenge jurisdiction, the defendant must <strong>acknowledge service and then apply within 14 days</strong>. Doing nothing loses the point (default judgment follows) and filing a defence loses it too (submission). The acknowledgment of service form has a tick box for “I intend to contest jurisdiction” precisely for this purpose.</p>
</div>
</div>
</section>
<section id="default-judgment" class="level3" data-number="11.4.3">
<h3 data-number="11.4.3" class="anchored" data-anchor-id="default-judgment"><span class="header-section-number">11.4.3</span> Default judgment</h3>
<p><strong>Part 12.</strong> The claimant may obtain judgment in default where the defendant has failed to file an acknowledgment of service <strong>or</strong> a defence, and the time for doing so has expired. It is entered administratively on request for a specified sum, and on application otherwise.</p>
<p>Default judgment is <strong>not</strong> available where:</p>
<ul>
<li>the claim is under <strong>Part 8</strong>;</li>
<li>the defendant has applied for <strong>summary judgment</strong> or to have the claim <strong>struck out</strong>, and the application has not been disposed of;</li>
<li>the defendant has <strong>satisfied</strong> the claim; or</li>
<li>the defendant has <strong>admitted</strong> the claim and applied for time to pay.</li>
</ul>
<p><strong>Setting aside</strong> (Part 13):</p>
<ul>
<li><strong>CPR 13.2 — mandatory.</strong> The court <strong>must</strong> set the judgment aside if it was <strong>wrongly entered</strong> — because the time for responding had not in fact expired, or the claim had been satisfied, or the defendant had filed an acknowledgment or defence in time.</li>
<li><strong>CPR 13.3 — discretionary.</strong> The court <strong>may</strong> set it aside if the defendant has a <strong>real prospect of successfully defending</strong> the claim, or if it appears to the court that there is <strong>some other good reason</strong> why the judgment should be set aside or the defendant should be allowed to defend. On any such application the court <strong>must have regard to whether the application was made promptly</strong>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Worked example">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Worked example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Particulars of claim are deemed served on 1 October. The defendant, who has been abroad, files nothing. On 20 October the claimant enters default judgment. The defendant returns on 5 November, and applies to set the judgment aside on 20 December, saying the goods were defective.</p>
<p><strong>Was the judgment properly entered?</strong> The defence was due by 15 October and nothing was filed, so yes. CPR 13.2 does not apply.</p>
<p><strong>Will it be set aside?</strong> Only under CPR 13.3, and the defendant must show a real prospect of successfully defending — a defective goods defence may well qualify. But the court <strong>must have regard to promptness</strong>, and a six-week delay after returning is a serious obstacle. On these facts the application may fail on delay alone, and if it succeeds the defendant will almost certainly bear the costs thrown away.</p>
</div>
</div>
</section>
<section id="discontinuance-and-settlement" class="level3" data-number="11.4.4">
<h3 data-number="11.4.4" class="anchored" data-anchor-id="discontinuance-and-settlement"><span class="header-section-number">11.4.4</span> Discontinuance and settlement</h3>
<p><strong>Discontinuance</strong> (Part 38). The claimant may discontinue at any time by filing and serving a <strong>notice of discontinuance</strong>. Permission is required where the court has granted an <strong>interim injunction</strong> or where any party has given an <strong>undertaking</strong> to the court, or where the claimant has received an <strong>interim payment</strong>. Where there is more than one claimant, the consent of the others or the court’s permission is needed. Unless the court orders otherwise, the claimant is <strong>liable for the defendant’s costs</strong> to the date of discontinuance (CPR 38.6).</p>
<p><strong>Settlement</strong> may be recorded by:</p>
<ul>
<li>a <strong>consent order</strong>, where the terms are to be enforceable as an order of the court and there is nothing confidential;</li>
<li>a <strong>Tomlin order</strong> — an order <strong>staying</strong> the proceedings on agreed terms set out in a <strong>schedule</strong>, with permission to apply for the purpose of carrying those terms into effect. The schedule is not part of the order and need not be a matter of public record, which is why it is used where the terms are confidential or go beyond what the court could order;</li>
<li>acceptance of a <strong>Part 36 offer</strong>, which stays the claim automatically; or</li>
<li>a simple <strong>settlement agreement</strong>, with the claim then discontinued.</li>
</ul>
</section>
</section>
<section id="check-yourself" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="check-yourself"><span class="header-section-number">11.5</span> Check yourself</h2>
<p><strong>Q1.</strong> A claim form is issued on 3 March. On 30 June the claimant’s solicitor posts it to the defendant’s solicitors, who are authorised in writing to accept service, by first class post. It arrives on 2 July.</p>
<p>Which of the following is correct?</p>
<p>A. Service is out of time, because the claim form was not received by the defendant’s solicitors within four months of issue.</p>
<p>B. Service is in time: the step required for postal service is posting, which was completed on 30 June, within four months of issue; the claim form is deemed served on the second business day after posting.</p>
<p>C. Service is in time, and the claim form is deemed served on the day it arrived, 2 July.</p>
<p>D. Service is out of time, because service on solicitors is not permitted.</p>
<p>E. Service is in time, and the claim form is deemed served on the day it was posted, 30 June.</p>
<p><strong>Q2.</strong> Particulars of claim are deemed served on a defendant on Tuesday 6 October. The defendant files an acknowledgment of service on 15 October, indicating an intention to defend.</p>
<p>By when must the defence be filed, assuming no agreement or order extending time?</p>
<p>A. 20 October, being 14 days after the acknowledgment of service.</p>
<p>B. 20 October, being 14 days after service of the particulars of claim.</p>
<p>C. 3 November, being 28 days after service of the particulars of claim.</p>
<p>D. 12 November, being 28 days after the acknowledgment of service.</p>
<p>E. 1 December, being 56 days after service of the particulars of claim.</p>
<p><strong>Q3.</strong> A claimant sued “Northgate Logistics Limited”. The contracting party was in fact “Northgate Logistics (UK) Limited”, a different company in the same group with a similar name. The limitation period expired two months after the claim form was issued. The claimant now applies to substitute the correct company.</p>
<p>Which of the following is correct?</p>
<p>A. The application must be refused, because the limitation period has expired.</p>
<p>B. The application may be granted under CPR 19.6 if the limitation period was current when the proceedings were started and the substitution is necessary — which it is where the new party is being substituted for a party named in the claim form by mistake for the new party.</p>
<p>C. The application may be granted as of right, because the claim form has not yet been amended.</p>
<p>D. The application must be refused, because the claimant chose to sue a different legal person and that is not a mistake as to name.</p>
<p>E. The claimant must issue fresh proceedings and rely on s.33 of the Limitation Act 1980.</p>
<p><strong>Q4.</strong> A defendant based in Germany is served with an English claim form. The defendant believes the English court has no jurisdiction because the contract contains an exclusive German jurisdiction clause.</p>
<p>What must the defendant do to preserve the point?</p>
<p>A. File a defence setting out the jurisdiction objection.</p>
<p>B. Write to the court explaining that it does not accept jurisdiction, and take no further step.</p>
<p>C. File an acknowledgment of service indicating an intention to contest jurisdiction, and apply under Part 11 within 14 days after filing it.</p>
<p>D. Apply for summary judgment under Part 24.</p>
<p>E. Ignore the proceedings, because a foreign defendant cannot be bound by an English judgment.</p>
<p><strong>Q5.</strong> A defendant, having filed a defence, wishes to bring a claim for an indemnity against a sub-contractor who is not a party to the proceedings. The defence was filed three weeks ago.</p>
<p>Which of the following is correct?</p>
<p>A. The defendant may issue the additional claim without permission at any time.</p>
<p>B. The defendant requires the court’s permission, because the additional claim was not issued before or at the same time as the defence was filed.</p>
<p>C. The defendant may only bring the claim in separate proceedings.</p>
<p>D. The defendant requires the consent of the claimant.</p>
<p>E. The defendant may issue the additional claim without permission because it is a claim for an indemnity.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Answers and explanations">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Answers and explanations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Q1 — B.</strong> CPR 7.5(1): the claimant must complete the <strong>step required</strong> within four months of issue, and for first class post that step is <strong>posting</strong>. Posting on 30 June, from a claim form issued on 3 March, is within four months. Deemed service under CPR 6.14 is the <strong>second business day</strong> after completion of the step, regardless of actual delivery.</p>
<ul>
<li><strong>A</strong> and <strong>D</strong> apply the wrong test: what matters is the step, not receipt, and CPR 6.7 requires service on a solicitor authorised in writing to accept it.</li>
<li><strong>C</strong> applies the actual date of delivery. CPR 6.14 is a deeming provision and the real date is irrelevant.</li>
<li><strong>E</strong> deems service on the day of the step, which is what CPR 6.14 expressly does not do.</li>
</ul>
<p><strong>Q2 — C.</strong> CPR 15.4(1)(b): where the defendant files an acknowledgment of service, the defence must be filed <strong>28 days after service of the particulars of claim</strong> — not 28 days after the acknowledgment. Twenty-eight days from 6 October is 3 November.</p>
<ul>
<li><strong>A</strong> and <strong>D</strong> run time from the acknowledgment, which is the classic error.</li>
<li><strong>B</strong> applies the 14-day period that operates only where no acknowledgment is filed.</li>
<li><strong>E</strong> applies the maximum available <strong>with</strong> an agreed extension under CPR 15.5, which the facts exclude.</li>
</ul>
<p><strong>Q3 — B.</strong> CPR 19.6. The limitation period was current when the proceedings were started, and substitution is “necessary” under CPR 19.6(3)(a) where the new party is to be substituted for a party named in the claim form <strong>by mistake</strong> for the new party. Suing the wrong company in a group because of a similar name is a classic mistake as to identity of this kind, provided the mistake was genuine and would not cause reasonable doubt as to who was intended.</p>
<ul>
<li><strong>A</strong> treats the expiry of limitation as an absolute bar, which CPR 19.6 exists to qualify.</li>
<li><strong>C</strong> ignores the need for permission after service and the special rule after limitation.</li>
<li><strong>D</strong> is the strongest distractor, and would be right if the claimant had deliberately sued one legal person and later changed its mind. Here the intention was always to sue the contracting party.</li>
<li><strong>E</strong> applies s.33, which is available only in personal injury and fatal accident claims.</li>
</ul>
<p><strong>Q4 — C.</strong> CPR Part 11. The defendant must file an <strong>acknowledgment of service</strong> — which is not a submission to the jurisdiction — and then apply for an order declaring that the court has no jurisdiction, or should not exercise it, <strong>within 14 days</strong> after filing the acknowledgment.</p>
<ul>
<li><strong>A</strong> is fatal: filing a defence without making the application means the defendant is <strong>treated as having accepted</strong> that the court has jurisdiction.</li>
<li><strong>B</strong> and <strong>E</strong> invite default judgment.</li>
<li><strong>D</strong> attacks the merits, not the forum, and engaging with the merits risks submission.</li>
</ul>
<p><strong>Q5 — B.</strong> CPR 20.7(3): an additional claim other than a counterclaim against the claimant or a claim for contribution or indemnity <strong>against an existing co-defendant</strong> may be made without permission only if it is issued <strong>before or at the same time as</strong> the defendant files their defence. The defence was filed three weeks ago, so permission is required.</p>
<ul>
<li><strong>A</strong> and <strong>E</strong> overlook the timing condition. Note the distinction being tested: CPR 20.6 allows a contribution or indemnity claim against an <strong>existing co-defendant</strong> without permission if filed with the defence; this sub-contractor is <strong>not yet a party</strong>, so CPR 20.7 applies.</li>
<li><strong>C</strong> is wrong: Part 20 exists so that related claims can be tried together.</li>
<li><strong>D</strong> requires a consent the rules do not call for.</li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../flk1/dr-02-preaction.html" class="pagination-link" aria-label="Before proceedings">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Before proceedings</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../flk1/dr-04-case-management.html" class="pagination-link" aria-label="Running the claim">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Running the claim</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>