baseurl: '/'
permalink: pretty
title: 'Mehman Ismayilli'


collections:
  services:
    output: false
    sort_by: weight
  team:
    output: false

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
