<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Extreme Values, Quantiles, and Value at Risk – Time Series Analysis in Financial Econometrics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/14-options.html" rel="next">
<link href="../chapters/11-garch-est.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c94efcbe7087408ea84692b584c735f1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-fca680cf785cbab9ed9b1a0a99de9537.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-c94efcbe7087408ea84692b584c735f1.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/15-extreme-values.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Extreme Values, Quantiles, and Value at Risk</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Time Series Analysis in Financial Econometrics</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-returns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Asset Returns: Simple and Log</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Distributional Properties of Returns</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-linear-ts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Time Series Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-ma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Moving-Average Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-arma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">ARMA Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-unit-root.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Unit-Root Nonstationarity</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-arima.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ARIMA Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-arch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">ARCH Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-garch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">GARCH Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-garch-est.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating and Evaluating Volatility Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15-extreme-values.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Extreme Values, Quantiles, and Value at Risk</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14-options.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Options: Contracts, Payoffs, and the Greeks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13-continuous-time.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Continuous-Time Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Nonlinear Models</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-evt-var" id="toc-sec-evt-var" class="nav-link active" data-scroll-target="#sec-evt-var"><span class="header-section-number">11.1</span> What is Value at Risk?</a>
  <ul class="collapse">
  <li><a href="#sec-evt-roadmap" id="toc-sec-evt-roadmap" class="nav-link" data-scroll-target="#sec-evt-roadmap"><span class="header-section-number">11.1.1</span> A map of the four methods</a></li>
  </ul></li>
  <li><a href="#sec-evt-rm" id="toc-sec-evt-rm" class="nav-link" data-scroll-target="#sec-evt-rm"><span class="header-section-number">11.2</span> RiskMetrics</a>
  <ul class="collapse">
  <li><a href="#sec-evt-rm-what" id="toc-sec-evt-rm-what" class="nav-link" data-scroll-target="#sec-evt-rm-what"><span class="header-section-number">11.2.1</span> What is RiskMetrics?</a></li>
  <li><a href="#sec-evt-rm-multi" id="toc-sec-evt-rm-multi" class="nav-link" data-scroll-target="#sec-evt-rm-multi"><span class="header-section-number">11.2.2</span> Multiple positions</a></li>
  <li><a href="#sec-evt-rm-es" id="toc-sec-evt-rm-es" class="nav-link" data-scroll-target="#sec-evt-rm-es"><span class="header-section-number">11.2.3</span> Expected Shortfall</a></li>
  </ul></li>
  <li><a href="#sec-evt-econ" id="toc-sec-evt-econ" class="nav-link" data-scroll-target="#sec-evt-econ"><span class="header-section-number">11.3</span> An econometric approach to VaR</a>
  <ul class="collapse">
  <li><a href="#sec-evt-econ-multi" id="toc-sec-evt-econ-multi" class="nav-link" data-scroll-target="#sec-evt-econ-multi"><span class="header-section-number">11.3.1</span> Multiple periods</a></li>
  <li><a href="#sec-evt-econ-es" id="toc-sec-evt-econ-es" class="nav-link" data-scroll-target="#sec-evt-econ-es"><span class="header-section-number">11.3.2</span> Expected shortfall under conditional normality</a></li>
  </ul></li>
  <li><a href="#sec-evt-quantile" id="toc-sec-evt-quantile" class="nav-link" data-scroll-target="#sec-evt-quantile"><span class="header-section-number">11.4</span> Quantile estimation</a>
  <ul class="collapse">
  <li><a href="#sec-evt-orderstat" id="toc-sec-evt-orderstat" class="nav-link" data-scroll-target="#sec-evt-orderstat"><span class="header-section-number">11.4.1</span> Quantiles and order statistics</a></li>
  <li><a href="#sec-evt-qreg" id="toc-sec-evt-qreg" class="nav-link" data-scroll-target="#sec-evt-qreg"><span class="header-section-number">11.4.2</span> Quantile regression</a></li>
  </ul></li>
  <li><a href="#sec-evt-theory" id="toc-sec-evt-theory" class="nav-link" data-scroll-target="#sec-evt-theory"><span class="header-section-number">11.5</span> Extreme value theory</a>
  <ul class="collapse">
  <li><a href="#sec-evt-review" id="toc-sec-evt-review" class="nav-link" data-scroll-target="#sec-evt-review"><span class="header-section-number">11.5.1</span> A review of extreme value theory</a></li>
  <li><a href="#sec-evt-empirical" id="toc-sec-evt-empirical" class="nav-link" data-scroll-target="#sec-evt-empirical"><span class="header-section-number">11.5.2</span> Empirical estimation</a></li>
  <li><a href="#sec-evt-application" id="toc-sec-evt-application" class="nav-link" data-scroll-target="#sec-evt-application"><span class="header-section-number">11.5.3</span> Application to stock returns</a></li>
  </ul></li>
  <li><a href="#sec-evt-var-block" id="toc-sec-evt-var-block" class="nav-link" data-scroll-target="#sec-evt-var-block"><span class="header-section-number">11.6</span> An extreme-value approach to VaR</a>
  <ul class="collapse">
  <li><a href="#sec-evt-var-disc" id="toc-sec-evt-var-disc" class="nav-link" data-scroll-target="#sec-evt-var-disc"><span class="header-section-number">11.6.1</span> Discussion</a></li>
  <li><a href="#sec-evt-multi" id="toc-sec-evt-multi" class="nav-link" data-scroll-target="#sec-evt-multi"><span class="header-section-number">11.6.2</span> Multiperiod VaR</a></li>
  <li><a href="#sec-evt-return" id="toc-sec-evt-return" class="nav-link" data-scroll-target="#sec-evt-return"><span class="header-section-number">11.6.3</span> Return levels</a></li>
  </ul></li>
  <li><a href="#sec-evt-pot" id="toc-sec-evt-pot" class="nav-link" data-scroll-target="#sec-evt-pot"><span class="header-section-number">11.7</span> A modern approach: peaks over threshold</a>
  <ul class="collapse">
  <li><a href="#sec-evt-pot-theory" id="toc-sec-evt-pot-theory" class="nav-link" data-scroll-target="#sec-evt-pot-theory"><span class="header-section-number">11.7.1</span> Statistical theory</a></li>
  <li><a href="#sec-evt-me" id="toc-sec-evt-me" class="nav-link" data-scroll-target="#sec-evt-me"><span class="header-section-number">11.7.2</span> The mean-excess function</a></li>
  <li><a href="#sec-evt-pot-fit" id="toc-sec-evt-pot-fit" class="nav-link" data-scroll-target="#sec-evt-pot-fit"><span class="header-section-number">11.7.3</span> Modelling the extreme values</a></li>
  <li><a href="#sec-evt-pot-var" id="toc-sec-evt-pot-var" class="nav-link" data-scroll-target="#sec-evt-pot-var"><span class="header-section-number">11.7.4</span> VaR from the POT approach</a></li>
  <li><a href="#sec-evt-pot-covariates" id="toc-sec-evt-pot-covariates" class="nav-link" data-scroll-target="#sec-evt-pot-covariates"><span class="header-section-number">11.7.5</span> Using explanatory variables</a></li>
  <li><a href="#sec-evt-illustration" id="toc-sec-evt-illustration" class="nav-link" data-scroll-target="#sec-evt-illustration"><span class="header-section-number">11.7.6</span> A general illustration</a></li>
  </ul></li>
  <li><a href="#sec-evt-extremal" id="toc-sec-evt-extremal" class="nav-link" data-scroll-target="#sec-evt-extremal"><span class="header-section-number">11.8</span> The extremal index: when extremes cluster</a>
  <ul class="collapse">
  <li><a href="#sec-evt-dun" id="toc-sec-evt-dun" class="nav-link" data-scroll-target="#sec-evt-dun"><span class="header-section-number">11.8.1</span> The D(<span class="math inline">\(u_n\)</span>) condition</a></li>
  <li><a href="#sec-evt-theta-est" id="toc-sec-evt-theta-est" class="nav-link" data-scroll-target="#sec-evt-theta-est"><span class="header-section-number">11.8.2</span> Estimating the extremal index</a></li>
  <li><a href="#sec-evt-var-stationary" id="toc-sec-evt-var-stationary" class="nav-link" data-scroll-target="#sec-evt-var-stationary"><span class="header-section-number">11.8.3</span> Value at Risk for a stationary time series</a></li>
  </ul></li>
  <li><a href="#sec-evt-concept" id="toc-sec-evt-concept" class="nav-link" data-scroll-target="#sec-evt-concept"><span class="header-section-number">11.9</span> Concept check</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-evt" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Extreme Values, Quantiles, and Value at Risk</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The whole book has repeated one fact: financial returns are <strong>fat-tailed</strong>. This chapter is where that fact is finally turned into a <strong>risk number</strong>. We define <strong>Value at Risk (VaR)</strong>, compute it four ways — RiskMetrics, an econometric (GARCH) approach, empirical quantiles, and <strong>Extreme Value Theory (EVT)</strong> — and see, starkly, how badly the Normal-based numbers understate the danger in the deep tail. The chapter’s own tail-fit figure (<a href="#fig-evt-tailfit" class="quarto-xref">Figure&nbsp;<span>11.4</span></a>) tells the story in advance: the Normal curve plunges <em>ten orders of magnitude</em> below where the S&amp;P’s real losses actually sit.</p>
<section id="sec-evt-var" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="sec-evt-var"><span class="header-section-number">11.1</span> What is Value at Risk?</h2>
<div class="definition">
<p><strong>Value at Risk (VaR)</strong> at level <span class="math inline">\(p\)</span> over a horizon <span class="math inline">\(h\)</span> is the loss that will be exceeded with probability <span class="math inline">\(p\)</span>. A 1-day 99% VaR of $1m means: on 99 days out of 100 the loss stays under $1m; on the 100th it may be worse.</p>
</div>
<p>Formally, if <span class="math inline">\(L\)</span> is the loss over the horizon, <span class="math inline">\(\text{VaR}_p\)</span> is the number with <span class="math inline">\(P(L &gt; \text{VaR}_p) = p\)</span> — the upper <span class="math inline">\(p\)</span>-quantile of the loss distribution. Three ingredients are needed: the <strong>horizon</strong> (1 day, 10 days), the <strong>confidence</strong> (<span class="math inline">\(p =
1\%\)</span> or <span class="math inline">\(5\%\)</span>), and an estimate of the <strong>loss distribution</strong>. The methods of this chapter differ only in that last ingredient.</p>
<p>The simplest estimate is <strong>historical</strong> — the empirical quantile of past losses — and comparing it to the <strong>Normal</strong> estimate already exposes the problem:</p>
<div id="tbl-evt-var" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-evt-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.1: 1-day VaR and Expected Shortfall, historical vs Normal (as % loss)
</figcaption>
<div aria-describedby="tbl-evt-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Ticker</th>
<th style="text-align: center;">Hist VaR 5%</th>
<th style="text-align: center;">Normal 5%</th>
<th style="text-align: center;">Hist VaR 1%</th>
<th style="text-align: center;">Normal 1%</th>
<th style="text-align: center;">Hist ES 1%</th>
<th style="text-align: center;">Normal ES 1%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AAPL</td>
<td style="text-align: center;">2.71%</td>
<td style="text-align: center;">2.85%</td>
<td style="text-align: center;"><strong>4.92%</strong></td>
<td style="text-align: center;">4.07%</td>
<td style="text-align: center;"><strong>6.80%</strong></td>
<td style="text-align: center;">4.68%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MSFT</td>
<td style="text-align: center;">2.54%</td>
<td style="text-align: center;">2.64%</td>
<td style="text-align: center;"><strong>4.28%</strong></td>
<td style="text-align: center;">3.77%</td>
<td style="text-align: center;"><strong>6.19%</strong></td>
<td style="text-align: center;">4.33%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AMZN</td>
<td style="text-align: center;">3.11%</td>
<td style="text-align: center;">3.32%</td>
<td style="text-align: center;"><strong>5.69%</strong></td>
<td style="text-align: center;">4.73%</td>
<td style="text-align: center;"><strong>7.82%</strong></td>
<td style="text-align: center;">5.43%</td>
</tr>
<tr class="even">
<td style="text-align: left;">SPX</td>
<td style="text-align: center;">1.65%</td>
<td style="text-align: center;">1.75%</td>
<td style="text-align: center;"><strong>3.17%</strong></td>
<td style="text-align: center;">2.50%</td>
<td style="text-align: center;"><strong>4.63%</strong></td>
<td style="text-align: center;">2.87%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GLD</td>
<td style="text-align: center;">1.67%</td>
<td style="text-align: center;">1.72%</td>
<td style="text-align: center;"><strong>3.03%</strong></td>
<td style="text-align: center;">2.44%</td>
<td style="text-align: center;"><strong>4.26%</strong></td>
<td style="text-align: center;">2.80%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCF</td>
<td style="text-align: center;">1.69%</td>
<td style="text-align: center;">1.76%</td>
<td style="text-align: center;"><strong>3.10%</strong></td>
<td style="text-align: center;">2.51%</td>
<td style="text-align: center;"><strong>4.49%</strong></td>
<td style="text-align: center;">2.88%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>At the <span class="math inline">\(5\%\)</span> level the two agree; the Normal is even a touch <em>higher</em>. But at the <span class="math inline">\(1\%\)</span> level the historical VaR pulls decisively ahead — the S&amp;P’s real 1% loss is <span class="math inline">\(3.17\%\)</span> against the Normal’s <span class="math inline">\(2.50\%\)</span> — and the <strong>Expected Shortfall</strong> (defined below) diverges far more. The deeper into the tail we look, the worse the Normal does. VaR itself has a known flaw, which motivates that Expected Shortfall column: it says nothing about <em>how bad</em> losses beyond it can be.</p>
<p>The mismatch is easiest to <em>see</em>. <a href="#fig-evt-histnorm" class="quarto-xref">Figure&nbsp;<span>11.1</span></a> plots the S&amp;P’s daily returns against a normal with the <em>same</em> mean and standard deviation: identical spread, but the wrong <strong>shape</strong> — a taller, thinner peak and far too little mass in the tail. The right panel magnifies the left tail, where the normal’s <span class="math inline">\(1\%\)</span> VaR (<span class="math inline">\(2.50\%\)</span>) sits <em>inside</em> the true <span class="math inline">\(1\%\)</span> loss (<span class="math inline">\(3.17\%\)</span>): the real loss days beyond it are exactly the ones the bell curve treats as all but impossible.</p>
<div id="fig-evt-histnorm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evt-histnorm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/evt_hist_normal.png" class="img-fluid figure-img" style="width:95.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evt-histnorm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: S&amp;P 500 daily returns vs.&nbsp;a fitted normal with the same mean and variance. <strong>Left:</strong> the return histogram has a taller peak and fatter tails than the normal bell. <strong>Right:</strong> the left tail magnified — real loss days pile up beyond where the normal density has effectively vanished, and the historical 1% VaR (3.17%) lies further out than the normal 1% VaR (2.50%). Same volatility, wrong tail shape.
</figcaption>
</figure>
</div>
<p>The same diagnostic for <strong>every series</strong> tells the same story — each is fat-tailed, and its historical <span class="math inline">\(1\%\)</span> VaR sits outside the normal’s. Flip through the tabs:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">AAPL</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">MSFT</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">AMZN</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">SPX</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">GLD</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false">GCF</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/evt_hist_normal_AAPL.png" class="img-fluid figure-img"></p>
<figcaption>Apple: fat peak, fat tails; historical 1% VaR 4.92% vs.&nbsp;normal 4.07%.</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/evt_hist_normal_MSFT.png" class="img-fluid figure-img"></p>
<figcaption>Microsoft: historical 1% VaR 4.28% vs.&nbsp;normal 3.77%.</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/evt_hist_normal_AMZN.png" class="img-fluid figure-img"></p>
<figcaption>Amazon: the widest series; historical 1% VaR 5.69% vs.&nbsp;normal 4.73%.</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/evt_hist_normal_SPX.png" class="img-fluid figure-img"></p>
<figcaption>S&amp;P 500: the most leptokurtic (excess kurtosis ≈ 14); historical 1% VaR 3.17% vs.&nbsp;normal 2.50%.</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/evt_hist_normal_GLD.png" class="img-fluid figure-img"></p>
<figcaption>Gold ETF: historical 1% VaR 3.03% vs.&nbsp;normal 2.44%.</figcaption>
</figure>
</div>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/evt_hist_normal_GCF.png" class="img-fluid figure-img"></p>
<figcaption>Gold futures: historical 1% VaR 3.10% vs.&nbsp;normal 2.51%.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>Across all six, the gap between the historical and normal 1% VaR is the same lesson in six different magnitudes: <a href="#fig-evt-histnormgrid" class="quarto-xref">Figure&nbsp;<span>11.2</span></a> lines them up side by side.</p>
<div id="fig-evt-histnormgrid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evt-histnormgrid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/evt_hist_normal_grid.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evt-histnormgrid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.2: Every series against a same-moment normal (red). All six show a taller peak and heavier tails; the excess kurtosis and the historical-vs-normal 1% VaR are annotated in each panel.
</figcaption>
</figure>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">log</span>(<span class="fu">read.csv</span>(<span class="st">"data/SPX.csv"</span>)<span class="sc">$</span>Adjusted))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>hist_var <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">quantile</span>(r, <span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.01</span>))                 <span class="co"># historical VaR</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>norm_var <span class="ot">&lt;-</span> <span class="sc">-</span>(<span class="fu">mean</span>(r) <span class="sc">+</span> <span class="fu">qnorm</span>(<span class="fu">c</span>(<span class="fl">0.05</span>, <span class="fl">0.01</span>)) <span class="sc">*</span> <span class="fu">sd</span>(r))   <span class="co"># Normal VaR</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>es_1     <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">mean</span>(r[r <span class="sc">&lt;=</span> <span class="fu">quantile</span>(r, <span class="fl">0.01</span>)])            <span class="co"># historical Expected Shortfall</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd, numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> np.log(pd.read_csv(<span class="st">"data/SPX.csv"</span>)[<span class="st">"Adjusted"</span>]).diff().dropna()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>hist_var <span class="op">=</span> <span class="op">-</span>r.quantile([<span class="fl">0.05</span>, <span class="fl">0.01</span>])                    <span class="co"># historical VaR</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>norm_var <span class="op">=</span> <span class="op">-</span>(r.mean() <span class="op">+</span> norm.ppf([<span class="fl">0.05</span>, <span class="fl">0.01</span>]) <span class="op">*</span> r.std())   <span class="co"># Normal VaR</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>es_1     <span class="op">=</span> <span class="op">-</span>r[r <span class="op">&lt;=</span> r.quantile(<span class="fl">0.01</span>)].mean()             <span class="co"># historical Expected Shortfall</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="sec-evt-roadmap" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="sec-evt-roadmap"><span class="header-section-number">11.1.1</span> A map of the four methods</h3>
<p>Historical and Normal are the two crudest estimates, and beyond thin tails they share a deeper limitation: both are <strong>static</strong>. Each collapses the entire sample into a single unconditional number and so ignores the fact this book keeps returning to — volatility clusters, so the risk that matters is <em>today’s</em>, not the fifteen-year average. The rest of the chapter estimates the loss distribution more carefully, and it is easiest to read as a chain in which each method repairs a specific flaw in the one before it:</p>
<ul>
<li><strong>RiskMetrics</strong> makes the volatility time-varying, so the number breathes with the market — but it keeps the normal assumption.</li>
<li>The <strong>econometric (GARCH)</strong> approach fixes RiskMetrics’ two remaining faults: its forced unit persistence and its thin tail.</li>
<li><strong>Quantile methods</strong> stop modelling volatility altogether and target the single object every method is really after — a quantile of the loss distribution.</li>
<li><strong>Extreme Value Theory</strong> models the <em>shape</em> of the tail itself, the one region where every data-based method eventually runs out of observations.</li>
</ul>
<p>We take them in that order, and each section states what it fixes and what it still leaves open.</p>
</section>
</section>
<section id="sec-evt-rm" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="sec-evt-rm"><span class="header-section-number">11.2</span> RiskMetrics</h2>
<section id="sec-evt-rm-what" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="sec-evt-rm-what"><span class="header-section-number">11.2.1</span> What is RiskMetrics?</h3>
<p>The smallest possible improvement over the static picture is to stop treating volatility as a constant. RiskMetrics does exactly that, and little more.</p>
<div class="definition">
<p><strong>RiskMetrics</strong> (J.P. Morgan, 1990s) is a simple, industry-standard VaR method: model volatility with an <strong>exponentially weighted moving average (EWMA)</strong> and assume conditionally normal returns.</p>
</div>
<p>The volatility recursion is</p>
<p><span id="eq-ewma"><span class="math display">\[
\sigma_t^2 = \lambda\, \sigma_{t-1}^2 + (1-\lambda)\, a_{t-1}^2,
\qquad \lambda = 0.94 \text{ (daily)},
\tag{11.1}\]</span></span></p>
<p>which is exactly a GARCH(1,1) with <span class="math inline">\(\alpha_0 = 0\)</span>, <span class="math inline">\(\alpha_1 = 1-\lambda\)</span>, <span class="math inline">\(\beta_1 =
\lambda\)</span> — an <strong>IGARCH</strong> with persistence <span class="math inline">\(\alpha_1+\beta_1 = 1\)</span> (<a href="13-continuous-time.html" class="quarto-xref"><span>Chapter 13</span></a> touched on integrated variance). Today’s variance is a decaying weighted average of all past squared returns, most weight on the recent ones. The VaR is then just a Normal quantile of today’s volatility, <span class="math inline">\(\text{VaR}_p = -z_p\,\sigma_t\)</span> (the drift is ignored over short horizons). For our tickers the current one-day <span class="math inline">\(99\%\)</span> figure is:</p>
<div id="tbl-evt-rm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-evt-rm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.2: RiskMetrics (EWMA, λ = 0.94) one-day 99% VaR
</figcaption>
<div aria-describedby="tbl-evt-rm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Ticker</th>
<th style="text-align: center;">EWMA <span class="math inline">\(\sigma_T\)</span></th>
<th style="text-align: center;">RiskMetrics 99% VaR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AAPL</td>
<td style="text-align: center;">2.11%</td>
<td style="text-align: center;">4.92%</td>
</tr>
<tr class="even">
<td style="text-align: left;">MSFT</td>
<td style="text-align: center;">2.52%</td>
<td style="text-align: center;">5.87%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AMZN</td>
<td style="text-align: center;">2.27%</td>
<td style="text-align: center;">5.27%</td>
</tr>
<tr class="even">
<td style="text-align: left;">SPX</td>
<td style="text-align: center;">0.95%</td>
<td style="text-align: center;">2.20%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GLD</td>
<td style="text-align: center;">1.73%</td>
<td style="text-align: center;">4.02%</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCF</td>
<td style="text-align: center;">1.76%</td>
<td style="text-align: center;">4.08%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>RiskMetrics is simple and <strong>adapts to current conditions</strong> — the S&amp;P’s low <span class="math inline">\(\sigma_T\)</span> gives a tight <span class="math inline">\(2.2\%\)</span> VaR because July 2026 was calm. Its two weaknesses are the two this book keeps returning to: it forces persistence to exactly <span class="math inline">\(1\)</span>, and it assumes <strong>normality</strong>, so it inherits the thin-tail error of <a href="#tbl-evt-var" class="quarto-xref">Table&nbsp;<span>11.1</span></a>.</p>
</section>
<section id="sec-evt-rm-multi" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="sec-evt-rm-multi"><span class="header-section-number">11.2.2</span> Multiple positions</h3>
<p>For a portfolio the volatility comes from the <strong>covariance matrix</strong> <span class="math inline">\(\Sigma\)</span> of the positions: with weights <span class="math inline">\(w\)</span>, the portfolio variance is <span class="math inline">\(\sigma_p^2 = w^\top \Sigma\,
w\)</span> and <span class="math inline">\(\text{VaR}_p = -z_p\,\sigma_p\)</span>. Because correlations are below one, <strong>diversification lowers VaR</strong>: the portfolio’s risk is less than the sum of its parts. A 50/50 S&amp;P–gold book illustrates it — the two are almost <strong>uncorrelated</strong> (correlation <span class="math inline">\(0.06\)</span>), so the combined <span class="math inline">\(99\%\)</span> VaR is <strong><span class="math inline">\(1.79\%\)</span></strong>, well below the <span class="math inline">\(2.47\%\)</span> you would get by adding the two positions’ VaRs. The <span class="math inline">\(0.68\)</span>-point gap is the diversification benefit, and it is why gold earns its place beside equities.</p>
</section>
<section id="sec-evt-rm-es" class="level3" data-number="11.2.3">
<h3 data-number="11.2.3" class="anchored" data-anchor-id="sec-evt-rm-es"><span class="header-section-number">11.2.3</span> Expected Shortfall</h3>
<div class="definition">
<p><strong>Expected Shortfall (ES)</strong>, or conditional VaR, is the <em>average</em> loss in the worst <span class="math inline">\(p\%\)</span> of cases: <span class="math inline">\(\text{ES}_p = E[L \mid L &gt; \text{VaR}_p]\)</span>. It answers “if we breach the VaR, how bad is it on average?”</p>
</div>
<p>ES fixes VaR’s blind spot — it accounts for the <em>size</em> of tail losses, not just their frequency — and unlike VaR it is <strong>coherent</strong> (a diversified book never has higher ES than the sum of parts). Under conditional normality it has a clean form,</p>
<p><span id="eq-es-normal"><span class="math display">\[
\text{ES}_p = -\mu + \sigma\,\frac{\phi(z_p)}{p},
\tag{11.2}\]</span></span></p>
<p>with <span class="math inline">\(\phi\)</span> the normal density and <span class="math inline">\(z_p = \Phi^{-1}(p)\)</span>. The last two columns of <a href="#tbl-evt-var" class="quarto-xref">Table&nbsp;<span>11.1</span></a> show the catch: because ES lives <em>further</em> out in the tail than VaR, the Normal underestimates it even more — the S&amp;P’s historical 1% ES is <span class="math inline">\(4.63\%\)</span> versus the Normal’s <span class="math inline">\(2.87\%\)</span>, a <span class="math inline">\(60\%\)</span> shortfall. Regulators have moved from VaR toward ES for exactly this reason.</p>
</section>
</section>
<section id="sec-evt-econ" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="sec-evt-econ"><span class="header-section-number">11.3</span> An econometric approach to VaR</h2>
<p>The RiskMetrics volatility is a fixed-<span class="math inline">\(\lambda\)</span> special case; the <strong>econometric approach</strong> replaces it with a properly estimated volatility model and a properly chosen innovation distribution — precisely the GARCH machinery of Chapters 8–10. The one-day VaR becomes</p>
<p><span id="eq-econ-var"><span class="math display">\[
\text{VaR}_{t}(p) = -\bigl(\mu + q_p\,\sigma_t\bigr),
\tag{11.3}\]</span></span></p>
<p>where <span class="math inline">\(\sigma_t\)</span> is the GARCH conditional volatility and <span class="math inline">\(q_p\)</span> the <span class="math inline">\(p\)</span>-quantile of the innovation — the <strong>Normal</strong> quantile, or (better, from <a href="11-garch-est.html" class="quarto-xref"><span>Chapter 10</span></a>) the fatter <strong>Student-<span class="math inline">\(t\)</span></strong> quantile. We already saw the payoff: Normal-innovation VaR was breached far too often; <span class="math inline">\(t\)</span>-innovations restored honest coverage.</p>
<section id="sec-evt-econ-multi" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="sec-evt-econ-multi"><span class="header-section-number">11.3.1</span> Multiple periods</h3>
<p>For an <span class="math inline">\(h\)</span>-day horizon, if returns are iid the variance adds, so volatility — and VaR — scale with <span class="math inline">\(\sqrt{h}\)</span> (the <strong>square-root-of-time rule</strong>), with the drift scaling linearly:</p>
<p><span id="eq-multiperiod-var"><span class="math display">\[
\text{VaR}_p(h) \approx \sqrt{h}\;\sigma\,(-q_p) - h\mu .
\tag{11.4}\]</span></span></p>
<p>The S&amp;P’s 10-day 99% VaR is thus roughly <span class="math inline">\(\sqrt{10} \approx 3.2\)</span> times the one-day figure. Under GARCH the rule is only approximate: the <span class="math inline">\(h\)</span>-step variance forecast <strong>mean-reverts</strong> (<a href="10-garch.html#sec-garch-forecast" class="quarto-xref"><span>Section 9.5</span></a>), so from an elevated start the true multiperiod VaR grows <em>slower</em> than <span class="math inline">\(\sqrt{h}\)</span>, and from a calm start, faster.</p>
</section>
<section id="sec-evt-econ-es" class="level3" data-number="11.3.2">
<h3 data-number="11.3.2" class="anchored" data-anchor-id="sec-evt-econ-es"><span class="header-section-number">11.3.2</span> Expected shortfall under conditional normality</h3>
<p>Combining the ES formula <a href="#eq-es-normal" class="quarto-xref">Equation&nbsp;<span>11.2</span></a> with a GARCH volatility gives a <strong>conditional</strong> Expected Shortfall that breathes with the market: <span class="math inline">\(\text{ES}_t(p) = -\mu +
\sigma_t\,\phi(z_p)/p\)</span>. On a calm day the shortfall is small; after a shock it widens — the same adaptivity as the conditional VaR, now measuring the <em>severity</em> of tail events rather than their threshold.</p>
</section>
</section>
<section id="sec-evt-quantile" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="sec-evt-quantile"><span class="header-section-number">11.4</span> Quantile estimation</h2>
<p>The three methods so far are increasingly elaborate <em>parametric</em> machines: RiskMetrics bolts a normal onto an EWMA variance, and the econometric approach layers a GARCH and a Student-<span class="math inline">\(t\)</span> on top. Before adding still more structure it is worth stepping back to the single idea sitting underneath all of them. Whatever the model, a VaR number is nothing but a <strong>quantile</strong> of the loss distribution — so the most basic question is how to estimate a quantile <em>directly</em>, with as few assumptions as possible. That question has two answers, one unconditional and one conditional, and between them they bracket everything else in the chapter.</p>
<section id="sec-evt-orderstat" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="sec-evt-orderstat"><span class="header-section-number">11.4.1</span> Quantiles and order statistics</h3>
<div class="definition">
<p>The <strong><span class="math inline">\(p\)</span>-quantile</strong> of a distribution is the value below which a fraction <span class="math inline">\(p\)</span> of the outcomes fall. VaR <em>is</em> a quantile of the loss distribution, so estimating VaR is estimating a quantile.</p>
</div>
<p>The model-free estimate uses <strong>order statistics</strong>: sort the returns <span class="math inline">\(r_{(1)} \le
r_{(2)} \le \cdots \le r_{(n)}\)</span>; the empirical <span class="math inline">\(p\)</span>-quantile is about <span class="math inline">\(r_{(\lceil np
\rceil)}\)</span>. Historical VaR (the left column of <a href="#tbl-evt-var" class="quarto-xref">Table&nbsp;<span>11.1</span></a>) is exactly this — no distributional assumption, which is its strength. Its weakness is the <strong>tail</strong>: the <span class="math inline">\(1\%\)</span> quantile of <span class="math inline">\(3{,}770\)</span> days rests on only <span class="math inline">\(\sim\!38\)</span> observations, and the <span class="math inline">\(0.1\%\)</span> quantile on fewer than four, so historical VaR is noisy exactly where it matters most and <em>cannot</em> speak to losses larger than the worst one observed. That limitation is the entire motivation for Extreme Value Theory below.</p>
</section>
<section id="sec-evt-qreg" class="level3" data-number="11.4.2">
<h3 data-number="11.4.2" class="anchored" data-anchor-id="sec-evt-qreg"><span class="header-section-number">11.4.2</span> Quantile regression</h3>
<div class="definition">
<p><strong>Quantile regression</strong> models a conditional <em>quantile</em> of the response as a function of covariates — where ordinary regression models the conditional <em>mean</em>.</p>
</div>
<p>Instead of minimising squared errors, quantile regression (Koenker–Bassett) minimises the asymmetric <strong>check-function</strong> loss</p>
<p><span id="eq-qreg"><span class="math display">\[
\min_{\beta}\ \sum_t \rho_\tau\!\bigl(r_t - x_t^\top\beta\bigr),
\qquad \rho_\tau(u) = u\,\bigl(\tau - \mathbf{1}\{u&lt;0\}\bigr),
\tag{11.5}\]</span></span></p>
<p>which penalises under- and over-prediction unequally so that the fitted line is the conditional <span class="math inline">\(\tau\)</span>-quantile. For risk this is direct: set <span class="math inline">\(\tau = 0.01\)</span> and regress the return quantile on covariates such as lagged volatility or a volatility index, and you have a VaR that moves with the state of the market <em>without</em> assuming a distribution. It is a semiparametric middle ground between the fully parametric GARCH VaR and the fully empirical historical VaR.</p>
</section>
</section>
<section id="sec-evt-theory" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="sec-evt-theory"><span class="header-section-number">11.5</span> Extreme value theory</h2>
<p>Order statistics gave us historical VaR, but with a warning attached: the empirical quantile is built from data, and in the far tail the data simply run out. Quantile regression added covariates but still needs observations wherever we choose to look. Both fall silent exactly where the largest losses live — beyond the worst day yet seen. Extreme Value Theory is the branch of statistics built for that region: instead of counting tail observations it never has, it models the tail’s <em>shape</em> and extrapolates it outward.</p>
<section id="sec-evt-review" class="level3" data-number="11.5.1">
<h3 data-number="11.5.1" class="anchored" data-anchor-id="sec-evt-review"><span class="header-section-number">11.5.1</span> A review of extreme value theory</h3>
<div class="definition">
<p><strong>Extreme Value Theory (EVT)</strong> describes the distribution of the <em>most extreme</em> observations, giving a principled way to model — and extrapolate into — the far tail where ordinary data run out.</p>
</div>
<p>The classical result concerns <strong>block maxima</strong>. Take the maximum of each block of <span class="math inline">\(n\)</span> iid observations; the <strong>Fisher–Tippett–Gnedenko</strong> theorem says that, suitably rescaled, this maximum can only converge to the <strong>Generalized Extreme Value (GEV)</strong> distribution,</p>
<p><span id="eq-gev"><span class="math display">\[
G(x) = \exp\!\Bigl[-\bigl(1 + \xi\,\tfrac{x-\mu}{\sigma}\bigr)^{-1/\xi}\Bigr],
\tag{11.6}\]</span></span></p>
<p>whose <strong>shape parameter <span class="math inline">\(\xi\)</span></strong> sorts all tails into three families: <strong>Gumbel</strong> (<span class="math inline">\(\xi = 0\)</span>, thin tails like the normal), <strong>Fréchet</strong> (<span class="math inline">\(\xi &gt; 0\)</span>, heavy power-law tails), and <strong>Weibull</strong> (<span class="math inline">\(\xi &lt; 0\)</span>, bounded). The single number <span class="math inline">\(\xi\)</span> decides how fat the tail is.</p>
</section>
<section id="sec-evt-empirical" class="level3" data-number="11.5.2">
<h3 data-number="11.5.2" class="anchored" data-anchor-id="sec-evt-empirical"><span class="header-section-number">11.5.2</span> Empirical estimation</h3>
<p>To fit the GEV, split the losses into blocks (say, monthly), take each block’s maximum loss, and estimate <span class="math inline">\((\mu, \sigma, \xi)\)</span> from those maxima by maximum likelihood. The sign and size of <span class="math inline">\(\hat\xi\)</span> then classify the tail.</p>
</section>
<section id="sec-evt-application" class="level3" data-number="11.5.3">
<h3 data-number="11.5.3" class="anchored" data-anchor-id="sec-evt-application"><span class="header-section-number">11.5.3</span> Application to stock returns</h3>
<p>For financial losses the answer is always the same: <strong><span class="math inline">\(\hat\xi &gt; 0\)</span>, the Fréchet case</strong> — heavy, power-law tails, exactly the fat tails of Chapter 2 seen through the lens of extremes. We quantify <span class="math inline">\(\hat\xi\)</span> precisely with the more efficient peaks-over-threshold method in <a href="#sec-evt-pot" class="quarto-xref"><span>Section 11.7</span></a>; every one of our six series comes out Fréchet.</p>
</section>
</section>
<section id="sec-evt-var-block" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="sec-evt-var-block"><span class="header-section-number">11.6</span> An extreme-value approach to VaR</h2>
<p>This section sets out <em>what</em> EVT buys a risk manager — safe extrapolation, a clean multiperiod scaling law, and return levels — while stating the results in terms of a fitted tail. The tail itself is estimated in the next section, <a href="#sec-evt-pot" class="quarto-xref"><span>Section 11.7</span></a>, using the more efficient peaks-over-threshold method, and the numbers quoted here are read back from that fit. Concept first; estimation next.</p>
<section id="sec-evt-var-disc" class="level3" data-number="11.6.1">
<h3 data-number="11.6.1" class="anchored" data-anchor-id="sec-evt-var-disc"><span class="header-section-number">11.6.1</span> Discussion</h3>
<p>The point of EVT for risk is <strong>extrapolation</strong>. Historical VaR cannot exceed the worst observed loss; the Normal has the wrong tail shape; but a fitted extreme-value tail can give a sensible VaR at <span class="math inline">\(0.1\%\)</span> or <span class="math inline">\(0.01\%\)</span> — probabilities so small that few or no observations reach them. EVT models the <em>shape</em> of the tail from the moderately-extreme data and projects it outward.</p>
</section>
<section id="sec-evt-multi" class="level3" data-number="11.6.2">
<h3 data-number="11.6.2" class="anchored" data-anchor-id="sec-evt-multi"><span class="header-section-number">11.6.2</span> Multiperiod VaR</h3>
<p>Extremes aggregate through their own scaling law: for heavy (<span class="math inline">\(\xi&gt;0\)</span>) tails the <span class="math inline">\(h\)</span>-period VaR grows roughly like <span class="math inline">\(h^{\xi}\)</span> times the one-period tail, <em>slower</em> than the number of periods but governed by the same shape parameter — a cleaner multiperiod rule than the Normal’s <span class="math inline">\(\sqrt{h}\)</span> when the tail is fat.</p>
</section>
<section id="sec-evt-return" class="level3" data-number="11.6.3">
<h3 data-number="11.6.3" class="anchored" data-anchor-id="sec-evt-return"><span class="header-section-number">11.6.3</span> Return levels</h3>
<div class="definition">
<p>The <strong><span class="math inline">\(N\)</span>-period return level</strong> is the loss expected to be exceeded on average once every <span class="math inline">\(N\)</span> periods — i.e.&nbsp;VaR at <span class="math inline">\(p = 1/N\)</span>. A “10-year return level” is the daily loss you would see about once a decade.</p>
</div>
<p>Computed from the S&amp;P’s fitted tail (estimated by peaks-over-threshold in <a href="#sec-evt-pot" class="quarto-xref"><span>Section 11.7</span></a>), the return levels are <strong><span class="math inline">\(4.4\%\)</span> once a year, <span class="math inline">\(8.5\%\)</span> once a decade, and <span class="math inline">\(12.2\%\)</span> once every 40 years</strong> — and that last figure lands right on the actual worst day in our sample (<span class="math inline">\(-12.8\%\)</span>), a reassuring check that the extreme-value model is calibrated.</p>
</section>
</section>
<section id="sec-evt-pot" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="sec-evt-pot"><span class="header-section-number">11.7</span> A modern approach: peaks over threshold</h2>
<p>This is where the fitted tail promised above actually comes from. The block-maxima route behind the GEV is wasteful — it keeps one observation per block and discards the rest — so in practice the tail is estimated a different way, which we develop now and then feed back into the VaR and return-level formulas already stated.</p>
<section id="sec-evt-pot-theory" class="level3" data-number="11.7.1">
<h3 data-number="11.7.1" class="anchored" data-anchor-id="sec-evt-pot-theory"><span class="header-section-number">11.7.1</span> Statistical theory</h3>
<div class="definition">
<p>The <strong>peaks-over-threshold (POT)</strong> method models <em>every</em> loss above a high threshold <span class="math inline">\(u\)</span>, not just block maxima. The <strong>Pickands–Balkema–de Haan</strong> theorem says these exceedances follow a <strong>Generalized Pareto Distribution (GPD)</strong>.</p>
</div>
<p>Block maxima waste data — one number per block. POT keeps every exceedance, and for a high enough threshold <span class="math inline">\(u\)</span> the excess <span class="math inline">\(Y = X - u\)</span> (given <span class="math inline">\(X &gt; u\)</span>) has the GPD</p>
<p><span id="eq-gpd"><span class="math display">\[
P(Y \le y \mid X &gt; u) = 1 - \Bigl(1 + \xi\,\tfrac{y}{\beta}\Bigr)^{-1/\xi},
\tag{11.7}\]</span></span></p>
<p>with the same <strong>shape <span class="math inline">\(\xi\)</span></strong> (tail heaviness) as the GEV and a <strong>scale <span class="math inline">\(\beta\)</span></strong>. Two parameters describe the whole tail.</p>
</section>
<section id="sec-evt-me" class="level3" data-number="11.7.2">
<h3 data-number="11.7.2" class="anchored" data-anchor-id="sec-evt-me"><span class="header-section-number">11.7.2</span> The mean-excess function</h3>
<div class="definition">
<p>The <strong>mean-excess function</strong> <span class="math inline">\(e(u) = E[X - u \mid X &gt; u]\)</span> is the average overshoot above a threshold. For a GPD tail it is <strong>linear</strong> in <span class="math inline">\(u\)</span>: <span class="math inline">\(e(u) = (\beta + \xi u)/(1
- \xi)\)</span>.</p>
</div>
<p>That linearity is the practical tool for <strong>choosing the threshold</strong> <span class="math inline">\(u\)</span>: plot the empirical mean excess against <span class="math inline">\(u\)</span> and pick the point beyond which it becomes a straight line. <a href="#fig-evt-meanexcess" class="quarto-xref">Figure&nbsp;<span>11.3</span></a> does this for the S&amp;P — the plot straightens above roughly <span class="math inline">\(1.5\%\)</span>, so we set the threshold at the <span class="math inline">\(95\)</span>th percentile of losses.</p>
<div id="fig-evt-meanexcess" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evt-meanexcess-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/evt_meanexcess.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evt-meanexcess-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.3: S&amp;P 500 mean-excess plot. Above a threshold of about 1.5% the mean overshoot rises roughly linearly with the threshold — the signature of a GPD (heavy) tail — which is where we anchor the fit.
</figcaption>
</figure>
</div>
</section>
<section id="sec-evt-pot-fit" class="level3" data-number="11.7.3">
<h3 data-number="11.7.3" class="anchored" data-anchor-id="sec-evt-pot-fit"><span class="header-section-number">11.7.3</span> Modelling the extreme values</h3>
<p>Fitting the GPD to the S&amp;P’s exceedances above <span class="math inline">\(u = 1.65\%\)</span> (<span class="math inline">\(189\)</span> of them) by maximum likelihood gives <strong><span class="math inline">\(\hat\xi = 0.21\)</span></strong> and <span class="math inline">\(\hat\beta = 0.81\%\)</span>. A positive <span class="math inline">\(\hat\xi\)</span> is the Fréchet, power-law tail; its reciprocal <span class="math inline">\(1/\hat\xi \approx 4.7\)</span> is the <strong>tail index</strong> — the effective number of finite moments — and it matches the Student-<span class="math inline">\(t\)</span> degrees of freedom (<span class="math inline">\(\hat\nu \approx 5.6\)</span>) we estimated for the S&amp;P in <a href="11-garch-est.html" class="quarto-xref"><span>Chapter 10</span></a>. <a href="#fig-evt-tailfit" class="quarto-xref">Figure&nbsp;<span>11.4</span></a> shows the fit: the empirical exceedances lie on the GPD line, while the Normal tail dives away by ten orders of magnitude. Across all six series the tail is uniformly heavy:</p>
<div id="tbl-evt-xi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-evt-xi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.3: GPD tail-shape estimates (POT, 95th-percentile threshold)
</figcaption>
<div aria-describedby="tbl-evt-xi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Ticker</th>
<th style="text-align: center;">GPD shape <span class="math inline">\(\hat\xi\)</span></th>
<th style="text-align: center;">tail index <span class="math inline">\(1/\hat\xi\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AAPL</td>
<td style="text-align: center;">0.167</td>
<td style="text-align: center;">6.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">MSFT</td>
<td style="text-align: center;">0.203</td>
<td style="text-align: center;">4.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AMZN</td>
<td style="text-align: center;">0.162</td>
<td style="text-align: center;">6.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">SPX</td>
<td style="text-align: center;">0.213</td>
<td style="text-align: center;">4.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GLD</td>
<td style="text-align: center;">0.251</td>
<td style="text-align: center;">4.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCF</td>
<td style="text-align: center;">0.243</td>
<td style="text-align: center;">4.1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-evt-tailfit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-evt-tailfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figs/evt_tailfit.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-evt-tailfit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.4: S&amp;P 500 loss tail on a log scale. The empirical exceedances (dots) sit on the fitted GPD line (ξ = 0.21); the Normal tail (dashed) collapses far too fast, understating extreme losses by many orders of magnitude.
</figcaption>
</figure>
</div>
<p>Every <span class="math inline">\(\hat\xi\)</span> is positive; <strong>gold has the heaviest tail</strong> (<span class="math inline">\(\hat\xi \approx 0.25\)</span>, tail index <span class="math inline">\(\approx 4\)</span>), a reminder that “safe haven” refers to low <em>average</em> volatility, not to a thin tail.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">R</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Python</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(evir)                                   <span class="co"># or POT / extRemes / ismev</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>loss <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">diff</span>(<span class="fu">log</span>(<span class="fu">read.csv</span>(<span class="st">"data/SPX.csv"</span>)<span class="sc">$</span>Adjusted))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>fit  <span class="ot">&lt;-</span> <span class="fu">gpd</span>(loss, <span class="at">threshold =</span> <span class="fu">quantile</span>(loss, <span class="fl">0.95</span>))   <span class="co"># fit GPD to exceedances</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>fit<span class="sc">$</span>par.ests                                    <span class="co"># xi (shape), beta (scale)</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">riskmeasures</span>(fit, <span class="fl">0.999</span>)                         <span class="co"># extreme VaR and ES at 99.9%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> genpareto</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>loss <span class="op">=</span> <span class="op">-</span>np.log(pd.read_csv(<span class="st">"data/SPX.csv"</span>)[<span class="st">"Adjusted"</span>]).diff().dropna()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> loss.quantile(<span class="fl">0.95</span>)<span class="op">;</span> y <span class="op">=</span> loss[loss <span class="op">&gt;</span> u] <span class="op">-</span> u</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>xi, _, beta <span class="op">=</span> genpareto.fit(y, floc<span class="op">=</span><span class="dv">0</span>)          <span class="co"># shape xi, scale beta</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>n, Nu <span class="op">=</span> <span class="bu">len</span>(loss), <span class="bu">len</span>(y)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>VaR <span class="op">=</span> u <span class="op">+</span> (beta<span class="op">/</span>xi) <span class="op">*</span> ((n<span class="op">/</span>Nu <span class="op">*</span> <span class="fl">0.001</span>)<span class="op">**</span>(<span class="op">-</span>xi) <span class="op">-</span> <span class="dv">1</span>)   <span class="co"># 99.9% EVT VaR</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="sec-evt-pot-var" class="level3" data-number="11.7.4">
<h3 data-number="11.7.4" class="anchored" data-anchor-id="sec-evt-pot-var"><span class="header-section-number">11.7.4</span> VaR from the POT approach</h3>
<p>Inverting the GPD tail gives closed-form extreme VaR and ES:</p>
<p><span id="eq-gpd-var"><span class="math display">\[
\text{VaR}_p = u + \frac{\beta}{\xi}\Bigl[\bigl(\tfrac{n}{N_u}\,p\bigr)^{-\xi} - 1\Bigr],
\qquad
\text{ES}_p = \frac{\text{VaR}_p}{1-\xi} + \frac{\beta - \xi u}{1-\xi},
\tag{11.8}\]</span></span></p>
<p>where <span class="math inline">\(N_u\)</span> is the number of exceedances out of <span class="math inline">\(n\)</span>. The comparison at deep levels is the punchline of the chapter:</p>
<div id="tbl-evt-compare" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-evt-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.4: S&amp;P 500 VaR by method, at deep tail levels
</figcaption>
<div aria-describedby="tbl-evt-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Level <span class="math inline">\(p\)</span></th>
<th style="text-align: center;">EVT (GPD) VaR</th>
<th style="text-align: center;">Normal VaR</th>
<th style="text-align: center;">Historical VaR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.0%</td>
<td style="text-align: center;">3.21%</td>
<td style="text-align: center;">2.50%</td>
<td style="text-align: center;">3.17%</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.5%</td>
<td style="text-align: center;">4.06%</td>
<td style="text-align: center;">2.77%</td>
<td style="text-align: center;">3.96%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.1%</td>
<td style="text-align: center;"><strong>6.61%</strong></td>
<td style="text-align: center;"><strong>3.33%</strong></td>
<td style="text-align: center;">6.33%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>At <span class="math inline">\(p = 0.1\%\)</span> the EVT VaR is <strong><span class="math inline">\(6.6\%\)</span> against the Normal’s <span class="math inline">\(3.3\%\)</span></strong> — the Normal understates the once-in-1000-day loss by half. EVT agrees closely with the historical figure where data still exist, but unlike historical it <strong>extrapolates</strong> smoothly to levels beyond any observed loss (its <span class="math inline">\(99.9\%\)</span> ES is <span class="math inline">\(9.0\%\)</span>).</p>
</section>
<section id="sec-evt-pot-covariates" class="level3" data-number="11.7.5">
<h3 data-number="11.7.5" class="anchored" data-anchor-id="sec-evt-pot-covariates"><span class="header-section-number">11.7.5</span> Using explanatory variables</h3>
<p>The one thing plain POT misses is <em>time variation</em>: the threshold and scale are constant, but we know volatility clusters. The state of the art fixes this by letting the tail depend on covariates — most cleanly the <strong>GARCH–EVT (filtered EVT)</strong> two-step: first fit a GARCH to strip out volatility clustering, then apply POT-GPD to the <strong>standardised residuals</strong> (which are iid), and finally <em>rescale</em> the extreme quantile by today’s GARCH volatility <span class="math inline">\(\sigma_t\)</span>. This marries the two halves of the whole book — <strong>GARCH for the time-varying volatility, EVT for the tail shape</strong> — and is the best-performing VaR method in practice. One can equivalently make the GPD scale a function of covariates, <span class="math inline">\(\beta_t = \beta_0\exp(\gamma\,\sigma_t)\)</span>.</p>
</section>
<section id="sec-evt-illustration" class="level3" data-number="11.7.6">
<h3 data-number="11.7.6" class="anchored" data-anchor-id="sec-evt-illustration"><span class="header-section-number">11.7.6</span> A general illustration</h3>
<p>Putting the four methods side by side for the S&amp;P sums up the chapter. All agree near the centre; they diverge in the tail, and the divergence is where risk lives:</p>
<ul>
<li><strong>Historical</strong> — model-free and reliable at <span class="math inline">\(1\%\)</span>–<span class="math inline">\(5\%\)</span>, but blind beyond the worst observed loss and noisy in the far tail.</li>
<li><strong>Normal / RiskMetrics</strong> — adapts to current volatility, but its thin tail <em>systematically understates</em> extreme losses (half the true <span class="math inline">\(0.1\%\)</span> VaR).</li>
<li><strong>GARCH-<span class="math inline">\(t\)</span></strong> — adapts to volatility <em>and</em> uses a fat-tailed innovation, giving well-calibrated VaR (Chapter 10’s backtest).</li>
<li><strong>EVT / GARCH-EVT</strong> — targets the tail <em>shape</em> directly, extrapolates safely to extreme levels, and combined with GARCH is the most accurate of all.</li>
</ul>
<p>The message is the one the book has built toward from Chapter 2: <strong>the tail is fatter than the bell curve allows, and pretending otherwise is exactly the mistake that shows up as a blown risk limit on the worst day.</strong></p>
</section>
</section>
<section id="sec-evt-extremal" class="level2" data-number="11.8">
<h2 data-number="11.8" class="anchored" data-anchor-id="sec-evt-extremal"><span class="header-section-number">11.8</span> The extremal index: when extremes cluster</h2>
<p>Everything so far quietly assumed the exceedances were <strong>independent</strong>. They are not. The whole book has shown volatility <em>clusters</em>, and extreme losses cluster with it: the S&amp;P’s worst stretch was not one bad day but a <strong>15-day run</strong> of extreme losses in February–April 2020. Classical EVT must be corrected for this dependence — and the correction is a single number.</p>
<div class="definition">
<p>The <strong>extremal index</strong> <span class="math inline">\(\theta \in (0,1]\)</span> measures how much a stationary series’ extremes cluster. <span class="math inline">\(\theta = 1\)</span> means extremes arrive independently; <span class="math inline">\(\theta &lt; 1\)</span> means they come in clusters, and <span class="math inline">\(1/\theta\)</span> is the <strong>mean cluster size</strong>.</p>
</div>
<section id="sec-evt-dun" class="level3" data-number="11.8.1">
<h3 data-number="11.8.1" class="anchored" data-anchor-id="sec-evt-dun"><span class="header-section-number">11.8.1</span> The D(<span class="math inline">\(u_n\)</span>) condition</h3>
<p>For the maximum of a <em>stationary</em> (not iid) series to still converge to a Generalized Extreme Value law, its long-range dependence must fade at high levels — Leadbetter’s <strong>D(<span class="math inline">\(u_n\)</span>) condition</strong>, a mixing condition under which events far apart in time become asymptotically independent when the threshold <span class="math inline">\(u_n\)</span> is high. Under D(<span class="math inline">\(u_n\)</span>) the maximum still has a GEV limit, but modified by the extremal index:</p>
<p><span id="eq-extremal"><span class="math display">\[
P(M_n \le u_n) \;\longrightarrow\; G(x)^{\theta},
\tag{11.9}\]</span></span></p>
<p>so a stationary series’ extremes behave like those of an iid series of the <em>reduced</em> effective length <span class="math inline">\(n\theta\)</span>. A stronger condition, <strong>D<span class="math inline">\('(u_n)\)</span></strong>, additionally forbids <em>local</em> clustering; when it holds, <span class="math inline">\(\theta = 1\)</span>. For financial returns D(<span class="math inline">\(u_n\)</span>) holds (returns mix) but D<span class="math inline">\('(u_n)\)</span> fails (volatility clustering bunches the extremes), so <span class="math inline">\(\theta &lt; 1\)</span>.</p>
</section>
<section id="sec-evt-theta-est" class="level3" data-number="11.8.2">
<h3 data-number="11.8.2" class="anchored" data-anchor-id="sec-evt-theta-est"><span class="header-section-number">11.8.2</span> Estimating the extremal index</h3>
<p>Two standard estimators are used:</p>
<ul>
<li><strong>Blocks method</strong> — split the sample into blocks, then <span class="math inline">\(\hat\theta \approx (\text{number
of blocks with an exceedance}) / (\text{total exceedances})\)</span>.</li>
<li><strong>Intervals (Ferro–Segers) method</strong> — uses the <em>gaps</em> between exceedances: long gaps (isolated extremes) push <span class="math inline">\(\theta\)</span> toward 1, short gaps (clusters) pull it down.</li>
</ul>
<p>Applied to our series (95th-percentile threshold):</p>
<div id="tbl-evt-theta" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-evt-theta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.5: Extremal index and mean cluster size (Ferro–Segers, 95th-pct threshold)
</figcaption>
<div aria-describedby="tbl-evt-theta-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Ticker</th>
<th style="text-align: center;"><span class="math inline">\(\hat\theta\)</span></th>
<th style="text-align: center;">mean cluster size <span class="math inline">\(1/\hat\theta\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AAPL</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">1.7 days</td>
</tr>
<tr class="even">
<td style="text-align: left;">MSFT</td>
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">1.7 days</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AMZN</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">1.7 days</td>
</tr>
<tr class="even">
<td style="text-align: left;">SPX</td>
<td style="text-align: center;">0.48</td>
<td style="text-align: center;">2.1 days</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GLD</td>
<td style="text-align: center;">0.39</td>
<td style="text-align: center;">2.6 days</td>
</tr>
<tr class="even">
<td style="text-align: left;">GCF</td>
<td style="text-align: center;">0.54</td>
<td style="text-align: center;">1.8 days</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Every <span class="math inline">\(\hat\theta\)</span> is well below one: extreme losses <strong>cluster</strong> in all six series, with typical clusters of two to three days. The S&amp;P’s <span class="math inline">\(189\)</span> threshold exceedances form only about <span class="math inline">\(120\)</span> distinct episodes, and its single largest cluster is the <strong>15-day Feb–Apr 2020 crash</strong> — one event, not fifteen. Note that <strong>gold has the lowest <span class="math inline">\(\theta\)</span></strong> (<span class="math inline">\(0.39\)</span>, cluster size <span class="math inline">\(2.6\)</span>), the most-clustered extremes of the group — the same message as its highest GARCH persistence and longest volatility half-life: when gold turns turbulent, it <em>stays</em> turbulent.</p>
</section>
<section id="sec-evt-var-stationary" class="level3" data-number="11.8.3">
<h3 data-number="11.8.3" class="anchored" data-anchor-id="sec-evt-var-stationary"><span class="header-section-number">11.8.3</span> Value at Risk for a stationary time series</h3>
<p>The extremal index tells us what to adjust and what to leave alone. The <strong>one-day (marginal) VaR is unaffected</strong> — it is a quantile of the marginal loss distribution, and <span class="math inline">\(\theta\)</span> describes <em>timing</em>, not the marginal tail. But two things do change:</p>
<ul>
<li><strong>Return levels and multiperiod VaR.</strong> Because extremes cluster, the <em>rate of distinct extreme events</em> is <span class="math inline">\(\theta\)</span> times the marginal exceedance rate, so the once-in-<span class="math inline">\(N\)</span> level uses <span class="math inline">\(n\theta\)</span> in place of <span class="math inline">\(n\)</span> (from 1). Ignoring <span class="math inline">\(\theta\)</span> overstates how often <em>new</em> extreme episodes occur.</li>
<li><strong>Drawdown risk.</strong> Since a breach tends to be followed by more (mean cluster size <span class="math inline">\(1/\theta \approx 2\)</span>–<span class="math inline">\(3\)</span> days), the <em>cumulative</em> loss over a cluster is far worse than an iid model implies — the real danger of a crash is the run, not the single day.</li>
</ul>
<p>The clean practical fix is the <strong>GARCH-EVT</strong> procedure of <a href="#sec-evt-pot-covariates" class="quarto-xref"><span>Section 11.7.5</span></a>: fitting a GARCH first removes the volatility clustering, so the standardised residuals are close to iid (<span class="math inline">\(\theta \approx 1\)</span>) and ordinary POT-EVT applies to them directly. Filtering restores independence; rescaling by today’s <span class="math inline">\(\sigma_t\)</span> puts the clustering back where it belongs — in the <em>conditional</em> forecast. This is why <strong>GARCH and EVT are complementary</strong>: GARCH captures <em>when</em> volatility is high, EVT <em>how heavy</em> the tail is, and the extremal index is the bridge that explains why you need both.</p>
</section>
</section>
<section id="sec-evt-concept" class="level2" data-number="11.9">
<h2 data-number="11.9" class="anchored" data-anchor-id="sec-evt-concept"><span class="header-section-number">11.9</span> Concept check</h2>
<p>Decide first, then expand each answer.</p>
<p><strong>Q1. A 1-day 99% VaR of 3% means:</strong></p>
<ul>
<li><strong>(a)</strong> you will lose exactly 3% tomorrow.</li>
<li><strong>(b)</strong> on about 1 day in 100 the loss will <em>exceed</em> 3%.</li>
<li><strong>(c)</strong> the average daily loss is 3%.</li>
<li><strong>(d)</strong> you can never lose more than 3%.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(b).</strong> VaR is the loss exceeded with probability <span class="math inline">\(p\)</span> — a threshold, not a maximum, and it says nothing about how bad the breach is (that’s Expected Shortfall).</p>
</div>
</div>
</div>
<p><strong>Q2. Why does Expected Shortfall exceed VaR, and why is it preferred by regulators?</strong></p>
<ul>
<li><strong>(a)</strong> ES uses a higher confidence level.</li>
<li><strong>(b)</strong> ES is the <em>average</em> loss beyond the VaR, so it captures tail <em>severity</em>; it is also coherent (rewards diversification), which VaR is not.</li>
<li><strong>(c)</strong> ES ignores the tail.</li>
<li><strong>(d)</strong> They are equal.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(b).</strong> ES averages over the losses past the VaR threshold, so it is larger and sensitive to how fat the tail is.</p>
</div>
</div>
</div>
<p><strong>Q3. Why can’t historical VaR estimate a 0.1% (once-in-1000-day) loss reliably?</strong></p>
<ul>
<li><strong>(a)</strong> It assumes normality.</li>
<li><strong>(b)</strong> A <span class="math inline">\(0.1\%\)</span> quantile of a few thousand days rests on only a handful of observations, and it cannot exceed the worst loss ever seen.</li>
<li><strong>(c)</strong> It requires a GARCH model.</li>
<li><strong>(d)</strong> It is always too large.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(b).</strong> The far tail has too few data; EVT extrapolates the tail <em>shape</em> instead.</p>
</div>
</div>
</div>
<p><strong>Q4. A fitted GPD tail has <span class="math inline">\(\hat\xi = 0.21 &gt; 0\)</span>. This means the tail is:</strong></p>
<ul>
<li><strong>(a)</strong> thin, like a normal (Gumbel).</li>
<li><strong>(b)</strong> bounded (Weibull).</li>
<li><strong>(c)</strong> heavy / power-law (Fréchet), with tail index <span class="math inline">\(1/\xi \approx 5\)</span> finite moments.</li>
<li><strong>(d)</strong> exactly exponential.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(c).</strong> <span class="math inline">\(\xi&gt;0\)</span> is the Fréchet, heavy-tailed case; <span class="math inline">\(1/\xi\)</span> is the tail index, matching the Student-<span class="math inline">\(t\)</span> degrees of freedom found earlier.</p>
</div>
</div>
</div>
<p><strong>Q5. A series has an estimated extremal index <span class="math inline">\(\hat\theta = 0.48\)</span>. This means:</strong></p>
<ul>
<li><strong>(a)</strong> its extremes are independent.</li>
<li><strong>(b)</strong> its extremes <strong>cluster</strong> — they arrive in episodes of mean size <span class="math inline">\(1/\theta
\approx 2\)</span> days, so a bad day tends to be followed by more.</li>
<li><strong>(c)</strong> it has no extreme values.</li>
<li><strong>(d)</strong> its one-day VaR is doubled.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Show answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>(b).</strong> <span class="math inline">\(\theta&lt;1\)</span> signals clustered extremes (here mean cluster size <span class="math inline">\(\approx 2\)</span>). The marginal one-day VaR is unchanged, but return levels and drawdown risk must account for the clustering — or you filter it out first with GARCH.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key takeaways
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>VaR</strong> (<a href="#eq-econ-var" class="quarto-xref">Equation&nbsp;<span>11.3</span></a>) is the loss exceeded with probability <span class="math inline">\(p\)</span>; <strong>Expected Shortfall</strong> (<a href="#eq-es-normal" class="quarto-xref">Equation&nbsp;<span>11.2</span></a>) averages the losses beyond it and is the coherent, regulator-preferred measure.</li>
<li><strong>RiskMetrics</strong> is EWMA volatility (<a href="#eq-ewma" class="quarto-xref">Equation&nbsp;<span>11.1</span></a>) plus normality — simple and adaptive, but thin-tailed; diversification lowers portfolio VaR (S&amp;P–gold correlation <span class="math inline">\(0.06\)</span>).</li>
<li>The <strong>econometric</strong> approach uses GARCH volatility with a <span class="math inline">\(t\)</span> quantile (<a href="#eq-econ-var" class="quarto-xref">Equation&nbsp;<span>11.3</span></a>) and scales roughly like <span class="math inline">\(\sqrt{h}\)</span> over <span class="math inline">\(h\)</span> days.</li>
<li>Historical VaR is a <strong>quantile</strong> from order statistics — model-free but tail-limited; <strong>quantile regression</strong> (<a href="#eq-qreg" class="quarto-xref">Equation&nbsp;<span>11.5</span></a>) models conditional quantiles on covariates.</li>
<li><strong>EVT</strong> models the tail directly: block maxima give the <strong>GEV</strong> (<a href="#eq-gev" class="quarto-xref">Equation&nbsp;<span>11.6</span></a>), and the modern <strong>POT</strong> method gives the <strong>GPD</strong> (<a href="#eq-gpd" class="quarto-xref">Equation&nbsp;<span>11.7</span></a>). Our tails are all heavy (<span class="math inline">\(\hat\xi = 0.16\)</span>–<span class="math inline">\(0.25\)</span>, <a href="#tbl-evt-xi" class="quarto-xref">Table&nbsp;<span>11.3</span></a>).</li>
<li><strong>EVT VaR</strong> (<a href="#eq-gpd-var" class="quarto-xref">Equation&nbsp;<span>11.8</span></a>) extrapolates the tail: at <span class="math inline">\(0.1\%\)</span> the S&amp;P’s EVT VaR is <span class="math inline">\(6.6\%\)</span> versus the Normal’s <span class="math inline">\(3.3\%\)</span> (<a href="#tbl-evt-compare" class="quarto-xref">Table&nbsp;<span>11.4</span></a>). <strong>GARCH-EVT</strong> — GARCH for volatility, EVT for the tail — is the most accurate method of all.</li>
<li>Real extremes <strong>cluster</strong> (returns aren’t iid): the <strong>extremal index</strong> <span class="math inline">\(\theta&lt;1\)</span>
<ol class="example" type="1">
<li>measures it — <span class="math inline">\(\hat\theta \approx 0.4\)</span>–<span class="math inline">\(0.6\)</span>, cluster size <span class="math inline">\(1.7\)</span>–<span class="math inline">\(2.6\)</span> days (<a href="#tbl-evt-theta" class="quarto-xref">Table&nbsp;<span>11.5</span></a>). It leaves the one-day VaR unchanged but worsens <strong>drawdowns</strong>; GARCH filtering restores independence.</li>
</ol></li>
</ul>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/11-garch-est.html" class="pagination-link" aria-label="Estimating and Evaluating Volatility Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Estimating and Evaluating Volatility Models</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/14-options.html" class="pagination-link" aria-label="Options: Contracts, Payoffs, and the Greeks">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Options: Contracts, Payoffs, and the Greeks</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Time Series Analysis in Financial Econometrics</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>