import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';

// Course pages are generated by scanning `public/lectures/<course>` at build time.
// Every file found there is published. `src/data/lectures.yml` only supplies the
// presentation — nicer titles, summaries, and grouping. A file with no entry in the
// YAML still appears, under "Additional materials", so nothing is ever silently missing.

const LECTURES_ROOT = path.resolve('public/lectures');
const META_PATH = path.resolve('src/data/lectures.yml');

// Never published, whatever the YAML says. (Dotfiles like .DS_Store are skipped
// during the scan itself.)
const ALWAYS_HIDDEN = ['**/*.log'];

const KIND_LABELS: Record<string, string> = {
    pdf: 'PDF',
    html: 'HTML',
    r: 'R',
    rmd: 'R notebook',
    csv: 'CSV',
    xlsx: 'Excel',
    do: 'Stata',
    py: 'Python',
    ipynb: 'Notebook',
    zip: 'ZIP',
    md: 'Markdown',
    tex: 'TeX'
};

const collator = new Intl.Collator('en', { numeric: true, sensitivity: 'base' });

export type LectureFile = {
    /** Path relative to the course folder, e.g. `Week_1/FI362_Ch1.pdf`. */
    rel: string;
    /** Site URL, e.g. `/lectures/FE/Week_1/FI362_Ch1.pdf`. */
    href: string;
    /** Link text, e.g. `Slides`. */
    label: string;
    /** Type badge, e.g. `PDF`. */
    kind: string;
};

export type LectureItem = {
    /** Left-hand column, e.g. `Day 1` or `Chapter 1`. */
    label: string;
    title: string;
    summary?: string;
    files: LectureFile[];
};

export type LectureSection = {
    title: string;
    note?: string;
    items: LectureItem[];
};

export type Course = {
    id: string;
    href: string;
    title: string;
    code: string;
    level: string;
    eyebrow: string;
    blurb: string;
    intro: string;
    /** Standalone links shown above the tables, e.g. the module handbook. */
    top: LectureFile[];
    /** Featured links to things that are not files in the course folder, e.g. the book. */
    links: CourseLink[];
    sections: LectureSection[];
};

export type CourseLink = { label: string; href: string; note?: string };

type MetaFile = { path: string; label?: string };
type MetaItem = { label?: string; title?: string; summary?: string; files?: Array<string | MetaFile> };
type MetaSection = { title: string; note?: string; items?: MetaItem[] };
type MetaCourse = {
    id: string;
    title: string;
    code?: string;
    level?: string;
    eyebrow?: string;
    blurb?: string;
    intro?: string;
    hide?: string[];
    top?: Array<string | MetaFile>;
    links?: CourseLink[];
    sections?: MetaSection[];
};

/** `Week1_ProblemSets` -> `Week 1 Problem Sets`; `ec107-day1` -> `Ec 107 Day 1`. */
function humanize(name: string): string {
    return name
        .replace(/[_-]+/g, ' ')
        .replace(/([a-z])([A-Z])/g, '$1 $2')
        .replace(/([A-Za-z])(\d)/g, '$1 $2')
        .replace(/\s+/g, ' ')
        .trim()
        .replace(/\b[a-z]/g, (c) => c.toUpperCase());
}

/** Supports `*` (within a path segment) and `**` (across segments). */
function globToRegExp(glob: string): RegExp {
    let source = '';
    for (let i = 0; i < glob.length; i++) {
        const char = glob[i];
        if (char === '*' && glob[i + 1] === '*') {
            i++;
            if (glob[i + 1] === '/') {
                i++;
                source += '(?:.*/)?'; // `**/` also matches zero directories
            } else {
                source += '.*';
            }
        } else if (char === '*') {
            source += '[^/]*';
        } else if (char === '?') {
            source += '[^/]';
        } else {
            source += char.replace(/[.+^${}()|[\]\\]/g, '\\$&');
        }
    }
    return new RegExp(`^${source}$`);
}

function listFiles(dir: string, base = ''): string[] {
    let entries: fs.Dirent[];
    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return [];
    }
    return entries.flatMap((entry) => {
        if (entry.name.startsWith('.')) return [];
        const rel = base ? `${base}/${entry.name}` : entry.name;
        if (entry.isDirectory()) return listFiles(path.join(dir, entry.name), rel);
        return entry.isFile() ? [rel] : [];
    });
}

function makeFile(courseId: string, rel: string, label?: string): LectureFile {
    const ext = path.extname(rel).slice(1).toLowerCase();
    return {
        rel,
        href: `/lectures/${courseId}/${rel}`,
        label: label ?? humanize(path.basename(rel, path.extname(rel))),
        kind: KIND_LABELS[ext] ?? ext.toUpperCase()
    };
}

function readMeta(): MetaCourse[] {
    const raw = yaml.load(fs.readFileSync(META_PATH, 'utf-8')) as { courses?: MetaCourse[] } | undefined;
    return raw?.courses ?? [];
}

export function getCourses(): Course[] {
    return readMeta().map((meta) => {
        const courseDir = path.join(LECTURES_ROOT, meta.id);
        const hidden = [...ALWAYS_HIDDEN, ...(meta.hide ?? [])].map(globToRegExp);
        const onDisk = listFiles(courseDir).sort((a, b) => collator.compare(a, b));

        // `hide` suppresses auto-listing only. A file named explicitly in the YAML is
        // always published — that is how a single entry point (a rendered book's
        // index.html) can be linked while its hundreds of assets stay out of the way.
        const isHidden = (rel: string) => hidden.some((re) => re.test(rel));

        const known = new Set(onDisk);
        const claimed = new Set<string>();

        // Only resolve paths that exist on disk, so a stale YAML entry for a deleted
        // file cannot produce a dead link.
        const resolve = (entry: string | MetaFile): LectureFile | null => {
            const rel = typeof entry === 'string' ? entry : entry.path;
            if (!known.has(rel)) return null;
            claimed.add(rel);
            return makeFile(meta.id, rel, typeof entry === 'string' ? undefined : entry.label);
        };

        const isFile = (file: LectureFile | null): file is LectureFile => file !== null;

        const top = (meta.top ?? []).map(resolve).filter(isFile);

        const sections: LectureSection[] = (meta.sections ?? [])
            .map((section) => ({
                title: section.title,
                note: section.note,
                items: (section.items ?? [])
                    .map((item) => {
                        const files = (item.files ?? []).map(resolve).filter(isFile);
                        return {
                            label: item.label ?? '',
                            title: item.title ?? (files[0]?.label ?? ''),
                            summary: item.summary,
                            files
                        };
                    })
                    .filter((item) => item.files.length > 0)
            }))
            .filter((section) => section.items.length > 0);

        // Anything on disk the YAML did not place still gets published, grouped by folder.
        const unclaimed = onDisk.filter((rel) => !claimed.has(rel) && !isHidden(rel));
        if (unclaimed.length > 0) {
            const byFolder = new Map<string, string[]>();
            for (const rel of unclaimed) {
                const dir = path.dirname(rel);
                const folder = dir === '.' ? '' : dir;
                byFolder.set(folder, [...(byFolder.get(folder) ?? []), rel]);
            }
            sections.push({
                title: 'Additional materials',
                note: 'Newly added files. To give one a title and summary, or move it into a table above, add it to src/data/lectures.yml.',
                items: [...byFolder.entries()]
                    .sort((a, b) => collator.compare(a[0], b[0]))
                    .map(([folder, files]) => ({
                        label: folder ? humanize(folder) : 'Course files',
                        title: '',
                        files: files.map((rel) => makeFile(meta.id, rel))
                    }))
            });
        }

        return {
            id: meta.id,
            href: `/lectures/${meta.id}`,
            title: meta.title,
            code: meta.code ?? '',
            level: meta.level ?? '',
            eyebrow: meta.eyebrow ?? [meta.code, meta.level].filter(Boolean).join(' · '),
            blurb: meta.blurb ?? '',
            intro: meta.intro ?? meta.blurb ?? '',
            top,
            links: meta.links ?? [],
            sections
        };
    });
}
